// Auto-generated by scripts/embed-references.ts
// Source: cebuano-curriculum-reference.md
// Do not edit by hand. Re-run the embedding script if the source changes.

export const cebuanoReference = `# Cebuano (Bisaya) Curriculum Reference

**Purpose.** This is the Cebuano-specific knowledge base for the language learning project. It applies the universal pedagogical framework (see \`pedagogy-foundations.md\`) to Cebuano: how Cebuano is characterized along the seven dimensions, why specific variety decisions were made, the full 160-week curriculum architecture aligned to CEFR levels, Cebuano-specific resources and assessment paths, and notes on what English speakers (and Tagalog/Filipino speakers transitioning) find hard about Cebuano specifically.

**Companion documents.**
- \`pedagogy-foundations.md\` — Universal principles + the seven-dimensional framework
- \`filipino-curriculum-reference.md\` — closest cousin (same family, same Austronesian voice system; many systematic parallels and key differences)
- \`swahili-curriculum-reference.md\` — closest analog for Latin-alphabet agglutinative morphology
- \`japanese-curriculum-reference.md\`, \`korean-curriculum-reference.md\` — closest analogs for particle-based case marking
- \`hindi-curriculum-reference.md\`, \`russian-curriculum-reference.md\` — closest analogs for FSI Category III curriculum length
- \`claude-code-prompt.md\` — The build spec for the lesson-generator app
- This document — Cebuano-specific reference

**Cebuano's significance for the framework.** Cebuano demonstrates that the framework can handle multiple languages within the same family without collapsing them. Cebuano shares its general architecture with Filipino/Tagalog — both are Central Philippine Austronesian languages with the voice/focus system, predicate-initial word order, agglutinative morphology, and case-marker particles. But they are **not mutually intelligible**, they have **distinct grammatical markers and pronouns**, and they have **separate cultural identities and literary traditions**. Treating them as separate languages — which they are linguistically — rather than as variants of "Filipino" is both more accurate and more respectful of the Visayan cultural reality.

**Cebuano vs. Filipino/Tagalog (upfront comparison).** The most important things a learner needs to know before starting:

| Feature | Filipino/Tagalog | Cebuano (Bisaya) |
|---|---|---|
| Marker system | ang / ng / sa | **ang / ug / sa** |
| "We" (you and I) | tayo | **kita** (inclusive) |
| "We" (us, not you) | kami | **kami** (exclusive — distinguished!) |
| Actor focus prefix | -um-, mag- | **mu-, mi-, mag-** |
| Object focus suffix | -in | **-on** |
| Politeness particles | po, opo | **No po/opo** (politeness shown differently) |
| Vowel system tendency | More e and o | More **i and u** (older 3-vowel system) |
| "Where" | saan | **asa** |
| "What" | ano | **unsa** |
| "How are you" | Kumusta? | **Kumusta?** (same — Spanish borrowing) |
| Native speakers | ~22-30 million | **~21-27 million** |
| Cultural identity | Tagalog/Filipino | **Bisaya/Visayan** (distinct) |

Cebuano speakers and Tagalog speakers cannot have a fluent conversation without prior exposure to the other language. They are sister languages, not dialects of each other.

---

# PART 1 — CEBUANO LANGUAGE PROFILE

## 1.1 Basic Facts

- **Native speakers (L1):** ~21-27 million — the largest single language in the Philippines by native speakers, surpassing Tagalog
- **Total Cebuano speakers (L1 + L2):** ~30+ million across the Visayas and Mindanao
- **Geographic distribution:** Cebu province (Central Visayas — the heartland), Bohol, Negros Oriental (eastern Negros), western Leyte (the eastern parts speak Waray), Siquijor; most of Mindanao especially Cagayan de Oro, Davao, Misamis Oriental, Bukidnon, parts of Lanao and Cotabato; smaller communities throughout the Philippines and the diaspora
- **Diaspora communities:** US (significant Bisaya communities in California, Hawaii, NYC area, Las Vegas — often distinct from Tagalog-speaking Filipino diaspora), UAE, Saudi Arabia, Hong Kong, Singapore, Japan, UK, Italy
- **Official status:** Cebuano is one of the regional auxiliary languages recognized in the 1987 Philippine Constitution, but does not have official status in the way Filipino and English do. Cebuano is used as a regional medium of education in Cebuano-speaking areas under the K-12 Mother Tongue-Based Multilingual Education policy.
- **ISO 639-1 code:** ceb
- **Linguistic family:** Austronesian → Malayo-Polynesian → Philippine → Central Philippine → Visayan (Bisayan) → Cebuan → Cebuano
- **Sister languages:** Other Visayan languages — Hiligaynon (Ilonggo), Waray, Aklanon, Kinaray-a, etc. Mutual intelligibility within the Visayan group varies. Cebuano and Hiligaynon are partially mutually intelligible with effort; Cebuano and Waray less so.
- **Historical significance:** Cebu was the first Spanish settlement in the Philippines (1565); Magellan landed there in 1521 (the same expedition where he was killed by Lapu-Lapu at Mactan). Cebuano has its own significant literary tradition predating modern Tagalog/Filipino literature in some respects — particularly religious literature (Catholic liturgical materials, Sto. Niño devotional texts). Modern Cebuano literature (the Bag-ong Suga, the Bag-ong Kusog generation) is substantial.

## 1.2 The Seven Dimensions Applied to Cebuano

### Phonology — *Close to English; very similar to Filipino*

Cebuano phonology is closely parallel to Filipino — very accessible for English speakers.

**Vowel system:** 5 vowels in modern Cebuano (*a, e, i, o, u*), but historically and in conservative speech only 3 (*a, i, u*) — with *e* and *o* introduced through Spanish loanwords. Many older Cebuano words use *i* and *u* where the corresponding Tagalog word has *e* or *o*:

- Cebuano *libog* (worry) vs. Tagalog *libog* — both exist but with different shades
- Cebuano *suga* (light) vs. Tagalog *ilaw* (different word entirely)
- Cebuano speakers may pronounce loanword "telephone" closer to "tilipuno"
- The Cebuano speech of older speakers often shows more conservative i/u rather than e/o

**Consonants:** Same inventory as Filipino with very minor differences:
- The glottal stop (/ʔ/) — phonemic, often unwritten in casual text, pronounced consistently
- The /ŋ/ phoneme (written *ng*) — can appear at word start (*ngano* "why", *ngipon* "tooth")
- Familiar consonants from English; Spanish loanwords retain Spanish-influenced sounds
- The Cebuano R — alveolar tap /ɾ/, like Spanish single R

**Stress and accent:** Like Filipino, word stress is phonemic. Stress can change meaning: *bata* (child) vs. *batá* (young). Stress marked in dictionaries with acute accents but rarely in everyday text.

**Spelling-pronunciation correspondence:** Highly phonemic — once you know the basics, you can read aloud nearly any Cebuano word. Among the most regular writing systems in the curriculum.

**Implication:** Pronunciation focus light in early weeks — comparable to Filipino. The glottal stop (Week 1), word-initial /ŋ/ (Week 1-2), and stress patterns get attention. Note the i/u vs. e/o tendency for older vocabulary as a learner aid.

### Writing System — *Latin alphabet; minimal learning load*

Modern Cebuano uses the same 28-letter alphabet as Filipino: 26 Latin letters plus *ñ* (Spanish loanwords) and *ng* (treated as a single letter traditionally).

**Historical context:**
- **Baybayin variants** — pre-colonial Cebuano was written in indigenous abugida scripts (related to Tagalog Baybayin but with regional variants in the Visayas)
- **Spanish-era Latin orthography** (1565-1898) — established Latin alphabet; Cebu was actually the first place where Latin-script Cebuano was used (Doctrina Christiana en lengua española y bisaya, 1593, was one of the earliest Philippine printed books, alongside its Tagalog counterpart)
- **Modern standardization** — Cebuano spelling has been more variable historically than Tagalog; modern preferences favor phonemic spelling with some Spanish-loanword retention

**Spelling conventions:**
- Spanish loanwords often retain Spanish-influenced spelling
- English loanwords sometimes Cebuanized (*kompyuter*), often kept in English form
- The "I" letter often appears where Tagalog has "E" in cognate words
- Some Cebuano speakers and publications prefer more "purist" spellings using only the older 20-letter abakada (a, b, k, d, e, g, h, i, l, m, n, ng, o, p, r, s, t, u, w, y)

**Implication:** No separate script work needed. Cebuano spelling variations between purist and modern forms noted at higher levels.

### Morphology — *Agglutinative with focus/voice system; structurally parallel to Filipino with key differences*

Cebuano morphology shares the **Austronesian voice/focus system** with Filipino/Tagalog — verbs marked for which argument is "in focus," with case-like markers on other arguments. But the **specific affixes and markers differ**, requiring distinct study.

**The Cebuano voice/focus system:**

Cebuano has the same four/five focus types as Tagalog but with different markers:

- **Actor focus (AF)** — the doer is in focus
  - **Mu-** prefix (very common, often used for future/contemplated): *mukaon* (will eat / eats); *muanhi* (will come)
  - **Mi-** prefix (often used for completed/past): *mikaon* (ate); *mianhi* (came)
  - **Mag-** prefix (often used for ongoing/habitual): *magkaon* (will eat / is eating); *magtuon* (study)
  - **Mo-** is sometimes used; -um- is rare in Cebuano (a major difference from Tagalog)
- **Object focus (OF)** — the patient/object is in focus
  - **-on** suffix (Cebuano's distinctive object-focus marker; Tagalog uses *-in*): *kan-on* (will be eaten); *tan-awon* (will be looked at)
  - **gi-** prefix (for completed object focus): *gikaon* (was eaten); *gitan-aw* (was looked at)
- **Locative focus (LF)** — the location is in focus
  - **-an** suffix (same as Tagalog): *kan-an* (place of eating, dining table); *tan-awan* (place to be seen, viewpoint)
- **Benefactive focus (BF)** — the beneficiary is in focus
  - **i-** prefix (same as Tagalog): *ipangaon* (give for someone to eat); *itan-aw* (show to someone)
- **Instrumental focus (IF)** — the instrument is in focus (rarer)

Aspect marking interacts with focus. The same root verb appears in multiple forms depending on focus type AND aspect (completed, ongoing, contemplated).

**The Cebuano marker system (ang/ug/sa — NOT ang/ng/sa):**

| Marker | Function | Example |
|---|---|---|
| ang | Marker for focused noun (definite/topical) | *ang libro* (the book) |
| **ug** | Marker for non-focused noun (genitive-like; equivalent to Tagalog *ng*) | *ug libro* (of/a book) |
| sa | Marker for location, direction, indirect object | *sa balay* (at/to the house) |

This *ang/ug/sa* (not *ang/ng/sa*) is the most immediately visible Cebuano-Tagalog grammatical difference. Cebuano *ug* is sometimes written *og* in informal text.

For proper nouns and specific people:
- **Si** (focused proper name): *Si Maria* "Maria [as topic]"
- **Ni** (non-focused proper name): *ni Maria* "of/by Maria"
- **Kang** (locative proper name): *kang Maria* "to/at Maria"

For plural proper nouns or groups:
- **Sila** + name: *Sila Maria* "Maria and others"

**The Cebuano pronoun system — distinctive inclusive/exclusive "we":**

This is one of the most important Cebuano-Tagalog differences. Cebuano maintains the **inclusive/exclusive distinction in first-person plural** that Tagalog has largely lost:

| Pronoun | Meaning | Tagalog equivalent |
|---|---|---|
| ako / ko | I (focused / non-focused) | ako / ko |
| ikaw / ka | you singular (focused / non-focused) | ikaw / ka |
| siya / niya | he, she (focused / non-focused) | siya / niya |
| **kita** | **we (inclusive — you and I)** | tayo |
| **kami** | **we (exclusive — us but not you)** | kami |
| **kamo / mo** | you plural | kayo / ninyo |
| sila / nila | they (focused / non-focused) | sila / nila |

The *kita/kami* distinction is widespread across Austronesian languages — Tagalog actually used to have it but largely merged the categories in standard usage. In Cebuano, the distinction is alive and required.

**Tense/aspect intertwined with focus:**

Like Tagalog, Cebuano verb forms encode focus AND aspect:

- *kaon* (root: eat)
- Actor focus + contemplated: *mukaon*
- Actor focus + ongoing: *nagakaon* or *nikaon* (regional variation)
- Actor focus + completed: *mikaon*
- Object focus + contemplated: *kan-on*
- Object focus + ongoing: *gikaon* or *ginakaon*
- Object focus + completed: *gikaon*
- Etc.

**Adjectives:** Use the **ma-** prefix on roots (same as Tagalog): *maayo* (good), *matahum* (beautiful — Cebuano word, different from Tagalog *maganda*), *dako* (big — without ma-, an existing root), *gamay* (small).

**Possession:** Different from Tagalog:
- *Akong libro* (my book — *akong* combines ako + linker)
- *Imong libro* (your book — *imong* combines imo + linker)
- *Iyang libro* (his/her book — *iyang* combines iya + linker)
- *Among libro* (our book — exclusive)
- *Atong libro* (our book — inclusive)
- *Inyong libro* (your-plural book)
- *Ilang libro* (their book)

These possessive forms can appear before or after the noun.

**Implication:** Focus/voice system is the central A1-B1 task, like Filipino but with Cebuano's specific affixes. The kita/kami distinction taught explicitly from Week 3. The ang/ug/sa marker system from Week 5 with explicit contrast with Tagalog ang/ng/sa if learner has Tagalog background.

### Word Order — *Predicate-initial (VSO/VOS); flexible*

Cebuano is **predicate-initial** like Filipino — verb (or other predicate) first, followed by other elements. Order somewhat flexible because markers handle role identification.

- *Mukaon ang bata ug saging.* "The child will eat a banana." (V - S - O with markers)
- *Maayo ang adlaw.* "The day is good." (Predicate-Subject with no copula)

Same general word order patterns as Filipino — no major restructuring beyond what Filipino learners encounter.

**Implication:** Predicate-initial word order from Week 5. Modifier placement (mostly after noun) Week 11.

### Register — *No po/opo; different politeness system*

This is one of Cebuano's most notable differences from Filipino: **Cebuano does not use po/opo politeness particles**. This is a key cultural-linguistic feature often misunderstood.

**What Cebuano does instead:**

- **Address terms** carry significant politeness weight:
  - *Manong* (older man, like older brother)
  - *Manang* (older woman, like older sister)
  - *Lolo* / *Lola* (grandfather / grandmother — used widely for elderly)
  - *Tatay* / *Nanay* (father / mother — also used for elderly)
  - *Tito* / *Tita* (uncle / aunt — also used widely for adults)
  - *Bay* / *Dong* (friend / young man — casual)
  - *Day* (young woman — casual)
  - *Sir* / *Ma'am* (English borrowings, very widely used in modern Cebuano)
- **Tone and deference** in speech — slowing down, choosing softer words, respectful posture
- **The choice of pronoun** can convey respect (using full *ako* vs. clitic *ko*; using *ikaw* vs. *ka*)
- **Plural for respect** — using *kamo* (you plural) for a single person to show respect, similar to French *vous* — though less consistently than European languages
- **Indirect speech** in sensitive contexts (similar to Filipino *hiya*-based indirectness)

**Common misconception:** Tagalog speakers sometimes perceive Cebuano speakers as "less polite" because of the absence of po/opo. This is incorrect — Cebuano politeness is real and elaborate, just expressed through different mechanisms.

**Other register features:**

- **Bisalog / Bislish** — code-switching with Tagalog (Filipino) and English. In Mindanao and urban Cebu, speakers often mix Cebuano, English, and sometimes Tagalog naturally. This is normal modern speech.
- **Spoken vs. written register** — formal written Cebuano uses more Spanish-derived vocabulary and more conservative grammar; spoken casual Cebuano uses more English borrowing and code-switching
- **Religious register** — Catholic vocabulary (especially Sto. Niño devotional language) pervades casual speech
- **The English advantage** — most Cebuano speakers in urban areas speak English, often preferring English over Tagalog/Filipino as their bridge language (a point of cultural-political assertion vs. Tagalog dominance)

**Implication:** Cebuano politeness system taught Week 2 with explicit contrast to Tagalog po/opo. Address terms Week 15. Code-switching (Bisalog/Bislish) presented as legitimate modern Cebuano from B1.

### Cultural-Pragmatic Distance — *Distinct Visayan identity within Philippine context*

Cebuano cultural patterns overlap with broader Filipino culture (Catholic majority, family centrality, hospitality, hiya/utang na loob concepts, OFW phenomenon) but with distinctive Visayan features:

- **Strong Bisaya/Visayan identity** — many Cebuano speakers identify as Bisaya first, Filipino second. Real cultural pride in being "Bisdak" (Bisayang Dako — "true Bisaya"). Some resistance to Manila-centric cultural dominance.
- **Cebu City as cultural center** — "Queen City of the South"; major historical and contemporary significance; "the first Spanish city in Asia"
- **Sto. Niño devotion** — the Child Jesus image given by Magellan in 1521 is centrally important to Cebuano Catholic culture; Sinulog festival (January, Cebu) is one of the Philippines' largest celebrations
- **Magellan and Lapu-Lapu** — Magellan landed in Cebu in 1521 (where he became friends with Rajah Humabon); was killed by Lapu-Lapu at Mactan; both figures central to Cebuano historical identity
- **Bohol culture** — distinctive within the Cebuano-speaking world: Chocolate Hills, tarsiers, distinctive Boholano dialect, separate identity
- **Mindanao Cebuano speakers** — Cebuano spread to Mindanao with internal migration; Davao, Cagayan de Oro, and other Mindanao cities have large Cebuano-speaking populations with their own cultural mix (Mindanao Cebuano often blends with Hiligaynon, Tagalog, Maguindanao, and other influences)
- **Cebuano humor and entertainment** — distinct comedy traditions; Vice Ganda, Boy Abunda are Bisaya celebrities; Bisaya-language films and TV (especially from networks based in Cebu); contemporary Cebuano music (Bisrock, Bisaya pop)
- **Food** — Cebu lechon (considered by many the best), puso (hanging rice), ngohiong (Chinese-influenced), Bohol kalamay, Visayan seafood traditions
- **Bisaya hospitality and warmth** — generally considered warmer and more relaxed than Manila standards; "puro paspas" (always fast/rushed) is a Manila stereotype Bisaya reject
- **Religious context** — Catholic majority with strong devotional traditions (Sto. Niño, Black Nazarene veneration shared); growing Protestant/Evangelical presence; some Cebuano speakers in Mindanao are Muslim
- **Migration history** — Cebuanos have migrated widely within the Philippines (especially to Mindanao) and internationally; significant diaspora cultural maintenance
- **Sensitive topics** — Tagalog/Filipino dominance and language politics, Mindanao conflict and history, contemporary politics, social inequality, OFW exploitation — handled honestly

**Implication:** High cultural-note density throughout, with explicit attention to Visayan distinctiveness. Sinulog and Sto. Niño as Cebuano-specific cultural touchstones taught at A2-B1. Bohol and Mindanao Cebuano cultural contexts featured. The Manila-Cebu cultural distinction acknowledged. Modern Cebuano dynamism (Cebu City as tech hub, contemporary arts, BPO industry) featured alongside heritage.

### Resource Availability — *Smaller than Filipino but growing*

Cebuano has more limited resources than Filipino but the ecosystem is growing:

- **Free YouTube content** — Bisaya Mo (Beginner Bisaya), Learn Cebuano, Cebuano Lessons; smaller but growing channels
- **Textbooks** — *Beginning Cebuano* (Bunye & Yap) — classic two-volume Peace Corps text; *Cebuano-Visayan Dictionary* (Wolff) — the academic reference; *Conversational Cebuano* materials from Peace Corps
- **Apps** — Drops has Cebuano; Memrise has some courses; Mango Languages has Cebuano; Duolingo does NOT have Cebuano (notable gap, like Filipino)
- **Dictionaries** — Bisaya.com online dictionary; Glosbe Cebuano; bilingual Cebuano-English dictionaries
- **Native media** — Bisaya newspapers (mostly Cebu-based: Sun.Star Cebu in Cebuano sections, Banat News); ABS-CBN Cebuano (when operating); GMA Cebuano; YouTube content; Bisaya cinema; OPM songs in Cebuano (Bisrock especially)
- **Tutoring** — iTalki has Cebuano tutors (most based in Cebu); rates very favorable ($5-15/hr); fewer than Filipino tutors but available
- **Cebuano-speaking partners** — many Cebuano speakers want to practice English; mutual exchange possible
- **In-country options** — limited formal programs; University of San Carlos (Cebu) and other Cebu universities have some Cebuano-as-foreign-language programs; SIT Study Abroad has had Philippines programs; Peace Corps placement in Cebuano-speaking areas
- **Cebuano Wikipedia** — famously large (~6 million articles, most bot-generated from English articles); useful as receptive material but not great pedagogy
- **The English advantage** — most Cebuano speakers in urban areas speak fluent English; this helps learners access explanations but can hurt fluency development (as with Filipino)

**Implication:** Specific high-quality recommendations available but smaller pool than Filipino. iTalki tutoring particularly important given limited courseware. Peace Corps materials freely available are an unusually high-quality free resource. The Bunye & Yap *Beginning Cebuano* text remains the foundational learner textbook.

---

# PART 2 — VARIETY DECISION

## 2.1 The Decision

**Standard Cebuano (Cebu City variety)** as the productive base. Receptive exposure to **Boholano**, **Mindanao Cebuano** (Davao Cebuano especially), and **Negros Cebuano** at intermediate-to-advanced levels.

## 2.2 Rationale

- **Cebu City Cebuano is the prestige variety** — Cebu City is the cultural-economic center of the Cebuano-speaking world; major media originate from Cebu; Cebu City Cebuano is the variety most often taught in formal contexts
- **Most widely understood across the Cebuano-speaking world** — Cebu City Cebuano is mostly intelligible to Boholano, Mindanao Cebuano, and Negros Cebuano speakers; local features add nuance but don't prevent communication
- **Best resource availability** — most learning materials use Cebu City Cebuano
- **Manila-Cebu cultural axis** — Cebu City is the "second city" of the Philippines and the natural Cebuano-speaking equivalent of Manila Tagalog

## 2.3 Variety-Specific Considerations

**Cebu City Cebuano** — the standard; what most resources teach; what learners should primarily study.

**Boholano (Bol-anon)** — Bohol's Cebuano dialect has distinctive features including the pronunciation of "j" or "y" where standard Cebuano has "y," and some unique vocabulary. Bohol cultural identity is strong; learners going to Bohol benefit from awareness of Boholano features but can usually function in standard Cebuano.

**Mindanao Cebuano** — Cebuano spread to Mindanao with internal migration starting in the 19th-20th centuries. Mindanao Cebuano often shows influences from other languages (Hiligaynon, Tagalog, Maguindanao, Maranao, even Tausug in some areas). Davao Cebuano has specific Manila/Tagalog influences and English code-switching patterns.

**Negros Cebuano** — Eastern Negros (Negros Oriental) speaks Cebuano; Western Negros speaks Hiligaynon. The Cebuano of Negros has some distinctive features but is mostly standard.

**Leyte Cebuano** — Western Leyte speaks Cebuano (eastern Leyte speaks Waray). Leyte Cebuano has some distinctive features but is mostly standard.

**Cagayan de Oro Cebuano** — Mindanao Cebuano with northern Mindanao features.

**Surigaonon and other regional varieties** — sometimes classified as separate languages, sometimes as Cebuano dialects; complex classification.

## 2.4 What This Curriculum Excludes

- **Other Visayan languages** (Hiligaynon, Waray, Aklanon, Kinaray-a, etc.) — sister languages, not Cebuano dialects; would warrant separate curriculum references
- **Other Philippine languages** (Tagalog/Filipino, Ilocano, Bikol, Kapampangan, Pangasinan, Maguindanao, Maranao, Tausug, etc.) — separate languages
- **Pre-colonial Visayan scripts** — covered as cultural heritage at C2
- **Spanish in the Philippines historical varieties** — separate language
- **Chavacano** (Spanish-based creole in Zamboanga) — distinct language

---

# PART 3 — CURRICULUM ARCHITECTURE

## 3.1 At a Glance

- **Total length:** 160 weeks (~3.1 years at one lesson per week)
- **Pacing:** one lesson per week plus daily practice (40–55 min/day recommended — similar to Filipino/Hindi)
- **Total study time at recommended pace:** ~800–1,000 hours, matching FSI's Category III estimate
- **Level structure:** Six CEFR levels (A1–C2)

## 3.2 The Six Levels

| Level | Weeks | Span | CEFR Goal | Target Vocab |
|---|---|---|---|---|
| A1 — Foundations | 1–20 | 20 weeks | A1 | ~700 words |
| A2 — Elementary | 21–45 | 25 weeks | A2 | ~1,700 words |
| B1 — Intermediate | 46–85 | 40 weeks | B1 | ~3,500 words |
| B2 — Upper-Intermediate | 86–115 | 30 weeks | B2 | ~5,500 words |
| C1 — Advanced | 116–140 | 25 weeks | C1 | ~7,500 words |
| C2 — Mastery | 141–160 | 20 weeks | C2 | 10,000+ words |

## 3.3 Pacing Philosophy

- **A1 (Weeks 1–20):** Same pacing rationale as Filipino. **The focus/voice system gets systematic introduction** — actor focus (mu-/mi-/mag-) Week 7, object focus (-on) Week 8, locative Week 16, benefactive Week 17. *Ang/ug/sa* marker system Week 5 (with explicit contrast vs. Tagalog *ang/ng/sa*). The kita/kami distinction Week 3. End at A1 readiness.
- **A2 (Weeks 21–45):** All focus types mastered. Spanish-loanword vocabulary expansion. Reading begins shifting to native-aimed materials. Bohol and Mindanao Cebuano variety awareness.
- **B1 (Weeks 46–85):** **Longest level (40 weeks).** Focus system sustained mastery. Cultural concepts and Visayan identity. Bisalog/Bislish code-switching as legitimate. Cebuano literature introduction.
- **B2 (Weeks 86–115):** Literary register; Cebuano news media; Bisrock music; classical and contemporary Cebuano literature.
- **C1 (Weeks 116–140):** Grammar lightens. Specialized fields, Cebuano literature, other Visayan languages awareness.
- **C2 (Weeks 141–160):** Classical Cebuano (older religious literature), pan-Visayan and pan-Philippine awareness, capstone (Week 160).

---

# PART 4 — WEEK-BY-WEEK OVERVIEW

The full structured data will live in \`lib/curricula/cebuano.ts\` (to be built). Early weeks detailed; later weeks grouped.

## 4.1 Level A1 — Foundations (Weeks 1–20)

| W | Title | Core focus |
|---|---|---|
| 1 | **Pronunciation + alphabet** | The Cebuano sound system; 5 vowels (with note on older i/u tendency); glottal stop; word-initial /ŋ/; stress patterns; alphabet conventions; spelling variations |
| 2 | **Greetings + Cebuano politeness (NOT po/opo)** | *Maayong buntag/udto/hapon/gabii*; *Kumusta?*; *Salamat*; the address-term-based politeness system; explicit contrast with Tagalog po/opo for any learners with Filipino background |
| 3 | **Subject pronouns + kita/kami distinction** | All pronouns with their focused/non-focused forms; the inclusive/exclusive "we" — a defining Cebuano feature; usage contexts |
| 4 | "To be" and equational sentences | No copula in Cebuano (like Filipino); equational sentences; *Si Maria ko* "I am Maria"; basic introductions |
| 5 | **The ang/ug/sa marker system** | The Cebuano marker system; **explicit contrast with Tagalog ang/ng/sa**; si/ni/kang for proper names; the *ug* (or *og*) marker — the most visible Cebuano-Tagalog grammatical difference |
| 6 | **Introduction to focus/voice system** | Conceptual overview; why Cebuano verbs work like Filipino verbs but with different markers; preview of the system's logic |
| 7 | **Actor focus (mu-/mi-/mag-)** | The first focus type with Cebuano's specific prefixes; *mukaon, mikaon, magkaon*; aspect interaction; note that *-um-* is rare in Cebuano (a difference from Tagalog) |
| 8 | **Object focus (-on, gi-)** | The second focus type with Cebuano's specific markers; *kan-on* (will be eaten); *gikaon* (was eaten); aspect interaction |
| 9 | **Aspect marking — intertwined with focus** | Three aspects (completed, ongoing, contemplated); the Cebuano-specific aspect-focus combinations |
| 10 | Common verbs in different focuses | 20 high-frequency Cebuano verbs in their main focus forms; sustained practice; note where Cebuano verb is different from Tagalog cognate |
| 11 | **Adjectives with ma- prefix** | Same as Tagalog: *maayo* (good), *matahum* (beautiful — different from Tagalog *maganda*), *dako* (big); ma- prefix system |
| 12 | Possession in Cebuano | *Akong, imong, iyang, among, atong, inyong, ilang* + noun; inclusive vs. exclusive possessive (atong vs. among); the linker *-ng/-g* system |
| 13 | Numbers — Cebuano, Spanish, English | Cebuano numbers (usa, duha, tulo, upat, lima); Spanish-borrowed (uno, dos, tres); English; when each is used; combinations |
| 14 | Time, dates, calendar | Spanish-influenced calendar; days, months; telling time in Cebuano contexts |
| 15 | **Address terms** | *Manong, Manang, Lolo, Lola, Tatay, Nanay, Tito, Tita, Bay, Dong, Day, Sir, Ma'am*; cultural usage; family vocabulary |
| 16 | **Locative focus (-an)** | Same suffix as Tagalog; "where action happens"; *kan-an* (dining place); *tan-awan* (viewpoint); usage |
| 17 | **Benefactive focus (i-)** | Same prefix as Tagalog; "for whose benefit"; *ipalit* (buy for someone); *iandam* (prepare for someone) |
| 18 | Common irregular and frequent verbs | *Muanhi/muadto* (come/go), *muuli* (return home), *mutubag* (answer), *mangutana* (ask) |
| 19 | **Question formation** | *Unsa* (what), *Kinsa* (who), *Asa* (where), *Kanus-a* (when), *Ngano* (why), *Giunsa* (how), *Pila* (how many/much); the *ba* particle; explicit contrast with Tagalog question words |
| 20 | **A1 Review and consolidation** | Mock A1; ~700 vocab; all major focus types + aspect + ang/ug/sa system + kita/kami distinction functional |

## 4.2 Level A2 — Elementary (Weeks 21–45)

| W | Title | Core focus |
|---|---|---|
| 21 | **Aspect mastery** | Completed, ongoing, contemplated across all focus types; systematic Cebuano conjugation tables |
| 22 | The *maka-* / *maga-* verbs | Potential/ability ("can do"); *makakaon* (can eat); related forms |
| 23 | Causative verbs (*pa-*) | "Make someone do"; *pakaon* (feed); causative structures |
| 24 | Reciprocal verbs | "Each other"; *magkita* (meet each other); reciprocal patterns |
| 25 | Subordinate clauses | *Nga* (that), *kon* (if/when), *aron* (so that); embedding clauses |
| 26 | Relative clauses | *Nga* relative marker; constructing modifying clauses |
| 27 | Comparison and degree | *Mas*, *kay sa* / *kay kang* (more than); *labi* (most); degree words |
| 28 | Negation patterns | *Dili*, *wala*, *ayaw* (different negations for different contexts); position |
| 29 | Imperative and requests | Polite imperatives; *palihug* "please"; *ayaw* for prohibitions |
| 30 | Spatial vocabulary | Locative expressions; *dinhi, dira, didto*; spatial relationships |
| 31 | Workplace and professions | Jobs in Cebuano; workplace courtesy; OFW vocabulary; English code-switching in Cebu BPO industry |
| 32 | Daily routine and household | Daily activities vocabulary; household terms |
| 33 | Travel and transportation | Cebu transit (jeepney, tartanilla, multicab); travel phrases |
| 34 | Food and meals | Cebuano cuisine; *lechon* (Cebu's pride), *puso* (hanging rice), *humba*, *kinilaw*, *ngohiong*; meal etiquette |
| 35 | Health and body | Body parts; healing traditions (*albularyo*); medical visits |
| 36 | Shopping and money | Cebu markets; bargaining; peso vocabulary |
| 37 | Communication and technology | Modern Cebuano internet vocabulary; English/Tagalog code-switching |
| 38 | **Religion in Cebuano culture** | Catholic vocabulary; **Sto. Niño devotion** (central to Cebuano Catholic identity); Muslim Cebuano speakers in Mindanao; descriptive treatment |
| 39 | Cebuano-speaking geography | Cebu, Bohol, Negros Oriental, Leyte, Mindanao regions; the spread of Cebuano |
| 40 | OFW phenomenon in Cebuano context | Bisaya OFWs; cultural maintenance abroad; remittance economy |
| 41 | Festivals and celebrations | **Sinulog** (Cebu, January — one of Philippines' largest celebrations); Pintos Festival (Bohol); other Visayan festivals |
| 42 | Bisaya cultural values | Shared with broader Filipino culture (*hiya, utang na loob, bayanihan, pakikisama*) but with Visayan inflection; "Bisdak" identity |
| 43 | Cebuano pop culture intro | Bisrock (Bisaya rock music); Vice Ganda and Bisaya comedians; Cebu-based media |
| 44 | Bisalog/Bislish — code-switching | Cebuano-Tagalog-English mixing; modern urban speech in Cebu and Mindanao; not corruption |
| 45 | **A2 Review and consolidation** | Mock A2; ~1,700 vocab |

## 4.3 Level B1 — Intermediate (Weeks 46–85)

| W | Title | Core focus |
|---|---|---|
| 46–50 | Focus system mastery | All four/five focus types in all aspects; nuance in choice; discourse-level focus selection |
| 51–55 | Compound verbs and combinations | Multiple affix verbs; semantic combinations; productive patterns |
| 56–60 | Cebuano cultural deep dives | Cebu City history and modern dynamism; Bohol; Mindanao Cebuano contexts; Visayan identity |
| 61–65 | The Manila-Cebu cultural axis | Visayan-Tagalog cultural relations; language politics; "Bisdak" pride; resistance to Manila-centrism |
| 66–70 | Sto. Niño and Sinulog | Cultural-religious centrality; history (Magellan-Humabon-Sto. Niño 1521); modern celebration |
| 71–75 | Cebuano literature introduction | Lualhati Bautista (Tagalog but Bisaya themes); modern Cebuano authors; Sun.Star and other Cebu-based literary venues; Bisaya komiks tradition |
| 76–80 | Other Visayan languages awareness | Hiligaynon, Waray, Aklanon — distinct languages but related; basic recognition |
| 81–85 | **B1 Review and consolidation** | Mock B1; ~3,500 vocab |

## 4.4 Level B2 — Upper-Intermediate (Weeks 86–115)

| Weeks | Focus | Notes |
|---|---|---|
| 86–95 | Advanced grammar refinements | Subordinate focus; nominalization patterns; relative clause complexity |
| 96–100 | Cebuano literature sustained | Modern Cebuano novels and short stories; contemporary writers (Resil Mojares, Cesar Ruiz Aquino, others) |
| 101–105 | Bisrock and contemporary music | Cebuano rock tradition (Junior Kilat, Missing Filemon, Phylum); contemporary Bisaya music; lyrics analysis |
| 106–110 | News and journalism | Sun.Star Cebu; Cebu Daily News; broadcast Cebuano; political and social vocabulary |
| 111–114 | Business and professional Cebuano | Cebu BPO industry context; Cebu's role as second economic center; formal correspondence |
| 115 | **B2 Review and consolidation** | Mock B2; ~5,500 vocab |

## 4.5 Level C1 — Advanced (Weeks 116–140)

| Weeks | Focus | Notes |
|---|---|---|
| 116–125 | Cebuano literature classical | Vicente Sotto (early Cebuano novelist); Ramon Macario; Bag-ong Suga and Bag-ong Kusog generation writers; religious literature (Pasyon in Cebuano) |
| 126–130 | Other Visayan languages — receptive | Hiligaynon, Waray basic recognition; the broader Visayan linguistic family |
| 131–135 | Mindanao Cebuano deep dive | Davao, Cagayan de Oro, other Mindanao Cebuano-speaking contexts; the cultural mix with other Mindanao languages |
| 136–139 | Specialized fields | Choose 2: medical (Bisaya-English hybrid vocabulary); legal; academic; technology |
| 140 | **C1 Review and consolidation** | Mock C1; ~7,500 vocab |

## 4.6 Level C2 — Mastery (Weeks 141–160)

| Weeks | Focus | Notes |
|---|---|---|
| 141–145 | Classical Cebuano religious literature | Doctrina Christiana en lengua española y bisaya (1593) excerpts; classical Pasyon traditions; cultural-historical significance |
| 146–150 | Pre-colonial Visayan heritage | Visayan baybayin variants (cultural heritage); pre-colonial Visayan society; modern revival movements |
| 151–155 | Pan-Visayan and pan-Philippine identity | Understanding Cebuano within the broader Philippine multilingual reality; navigating regional sensitivities |
| 156–158 | Creative writing in Cebuano | Short fiction; poetry attempts; essay writing in Bisaya |
| 159 | Comprehensive review | All-skills mastery; identify final gaps |
| 160 | **Capstone project** | Choose: (a) 5,000-word essay in Cebuano, (b) translate a literary passage Cebuano↔English, (c) 30-minute podcast in Cebuano, (d) attend Sinulog festival and produce cultural documentation in Cebuano, (e) ACTFL OPI assessment if available |

---

# PART 5 — CULTURAL ROTATION STRATEGY

The Cebuano-speaking world spans the Central Visayas, parts of Western Visayas (Negros Oriental), parts of Eastern Visayas (Western Leyte), much of Mindanao, and a global diaspora. Cultural notes rotate across:

- **Cebu province** — Cebu City (Queen City of the South, BPO hub, contemporary cultural center), Mactan (Lapu-Lapu legacy, Mactan Channel, beaches), provincial Cebu (rural Cebuano life), Carcar (heritage town)
- **Bohol** — Tagbilaran (capital), Chocolate Hills, tarsiers, Boholano dialect features, distinctive cultural identity, San Juanico Bridge (connecting to Leyte)
- **Negros Oriental** — Dumaguete (university city with significant intellectual heritage), Apo Island
- **Western Leyte** — Ormoc, the Cebuano-speaking side of Leyte
- **Northern Mindanao** — Cagayan de Oro (significant Cebuano-speaking urban center), Misamis Oriental, Bukidnon
- **Davao region** — Davao City (Mindanao's largest, multilingual but Cebuano-dominant), the Duterte political legacy (politically sensitive)
- **Other Mindanao Cebuano areas** — Surigao, parts of Cotabato, Sarangani
- **Diaspora** — Filipino American communities (significant Bisaya populations distinct from Tagalog-speaking diaspora; California, Hawaii, NYC area), Hong Kong domestic helpers, Saudi nurses, UAE workers, Singapore, Japan, Australia
- **Religious traditions** — Roman Catholic majority with strong **Sto. Niño devotion** (the Magellan/Humabon Sto. Niño image is centrally important to Cebuano Catholic identity), Iglesia ni Cristo, various Protestant denominations, Iglesia Filipina Independiente (Aglipayan Church), Islam in Mindanao Cebuano-speaking areas, indigenous beliefs often syncretized
- **Historical periods** — Pre-colonial Visayas (1500s and earlier — Sri Vijayan and Majapahit influences; barangay system), **Magellan and Lapu-Lapu (1521 — Magellan's arrival and death at Mactan; Sto. Niño origin)**, Spanish colonial era (1565-1898 — Cebu was first Spanish settlement), American era (1898-1946), Japanese occupation (1942-1945), post-war, modern Cebu development, contemporary
- **Arts and literature** — Vicente Sotto (foundational Cebuano writer, "Father of Cebuano Literature"), early Bag-ong Suga and Bag-ong Kusog generation, modern Cebuano writers (Resil Mojares, Cesar Ruiz Aquino), Cebuano poetry traditions, Bisaya komiks (comics), contemporary Cebuano novels and short stories
- **Cinema** — Cebuano-language cinema growing; Bisaya scenes in mainstream Philippine cinema; documentary on Cebuano cultural topics
- **Music** — **Bisrock** (Cebuano rock — Junior Kilat, Missing Filemon, Phylum, Cattski); contemporary Bisaya pop; traditional Cebuano music; church music tradition; Sinulog beats
- **Cuisine** — **Cebu lechon** (considered by many the best in the Philippines), *puso* (hanging rice in palm-leaf packets), *humba* (slow-cooked pork), *kinilaw* (Cebuano ceviche), *ngohiong* (Chinese-influenced spring rolls), Bohol *kalamay* (sweet sticky rice), Visayan seafood traditions, *bibingka* and other rice cakes
- **Modern dynamism** — Cebu BPO industry (one of Philippines' largest), Cebu IT Park, contemporary arts scene, tourism (beach destinations, heritage), Cebuano internet culture, diaspora cultural production
- **Sensitive topics** — Language politics (Cebuano vs. Tagalog/Filipino national language debate), Mindanao Cebuano interactions with Muslim and Lumad communities, Duterte era and Davao context (politically sensitive given Cebuano-speaking origins), social inequality in Cebu, OFW exploitation, climate impacts and typhoons (Cebu and Bohol hit by Yolanda 2013) — handled honestly and neutrally

**Lesson-generator instruction:** Cultural notes should be specific (named places, people, eras, dishes, festivals, films, music). **Rotate across Cebu, Bohol, Negros Oriental, Leyte, Mindanao Cebuano regions, and diaspora**. Address Sto. Niño and Sinulog as Cebuano-specific cultural touchstones. Address Visayan identity as real and distinct from Tagalog/Filipino identity. Address modern Cebuano dynamism (Cebu BPO, IT Park, contemporary arts) alongside heritage. Religious diversity (Catholic, Muslim, indigenous) represented. Sensitive topics handled neutrally. **Don't conflate Cebuano with Filipino/Tagalog** — they are distinct languages with distinct cultural identities.

---

# PART 6 — RESOURCES FOR CEBUANO

## 6.1 Comprehensible Input

- **Bisaya Mo (Beginner Bisaya)** (YouTube) — accessible content
- **Learn Cebuano** YouTube channels — growing ecosystem
- **Cebuano Lessons** various creators
- **TalkBisaya** — online Cebuano lessons
- **Aksyon Bisaya** (when available) — Cebuano-language news broadcasts
- **Cebuano church services** (online streaming from various Cebu and Mindanao churches) — clear religious-cultural Cebuano

## 6.2 Structured Courses

- **Textbooks:**
  - **Beginning Cebuano** (Bunye & Yap) — classic two-volume Peace Corps textbook; THE foundational learner text
  - **A Dictionary of Cebuano Visayan** (Wolff) — academic dictionary, comprehensive
  - **Cebuano for Beginners** (Bunye & Yap, abridged) — shorter version
  - **Peace Corps Cebuano materials** — freely available online; high quality functional approach
  - **Conversational Cebuano** materials from various sources
- **Free online:**
  - **Peace Corps Tagalog and Cebuano materials** (free)
  - **Bisaya.com** — online dictionary and learner resources
  - **Cebuano Wikipedia** (huge but bot-generated — useful for receptive vocabulary, not pedagogy)
  - **University of San Carlos Cebuano resources** (Cebu)

## 6.3 Tutoring

- **iTalki** — Cebuano tutors available (mostly Cebu-based); rates very favorable ($5-15/hr); strong recommendation given limited courseware
- **Preply** — has Cebuano tutors
- **HelloTalk, Tandem** — Cebuano speakers wanting to practice English; mutual exchange
- **University of Hawaii Visayan/Cebuano program** — strong academic Cebuano
- **University of San Carlos** (Cebu) — has Cebuano-as-foreign-language programs
- **SIT Study Abroad** (when offering Philippines programs)
- **Peace Corps Philippines** — placement in Cebuano-speaking areas (multi-year commitment)

## 6.4 Reading Practice by Level

- **A1-A2:** Children's books in Cebuano (limited availability — *Si Pilandok* in Bisaya version); Bunye & Yap textbook practice texts
- **B1:** Sun.Star Cebu Bisaya columns; church bulletins in Cebuano; short stories in Bisaya komiks
- **B2:** Modern Cebuano short stories; contemporary Cebuano novels; Cesar Ruiz Aquino, Resil Mojares
- **C1+:** Vicente Sotto's foundational novels; Cebuano poetry collections; contemporary Cebuano literary anthologies
- **C2:** Classical Cebuano religious texts — *Doctrina Christiana en lengua española y bisaya* (1593); classical *Pasyon* traditions; pre-modern Cebuano texts

## 6.5 News and Media

- **Sun.Star Cebu** — major Cebu newspaper (English-language but with Cebuano sections and Cebu content); online presence
- **Cebu Daily News** — Cebu-focused journalism
- **The Freeman** — Cebu-based newspaper
- **Banat News** — Cebuano-language tabloid
- **DyAB, dyRC, dyBU** — Cebu radio stations (much in Cebuano)
- **ABS-CBN Cebuano** (when operating), **GMA Cebuano** — TV news
- **TV Patrol Central Visayas** — Cebuano news

## 6.6 Film and TV by Level

- **A2:** Cebuano children's content (limited); Cebu-based TV news (slower, formal Cebuano)
- **B1:** Cebuano religious programming; Cebu-based talk shows; Vice Ganda content (Cebuano segments)
- **B2:** Cebuano-language films (when produced); Cebuano scenes in mainstream Philippine cinema; documentaries on Cebu/Bohol
- **C1+:** Full native content unrestricted; classic Visayan cinema (when available); documentary films

## 6.7 Music for Listening Practice

- **Bisrock (Cebuano rock)** — Junior Kilat, Missing Filemon, Phylum, Cattski; contemporary Cebuano rock and indie; clear lyrics, vibrant cultural-linguistic learning
- **Bisaya pop and contemporary** — Kuh Ledesma (some Bisaya songs), Karylle, Sarah Geronimo Cebuano duets
- **Religious music** — Sto. Niño hymns; Sinulog music (drumbeat-driven); Catholic devotional music in Cebuano
- **Traditional Cebuano music** — kundiman in Cebuano; folk traditions; Visayan classical music
- **Sinulog music** — annual festival generates new music; cultural-linguistic landmark

## 6.8 Pronunciation Tools

- **Forvo** — native pronunciations (less Cebuano coverage than major languages but growing)
- **YouTube channels for pronunciation:** Bisaya teachers' channels
- **Shadowing:** any Cebuano podcast or news broadcast; repeat each sentence aloud
- **Reading aloud:** Cebuano is highly phonemic; reading aloud daily develops pronunciation

## 6.9 Apps and Tools

- **Anki** — essential for SRS; shared Cebuano decks available (smaller selection than Filipino)
- **Drops** — has Cebuano (notable since Duolingo does not)
- **Memrise** — some Cebuano courses
- **Mango Languages** — Cebuano course available
- **HelloTalk, Tandem** — Cebuano speakers available
- **Bisaya.com** — online dictionary
- **Note: Duolingo does NOT have Cebuano** (a notable gap, like Filipino)

---

# PART 7 — DAILY PRACTICE FRAMEWORK (CEBUANO-FLAVORED)

| Activity | Time | Frequency | Cebuano-specific notes |
|---|---|---|---|
| Vocab SRS (Anki) | 15–20 min | Daily | Cards from each lesson; include focus type with verbs; note Tagalog cognate differences when relevant |
| **Focus/voice system drills** | 5–10 min | Daily in A1-B1 | Conjugating roots across focus types and aspects; the central foundation |
| **Ang/ug/sa marker drills** | 5 min | Daily in A1 | Marker placement practice; explicit contrast with Tagalog ang/ng/sa if applicable |
| Comprehensible input | 20–25 min | Daily | Bisaya YouTube content; Cebuano podcasts; Bisrock music; Sun.Star online at intermediate |
| Active output (journaling) | 10 min | Daily | Write 3–5 sentences daily in Cebuano |
| Conversation with native | 30 min | 1–2× per week from Week 5 | iTalki Cebuano tutor (Cebu-based, very affordable); HelloTalk; **resist English/Tagalog fallback** |
| Reading at level | 15 min | 4× per week | Bunye & Yap practice texts early; Sun.Star at B1; Cebuano literature at C1 |
| Listening practice | Anytime | Daily | Bisrock music; Cebu radio; Cebuano podcasts |
| Pronunciation drill | 5 min | 3× per week | Glottal stop production; word-initial /ŋ/; stress accuracy |

**Cebuano-specific habit recommendations:**

- Switch phone language to Cebuano around Week 10 (Cebuano phone language support is limited; consider Filipino as alternative or stay in English)
- **Resist the English-fallback temptation** — most Cebuano speakers in urban areas speak fluent English and may switch when you struggle; staying in Cebuano is essential
- **Don't substitute Tagalog when stuck** — if you have Filipino/Tagalog background, the temptation to switch to Tagalog is real; Cebuano speakers may humor you but won't switch their own speech; staying in Cebuano builds the language
- Listen to Bisrock daily — Junior Kilat, Missing Filemon, Phylum are exceptional cultural-linguistic learning
- Follow Bisaya Twitter/X or Instagram accounts in Cebuano from B1+
- Use Cebuano kin terms in real conversation from Week 2+ — cultural-linguistic habit-building (Manong/Manang/Lolo/Lola)
- **If visiting the Philippines**: visit Cebu, Bohol, and a Mindanao Cebuano area for real exposure variety

**Total daily commitment: 40–55 minutes minimum.** Same as Filipino. Reaching B2 typically takes 3-4 years of consistent effort.

---

# PART 8 — ASSESSMENT MILESTONES

Cebuano has even more limited formal assessment infrastructure than Filipino. Options:

## 8.1 CEFR-Aligned Self-Assessment

- **University programs** with Cebuano (University of Hawaii, University of San Carlos in Cebu, some others) — institutional placement and proficiency tests
- **ACTFL OPI** — Oral Proficiency Interview may be available for Cebuano (smaller pool of assessors than Filipino)
- **ILR levels** — US government uses ILR scale; some military and intelligence programs include Cebuano

| Level | Curriculum week | Format |
|---|---|---|
| CEFR A1 | End of Week 20 | Self-assessment; institutional if available |
| CEFR A2 | End of Week 45 | Self-assessment; ACTFL Novice if available |
| CEFR B1 | End of Week 85 | ACTFL Intermediate; institutional |
| CEFR B2 | End of Week 115 | ACTFL Advanced |
| CEFR C1 | End of Week 140 | ACTFL Superior |
| CEFR C2 | End of Week 160 | ACTFL Distinguished; specialized university certification |

## 8.2 ACTFL OPI

Particularly useful for Cebuano given the very limited formal exam infrastructure. Confirm assessor availability when scheduling.

## 8.3 University Programs

- **University of Hawaii** — has Visayan/Cebuano courses with institutional assessment
- **University of San Carlos** (Cebu) — strong Cebuano programs
- **University of the Philippines Cebu** — Cebuano-medium programs
- **US universities offering Cebuano** — limited but growing (some California universities; UC Berkeley historically)

## 8.4 Self-Assessment

The lesson template's self-assessment checklist applies. For Cebuano, additionally rate weekly:

- **Focus/voice system fluency** — can you choose the right focus type automatically?
- **Ang/ug/sa marker accuracy** — what percentage of nouns produced with correct markers?
- **Kita/kami distinction** — do you naturally use inclusive vs. exclusive "we" correctly?
- **Cebuano-vs-Tagalog differentiation** — if you have Tagalog background, are you avoiding Tagalog interference?
- **Listening at native speed** — what percentage of Cebuano news or Bisrock songs can you follow?

---

# PART 9 — COMMON CHALLENGES FOR ENGLISH SPEAKERS (AND TAGALOG-BACKGROUND LEARNERS)

## 9.1 The Voice/Focus System

Same conceptual challenge as Filipino — the central A1-B1 task. Five (or more) focus types with their own affixes, interacting with aspect and the ang/ug/sa marker system. Curriculum response: systematic introduction Weeks 6-9, 16-17; sustained practice through B1.

## 9.2 The Ang/Ug/Sa Marker System

Different from Filipino's ang/ng/sa. Learners must internalize Cebuano-specific markers. For Tagalog-background learners, this requires unlearning Filipino markers in Cebuano contexts. Curriculum response: explicit teaching Week 5 with contrast.

## 9.3 The Kita/Kami Distinction

The inclusive/exclusive "we" — distinct from standard Tagalog's collapsed system. Genuinely different. Curriculum response: explicit teaching Week 3 with reinforcement.

## 9.4 Different Verb Affixes from Tagalog

Mu-/mi- prefixes prominent in Cebuano; -um- rare. -on object focus suffix (vs. Tagalog -in). For Tagalog-background learners, this requires conscious shifting. Curriculum response: explicit contrast throughout.

## 9.5 Absence of Po/Opo

Cebuano politeness expressed differently. Tagalog-background learners may overuse po/opo; Cebuano speakers consider this slightly awkward. Curriculum response: explicit cultural-grammatical teaching Week 2.

## 9.6 Different Basic Vocabulary

Many basic words differ from Tagalog: *asa* vs. *saan* (where), *unsa* vs. *ano* (what), *kinsa* vs. *sino* (who), *kanus-a* vs. *kailan* (when), *maayo* vs. *mabuti* (good), *matahum* vs. *maganda* (beautiful). Tagalog-background learners often substitute incorrectly. Curriculum response: explicit vocabulary contrasts throughout.

## 9.7 The Glottal Stop

Phonemic but often unwritten; same challenge as Filipino. Curriculum response: Week 1 phonology work.

## 9.8 Word-Initial /ŋ/

The *ng* sound at word start; same challenge as Filipino. Curriculum response: Week 1; minimal pairs.

## 9.9 The "I/E" and "O/U" Vowel Variations

Cebuano tends toward older 3-vowel system; many words use i/u where Tagalog has e/o. Curriculum response: noted as feature; helpful for recognizing related vocabulary.

## 9.10 Aspect Intertwined with Focus

Each verb has multiple forms based on focus + aspect; same challenge as Filipino. Curriculum response: introduced Week 9; sustained practice.

## 9.11 Indirect Communication Style

Shared with broader Filipino communication patterns. Curriculum response: cultural notes throughout.

## 9.12 The Bisalog/Bislish Reality

Modern urban Cebuano includes heavy code-switching. Learners may feel guilty about not using "pure" Cebuano. Curriculum response: introduced explicitly in B1; legitimacy framed clearly.

## 9.13 English (and Tagalog) Fallback Temptation

Most Cebuano speakers in urban areas speak English fluently. Some speak Tagalog (though often resentfully). They may switch to English or Tagalog when you struggle. Resisting this is essential. Curriculum response: explicit habit-formation guidance.

## 9.14 The Plateau at B1→B2

Standard plateau; Cebuano has the additional challenge of mastering Cebuano literary and journalistic register vocabulary at this level (resources sparser than Filipino). Curriculum response: B1 gets 40 weeks; thematic chunking.

## 9.15 Cultural-Pragmatic Adjustments

Visayan cultural identity; Sto. Niño centrality; Manila-Cebu cultural relations; Bisaya pride. Curriculum response: cultural notes throughout; explicit teaching at B1.

## 9.16 Resource Quality and Quantity

Significantly less than Filipino: no Duolingo, limited textbooks, smaller tutor pool. Bunye & Yap remains the foundational text decades after publication. Curriculum response: specific high-quality recommendations; iTalki tutoring emphasized; Peace Corps materials highlighted as free quality resource.

---

# PART 10 — CEBUANO-SPECIFIC NOTES FOR LESSON GENERATION

Notes for the AI generating each weekly Cebuano lesson, in addition to the universal pedagogical principles.

## 10.1 Lesson Template Adjustments for Cebuano

The universal 12-section template applies with these adjustments:

- **Add Section 13: Focus System Focus** (Weeks 6–30) — explicit work on focus type identification, verb affix conjugation (Cebuano-specific), ang/ug/sa marker selection. Reduce after Week 30 as system becomes integrated.
- **Add Section 14: Cebuano-vs-Tagalog Contrast** (optional throughout) — for learners with Filipino background, brief notes on Cebuano-Tagalog differences in the lesson's content. Can be skipped for pure beginners with no Filipino background.
- **Section 2 (Key Vocabulary)** — for verbs, **always show the focus types in which the verb appears most commonly** with Cebuano-specific affixes; for nouns, mark Spanish/English/native Cebuano etymology when relevant; for Tagalog-background learners, note Tagalog cognate when different.
- **Section 3 (Grammar Focus)** — pattern + example format. Include Cebuano grammatical terminology where useful.
- **Section 5 (Listening Exercise)** — A1: Bisaya YouTube beginner content; A2: Cebuano standard speech at moderate pace; B1+: Cebu radio, news; B2+: Bisrock and full native content.
- **Section 8 (Speaking Exercise)** — include pronunciation drills in A1 (glottal stop, ng-, stress); throughout, include focus-type production practice; politeness practice via address terms (NOT po/opo).

## 10.2 Vocabulary Selection

- Frequency-weighted Cebuano vocabulary (from Cebuano corpora — limited but available)
- **Always show focus types with verbs** with Cebuano-specific markers (mu-, mi-, mag-, -on, gi-)
- Note Spanish/English/native Cebuano etymology when relevant for register
- Include both formal Cebuano AND Bisalog/Bislish where appropriate to level
- For Tagalog-background learners (optional contrast), note when Cebuano vocabulary differs significantly from Tagalog

## 10.3 Example Sentence Composition

- Write natural Cebuano that a native would produce
- Use predicate-initial (VSO/VOS) word order consistently
- Use kita/kami distinction correctly throughout
- Reflect register appropriate to the level (formal Cebuano at A1-A2; Bisalog from B1)
- Reference Cebuano cultural contexts (Cebu, Bohol, Davao, Mindanao Cebuano areas) — rotate
- Acknowledge religious diversity (Catholic majority, Muslim Cebuano speakers in Mindanao) where relevant

## 10.4 Cultural Notes

- High density throughout
- Specific places, eras, people, dishes, festivals, films, music, cultural figures
- **Rotate across Cebu, Bohol, Negros Oriental, Western Leyte, Mindanao Cebuano regions, and diaspora**
- Address Visayan identity as real and distinct from Tagalog/Filipino identity
- Sto. Niño and Sinulog as Cebuano-specific cultural touchstones
- Modern Cebu dynamism (BPO, IT Park, contemporary arts) alongside heritage
- Religious diversity presented descriptively
- Sensitive topics (language politics, Mindanao history, Duterte-era Davao, social inequality) handled neutrally and factually
- Acknowledge other Visayan and Philippine languages when relevant
- Avoid conflating Cebuano with Filipino/Tagalog

## 10.5 Listening Recommendations

- A1: Bisaya YouTube beginner channels; clear children's content (limited availability)
- A2: Cebuano podcasts; Cebu radio; Bisrock ballads with lyrics
- B1: Cebu news; Cebuano talk shows; Bisaya religious programming
- B2: Full TV Patrol Central Visayas; Bisrock full speed; Cebuano cinema
- C1+: Native podcasts; literary readings; contemporary Cebuano debates

## 10.6 Reading Passages by Level

Calibrated to level:

- **A1:** ~80–120 words; present aspect; high-frequency vocab; main focus types
- **A2:** ~150–250 words; all aspects; multiple focus types; basic Bisaya cultural vocabulary
- **B1:** ~300–500 words; complex sentences; full focus system; some Bisalog
- **B2:** ~600–800 words; literary or journalistic register; advanced grammar
- **C1:** ~1,000–1,500 words; sophisticated register; classical influences
- **C2:** ~2,000+ words; native-quality including classical religious texts

## 10.7 Grammar Explanations

- In English through B1; transitioning to Cebuano for grammar terms at B2+
- Include Cebuano grammatical terminology where appropriate
- Pattern + example + translation + explanation + common pitfall format
- For Tagalog-background learners: contrast where Cebuano differs (markers, pronouns, vocabulary, politeness system)

## 10.8 Pronunciation Section

Every lesson, especially A1-A2:

- **A1:** Specific sound focus (glottal stop; word-initial /ŋ/; stress patterns); reading aloud
- **A2:** Sentence rhythm; intonation patterns; word stress placement; the i/u tendency in older vocabulary
- **B1+:** Code-switching pronunciation (Cebuano-Tagalog-English transitions in Bisalog/Bislish)
- **B2+:** Regional accent recognition (Boholano, Mindanao Cebuano); classical text pronunciation

## 10.9 Drill Variety

- Mix at least three of: focus-type selection, verb affix conjugation, ang/ug/sa marker selection, kita/kami selection, aspect transformation, translation (both directions), Tagalog-Cebuano translation (if appropriate to learner background)
- Avoid pure multiple-choice except for nuance items
- Include focus-aspect conjugation tables in A1-A2

## 10.10 The Weekly Challenge

Examples calibrated to level:

- A1: Have a 1-minute self-introduction conversation in Cebuano with a tutor (using appropriate address terms)
- A2: Order food in Cebuano at a Cebuano restaurant or via roleplay (lechon, puso, humba)
- B1: Watch one Cebu-based news broadcast and summarize the plot in Cebuano
- B2: Watch a Bisaya film or extended scene and discuss in Cebuano
- C1: Read a Vicente Sotto excerpt and write a brief analysis
- C2: Engage in unscripted debate in Cebuano; or attempt classical Pasyon recitation; or write a literary essay

## 10.11 Cultural and Political Sensitivity

For lesson generators (AI or human):

- The curriculum is for learners interested in Cebuano-speaking communities — Cebu, Bohol, Negros Oriental, Mindanao Cebuano areas, diaspora
- Religious diversity (Catholic majority, Muslim in Mindanao, indigenous beliefs) presented descriptively
- For political topics (language politics, Mindanao history, Duterte legacy in Davao, contemporary politics): present factually and neutrally
- Acknowledge that Cebuano speakers have diverse political views
- **Do NOT conflate Cebuano with Filipino/Tagalog or treat Cebuano as a dialect** — this is the most important framing choice; Cebuano is a distinct language with distinct cultural identity
- Acknowledge other Visayan languages (Hiligaynon, Waray, Aklanon, etc.) as also distinct languages
- Note where Cebuano/Visayan perspectives may differ from Manila-centric narratives
- Avoid orientalist or exotic-Philippines framing
- Represent modern urban Cebuano life alongside traditional contexts
- Visayan pride and identity treated with respect

---

*End of document. This is the Cebuano-specific reference for the language learning project. The next deliverable (when ready for the build phase) would be the structured curriculum data (\`lib/curricula/cebuano.ts\`) with all 160 weeks as TypeScript objects matching the schema used for other languages. If other Visayan or Philippine languages are added later (Hiligaynon, Waray, etc.), they would be separate curriculum references following this same framework with language-specific adaptations.*
`;
