// Auto-generated by scripts/embed-references.ts
// Source: gallup-strengths-pedagogy.md
// Do not edit by hand. Re-run the embedding script if the source changes.

export const gallupPedagogy = `# Gallup CliftonStrengths Pedagogy for Language Learning

**Purpose.** This document maps each of the 34 Gallup CliftonStrengths themes to language-learning implications. When a learner provides their top 10 strengths, the app uses these mappings to tailor lesson tone, section emphasis, path recommendations, motivation framing, and derailer awareness.

**Important: This is original pedagogical interpretation, not a reproduction of Gallup's copyrighted descriptions.** The theme names are Gallup trademarks; the interpretations below are this framework's own analysis of how each theme manifests in adult language learning specifically. For Gallup's authoritative descriptions of each theme, learners should consult Gallup's official materials.

**How the app uses this document:**
1. Learner enters their top 10 strengths during onboarding (or skips this step — it's optional)
2. The prompt builder pulls the relevant theme mappings from this document
3. Top 5 strengths are flagged as **dominant** (heavy influence on lesson design)
4. Strengths 6-10 are flagged as **supporting** (color the lessons but don't dominate)
5. Theme combinations are noted where pedagogically significant
6. Domain distribution (Executing / Influencing / Relationship Building / Strategic Thinking) informs broader motivational framing

---

## How the Four Domains Inform Lesson Design

Before per-theme details, the four CliftonStrengths domains have systematic implications for how lessons should be designed for a learner heavy in each domain.

### Executing Dominant (top 10 has 5+ Executing themes)

These learners make things happen. They thrive on completion, structure, routine, follow-through.

- **Motivation framing:** Visible progress, completion metrics, streaks, milestones, checklists
- **Section emphasis:** Section 7 (Drill) and Section 12 (Weekly Challenge) — both have clear "done" states
- **Path leanings:** Output-First (Path II on output timing) often fits well — they want to *do* the language
- **Tone:** Practical, action-oriented, focused on what to do next
- **Derailers:** Vague goals, abstract theory without application, lessons that feel like reading philosophy

### Influencing Dominant

These learners take charge, speak up, persuade. They thrive on impact and visibility.

- **Motivation framing:** Application to real conversations, social impact, "what can you do with this," competitive comparison
- **Section emphasis:** Section 8 (Speaking) and Section 12 (Weekly Challenge) framed around social use
- **Path leanings:** Strongly Output-First — speak from day one, find people to talk with
- **Tone:** Confident, energetic, action-oriented
- **Derailers:** Long silent-period methodology, isolated study with no social application

### Relationship Building Dominant

These learners build connections. They thrive on understanding people, supporting others, deep one-on-one engagement.

- **Motivation framing:** Connection to real people who speak the language, cultural empathy, understanding the human stories behind language
- **Section emphasis:** Section 6 (Cultural Note) framed around people and stories; Section 12 (Weekly Challenge) framed around connection
- **Path leanings:** Can go either Path I or II — depends on whether they want to deeply listen first (Path I) or connect immediately (Path II)
- **Tone:** Warm, story-rich, people-centered
- **Derailers:** Lessons that feel mechanical, drill-heavy without human context, language treated as code rather than communication

### Strategic Thinking Dominant

These learners absorb and analyze information. They thrive on patterns, depth, connections between ideas.

- **Motivation framing:** Intellectual depth, pattern recognition, etymology, contrastive analysis, "why" not just "what"
- **Section emphasis:** Section 3 (Grammar Focus) gets the deep treatment; Section 6 (Cultural Note) goes historical/philosophical; Section 2 (Vocabulary) includes etymology
- **Path leanings:** Often Path I (Input-First, massive comprehensible input) and Path I on grammar (explicit study) — they want to understand the system
- **Tone:** Intellectual, depth-oriented, treats learner as peer in inquiry
- **Derailers:** Surface-level lessons, gamification pressure (streaks, leaderboards), tone that's too peppy or sales-y

---

# THE 34 THEMES

## STRATEGIC THINKING DOMAIN

### Input

**Core driver:** A need to collect, archive, accumulate — information, ideas, words, references, resources. Curious in a sustained way that adds up over time.

**Language-learning implications:** Input learners build large vocabularies naturally because they enjoy collecting words the way others collect coins. They love etymology, word origins, regional variants, register distinctions, idioms, proverbs, slang. They also enjoy accumulating learning resources — they'll save 20 articles about a grammar point and read all of them. This is a strength.

**Path leanings:** Strongly Path I (Input-First) on output timing — they thrive on accumulating massive input. Path I on grammar (explicit study) — they want the analytical framework. They'll cross-reference relentlessly (Part 8.20).

**Section emphasis:**
- Section 2 (Vocabulary): include etymology, related word families, cognates with other languages, register variations
- Section 4 (Reading): can handle dense, rich passages with lots of new material — they'll dig in
- Section 6 (Cultural Note): historical, etymological, comparative — they enjoy the breadth
- Section 10 (Cultural/Pragmatic Notes): regional variations, register distinctions, "how this word differs in Spain vs Mexico"

**Tone guidance:** Treat as a fellow collector. "Here's an interesting word with a fascinating history..." resonates more than "let's learn this useful word!"

**Derailers:** Information overload — they'll save more resources than they can absorb. The app should occasionally remind them to consolidate, not just accumulate. They may also resist "moving on" from a topic before they've gathered everything; the app's weekly structure helps here by providing natural completion.

### Intellection

**Core driver:** Deep thinking, introspection, intellectual depth. Energy comes from sustained mental engagement, not surface activity.

**Language-learning implications:** Intellection learners love to think *about* the language as much as in it. They appreciate meta-discussion of how patterns work, why certain constructions exist, the cognitive science of language acquisition. They benefit from quiet, focused study time and can be derailed by overly social or busy learning environments. They may journal extensively about their learning.

**Path leanings:** Path I on output timing — they need processing time before producing. Path I on grammar — they want the architecture explicit. They'll do their best work in solitude with rich material.

**Section emphasis:**
- Section 3 (Grammar Focus): go deeper than typical — historical evolution, theoretical underpinnings, cross-linguistic comparison
- Section 11 (Self-Assessment): they'll engage substantively with reflective prompts — give them real questions to think about, not checkboxes
- Section 6 (Cultural Note): philosophical, intellectual movements, ideas embedded in language

**Tone guidance:** Treat as intellectual peer. Avoid breezy or peppy tone. Long-form is fine; depth is fine.

**Derailers:** Overthinking, paralysis by analysis. They may want to fully understand before practicing — but language acquisition requires production attempts even before full understanding. The app should occasionally nudge action ("you've thought about this enough — try producing it").

### Learner

**Core driver:** Love of the learning process itself — not just the outcome. Energized by the journey of acquiring something new.

**Language-learning implications:** Learner-types are the framework's natural users. They enjoy the steep early curve of a new language, treasure new insights, celebrate small breakthroughs. They may have started other languages just to enjoy the beginning. The risk: they may plateau or drop a language when the learning curve flattens at B1+ (the intermediate wall).

**Path leanings:** Adaptable — works in all paths. The motivation is intrinsic.

**Section emphasis:**
- Section 1 (Lesson Overview): they'll engage with the "what you'll learn this week" framing
- Section 11 (Self-Assessment): they love tracking what they've learned
- Section 12 (Weekly Challenge): respond well to "stretch yourself" framing

**Tone guidance:** Celebrate progress and process equally. "You're not just learning Spanish — you're becoming the kind of person who learns languages well."

**Derailers:** The intermediate wall is their biggest enemy — once initial learning slows, motivation can collapse. Lessons at B1+ should explicitly name the wall (per Part 8.15 of pedagogy-foundations) and reframe progress around depth rather than novelty. Topic-driven study (Part 8.10) becomes essential.

### Ideation

**Core driver:** Fascinated by ideas, patterns, possibilities. Enjoys connecting disparate concepts and seeing things from new angles.

**Language-learning implications:** Ideation learners love seeing patterns across languages, structural similarities, unusual constructions, "what if" linguistic thought experiments. They enjoy the *system* of a language — its inner logic. They may be less drawn to rote memorization but love grammar that reveals deep structure.

**Path leanings:** Path I on grammar — they want the patterns explicit so they can play with them. Can go either way on output timing.

**Section emphasis:**
- Section 3 (Grammar Focus): emphasize pattern, system, generative rules over isolated facts
- Section 2 (Vocabulary): show how compounds work (relevant to Mandarin, German, others), morphological patterns
- Section 6 (Cultural Note): comparative — "how does X compare to similar concepts in other cultures"

**Tone guidance:** Invite play with the system. "Once you know this pattern, you can generate hundreds of sentences..."

**Derailers:** Boredom when material feels mechanical or repetitive. Drills (Section 7) may need framing as "pattern recognition" rather than "rote practice."

### Strategic

**Core driver:** Quickly spots patterns and issues others miss. Generates multiple alternative paths and picks the most effective one. (Different from Strategic Thinking the domain.)

**Language-learning implications:** Strategic learners optimize their learning path. They'll evaluate whether a particular resource is worth the time, whether to focus on speaking or reading first, whether grammar study is paying off. They're efficient. The framework's Learning Paths concept (Part 9) appeals to them — they want to choose the right path, not blindly follow defaults.

**Path leanings:** Whatever they evaluate to work best — they'll re-evaluate periodically and adjust. The app should expose path tradeoffs explicitly so they can make informed choices.

**Section emphasis:**
- Section 12 (Weekly Challenge): they'll appreciate calibration to their goals
- Section 11 (Self-Assessment): they'll genuinely use this for course-correction

**Tone guidance:** Treat as strategic partner. Show tradeoffs explicitly. "If your goal is X, focus more on Section A; if Y, focus more on Section B."

**Derailers:** Constant re-evaluation can become a form of procrastination. The app should occasionally remind them that consistent practice beats perfect path selection (Part 8.12).

### Analytical

**Core driver:** Searches for reasons and causes. Wants to understand why something works the way it does. Skeptical of unsupported claims.

**Language-learning implications:** Analytical learners want the *why* behind every rule. They'll resist "just memorize it" — they want the underlying logic. They benefit from contrastive analysis with their L1, historical explanations, linguistic theory. They may push back on intuition-based learning ("just listen to a lot of native speech") if they don't understand the mechanism.

**Path leanings:** Path I on grammar (explicit) — they need the analysis. On output timing, they may want to understand before producing, leaning Path I.

**Section emphasis:**
- Section 3 (Grammar Focus): heavy emphasis — show the analysis, the mechanism, the why
- Section 10 (Cultural/Pragmatic Notes): explain *why* a pragmatic norm exists, not just that it does

**Tone guidance:** Provide reasoning. Don't assert without explanation. "This works because..." not "this is how it is."

**Derailers:** May resist activities they can't analytically justify (like shadowing — "why does this help?"). The app can address this by explaining the cognitive science behind each technique.

### Context

**Core driver:** Understands the present by researching the past. Finds meaning in historical roots and developmental sequences.

**Language-learning implications:** Context learners love etymology, historical linguistics, the story of how a language evolved. They understand modern Spanish better when they understand its Latin roots; modern Japanese makes more sense with historical context. They benefit from "how did we get here?" framing.

**Path leanings:** Path I on grammar (explicit) — but specifically wants the historical explanation. Often patient with input-first (Path I) on output.

**Section emphasis:**
- Section 2 (Vocabulary): include etymology, historical evolution of words
- Section 3 (Grammar Focus): show how a pattern developed (e.g., "the Spanish subjunctive evolved from Latin's..." or "this Japanese honorific system reflects feudal social structure...")
- Section 6 (Cultural Note): heavy historical framing — they want to understand the present through the past

**Tone guidance:** Storytelling about how things came to be. "This expression dates back to..." resonates strongly.

**Derailers:** May feel that modern fast-changing language (slang, internet language) is shallow. The app should validate this while gently noting that current usage is also part of the historical continuum.

### Futuristic

**Core driver:** Vividly imagines the future. Inspired by visions of what could be. Plans toward long-term outcomes.

**Language-learning implications:** Futuristic learners are motivated by the vision of who they'll be once they speak this language — the conversations they'll have, the books they'll read, the places they'll experience, the work they'll do. They need this vision kept alive throughout the long journey to fluency.

**Path leanings:** Flexible — driven by the long-term vision, can sustain any path. But they need that vision regularly reinforced.

**Section emphasis:**
- Section 1 (Lesson Overview): connect each lesson to the eventual outcome ("by the time you finish A1, you'll be able to...")
- Section 12 (Weekly Challenge): frame in terms of future capabilities being unlocked
- Section 6 (Cultural Note): aspirational — "the kinds of conversations you'll be able to have"

**Tone guidance:** Visionary. "Imagine yourself a year from now, reading [author] in the original..."

**Derailers:** The present can feel tedious compared to the vision. The app should explicitly bridge today's lesson to the future ("today's grammar is one of the things that unlocks [aspirational outcome]").

---

## RELATIONSHIP BUILDING DOMAIN

### Connectedness

**Core driver:** Believes everything is linked. Finds meaning in how things connect across people, ideas, history, and experiences. Spiritual or philosophical in orientation.

**Language-learning implications:** Connectedness learners are drawn to how a language connects to its culture, history, philosophy, religion, worldview. They want to understand the spirit of a language, not just its mechanics. They're often drawn to languages with rich philosophical or spiritual traditions (Sanskrit, Hebrew, Arabic, classical Chinese, Japanese).

**Path leanings:** Flexible on output timing. On grammar, they may prefer holistic explanations over atomized rule-by-rule.

**Section emphasis:**
- Section 6 (Cultural Note): connect language to deeper meaning — worldview, philosophy, spiritual tradition
- Section 4 (Reading Passage): texts that touch on meaning and connection resonate more than transactional ones
- Section 10 (Cultural/Pragmatic Notes): show how a pragmatic norm reflects deeper cultural worldview

**Tone guidance:** Meaning-oriented. "This word reveals how speakers see the relationship between..."

**Derailers:** May feel resistance to language treated as just a tool — they need it to have meaning. Avoid framing learning as purely transactional ("you need this for business").

### Relator

**Core driver:** Enjoys close, one-on-one relationships. Finds deep satisfaction working with people they trust. Quality over quantity in connections.

**Language-learning implications:** Relator learners are best served by one-on-one tutoring or a small number of close language partners — not group classes or shallow language exchange events. Their motivation is sustained by the relationships they build through language, not by tools or apps alone.

**Path leanings:** Output-First (Path II) often works *if* there's a real relationship — they'll speak imperfectly to someone they trust. Won't enjoy speaking to strangers for practice.

**Section emphasis:**
- Section 8 (Speaking) and Section 12 (Weekly Challenge): frame around one specific person ("have this conversation with your tutor / language partner" not "find someone to practice with")
- Section 5 (Listening): real human voices, ideally familiar ones, resonate more

**Tone guidance:** Warm, personal. "Once you can have this conversation with your tutor..."

**Derailers:** Apps and impersonal practice. The app should encourage them to find one or two consistent language partners early.

### Developer

**Core driver:** Sees potential in others and loves helping people grow. Energized by witnessing improvement, especially in others.

**Language-learning implications:** Developer learners may be drawn to languages because they want to help others (immigrants in their community, learners they tutor, family members). Their motivation is partly altruistic. They may also enjoy teaching what they're learning — which, per the Feynman Technique (Part 8.21), accelerates their own learning.

**Path leanings:** Flexible. Often enjoy teaching as part of learning.

**Section emphasis:**
- Section 11 (Self-Assessment): "explain this to a friend" prompts resonate
- Section 9 (Writing) and 12 (Weekly Challenge): include teaching-others options ("explain this pattern to someone learning the language")

**Tone guidance:** "Once you understand this, you'll be able to help others who are struggling..."

**Derailers:** May feel guilty learning "selfishly." The app can frame personal learning as ultimately enabling them to help others.

### Empathy

**Core driver:** Senses others' emotions as if they were their own. Reads people deeply, often without words.

**Language-learning implications:** Empathy learners pick up subtle pragmatic and register cues quickly — when someone is upset, when a phrase is too direct, when register is wrong. They may struggle more with the analytical aspects (grammar drills) but excel at communication. They're sensitive to native-speaker reactions and may be more affected by misunderstandings or perceived judgment.

**Path leanings:** May lean Path I (Input-First) initially due to fear of getting it wrong with someone — but a supportive tutor can unlock confident Output-First quickly.

**Section emphasis:**
- Section 10 (Cultural/Pragmatic Notes): pragmatic depth is their natural domain — give them substance here
- Section 8 (Speaking): emphasize tone, register, emotional accuracy alongside accuracy

**Tone guidance:** Acknowledge the emotional difficulty of producing language imperfectly. "It's natural to feel exposed when speaking a new language..."

**Derailers:** Sensitive to criticism — even gentle feedback can land hard. The app should frame mistakes very gently (Part 8.14).

### Harmony

**Core driver:** Looks for consensus and avoids unnecessary friction. Practical, conflict-averse, prefers smooth interactions.

**Language-learning implications:** Harmony learners may be slow to speak because they don't want to risk awkwardness or misunderstanding. They want to know the "right" way before attempting. They benefit from explicit pragmatic guidance — what's polite, what's safe, what won't cause friction.

**Path leanings:** Often Path I (Input-First) — they want to understand norms before producing. Can shift to Output-First with a patient, non-judgmental partner.

**Section emphasis:**
- Section 10 (Cultural/Pragmatic Notes): pragmatic safety is high-value for them — what's polite, what to avoid
- Section 12 (Weekly Challenge): low-friction options — interactions where mistakes won't cause real awkwardness

**Tone guidance:** Reassuring. "Here are the safe phrases you can rely on..." Provides a floor of confidence before they branch out.

**Derailers:** Conflict avoidance can become avoidance of speaking entirely. Gentle but consistent encouragement to attempt is essential.

### Includer

**Core driver:** Notices who's left out and works to bring them in. Accepts others readily. Egalitarian instinct.

**Language-learning implications:** Includer learners may be drawn to languages spoken by underserved or marginalized communities — minority languages, indigenous languages, languages of immigrants in their region. They appreciate when curricula treat all varieties of a language with respect (not just the prestige variety).

**Path leanings:** Flexible.

**Section emphasis:**
- Section 6 (Cultural Note): include voices and stories from marginalized speakers, not just the dominant variety
- Section 10 (Cultural/Pragmatic Notes): note when language norms exclude certain groups and how that's changing

**Tone guidance:** Inclusive of all speakers of the language. Don't privilege one accent or region as "correct."

**Derailers:** May feel uncomfortable with materials that privilege one variety over others. Acknowledge variety explicitly.

### Individualization

**Core driver:** Intrigued by what makes each person unique. Sees individuals, not categories. Knows how to bring out the best in different kinds of people.

**Language-learning implications:** Individualization learners want their learning customized to them specifically — not the standard curriculum applied identically to everyone. They benefit from path choices, topic personalization, and the freedom to skip or emphasize sections based on their own profile. The framework's Learning Paths concept (Part 9) is built for them.

**Path leanings:** Whatever fits them specifically — they want to be treated as an individual, not a category.

**Section emphasis:**
- Section 12 (Weekly Challenge): topic-driven, customizable to their interests
- Section 11 (Self-Assessment): genuine reflection, not generic checklist

**Tone guidance:** Personalized. The framework's CliftonStrengths integration *is* the gift to them — it shows the app sees them as an individual.

**Derailers:** One-size-fits-all approaches. They'll resist generic advice that doesn't account for them.

### Positivity

**Core driver:** Contagious enthusiasm. Naturally upbeat. Energizes others. Sees the good.

**Language-learning implications:** Positivity learners bring energy to their learning and to the people they learn with. They make great language exchange partners because their enthusiasm puts others at ease. They may be more resilient to setbacks than analytical types because they naturally reframe.

**Path leanings:** Often Output-First (Path II) — they enjoy the social and emotional energy of speaking. Energized by interaction.

**Section emphasis:**
- Section 8 (Speaking) and 12 (Weekly Challenge): social, interactive framings work well
- Section 6 (Cultural Note): celebratory, joyful aspects of culture (festivals, music, food) resonate

**Tone guidance:** Match their energy — but don't be saccharine. They appreciate genuine enthusiasm, not performed cheerfulness.

**Derailers:** May skim difficult or unpleasant aspects of the language. The app should occasionally include the harder/sadder cultural content so they don't only get the highlights reel.

### Adaptability

**Core driver:** Goes with the flow. Lives in the present. Discovers the future one day at a time. Comfortable with change and unpredictability.

**Language-learning implications:** Adaptability learners do well with flexible, non-rigid curricula. They may resist long-term planning ("I'll be at C1 in three years") in favor of "what should I do today?" They're often comfortable with mistakes and uncertainty in conversation.

**Path leanings:** Flexible. Often comfortable with Output-First because they don't need full preparation.

**Section emphasis:**
- Section 12 (Weekly Challenge): present-tense framing — what can you do this week, not "in six months"
- Lesson pacing: comfortable with variable pace — some weeks slow, some fast, based on what life brings

**Tone guidance:** Present-focused. "Today's lesson..." not "your future fluency..."

**Derailers:** May struggle with very long-term goals. The app should help them see the cumulative pattern without forcing rigid planning.

---

## EXECUTING DOMAIN

### Achiever

**Core driver:** Internal fire to be productive. Stamina for sustained work. Satisfaction in being busy and accomplishing things. Daily completion matters.

**Language-learning implications:** Achiever learners thrive on daily practice habits and visible accomplishment. They benefit from streaks, checklists, completion tracking. They may overdo it and burn out if they don't pace themselves. The framework's weekly cumulative structure suits them.

**Path leanings:** Flexible. Both Input-First and Output-First work as long as there's daily volume to accomplish.

**Section emphasis:**
- Section 7 (Drill) and Section 11 (Self-Assessment): completion-trackable
- Section 12 (Weekly Challenge): clear "done" criteria

**Tone guidance:** Acknowledge effort and productivity. "You've put in serious work this week..."

**Derailers:** Burnout from over-doing. The app should occasionally remind them that rest is part of acquisition (memory consolidation happens during breaks). Also: equating volume with quality can lead to going through motions without depth.

### Arranger

**Core driver:** Both organized and flexible. Loves aligning people, resources, schedules for best results. Coordinates complexity.

**Language-learning implications:** Arranger learners enjoy building learning systems — their own tracking spreadsheets, their own Anki decks, their own study schedules. They benefit from giving them the *components* and letting them assemble. They may resist rigid prescribed paths but love flexible toolkits.

**Path leanings:** Flexible. They'll arrange whatever serves them best.

**Section emphasis:**
- All sections: appreciate that the framework provides components they can rearrange
- Section 12 (Weekly Challenge): they'll combine pieces in their own way

**Tone guidance:** Give them tools, not prescriptions. "Here's what's available — here's how it can fit together — your call."

**Derailers:** May spend too much time arranging the system instead of using it. The app should occasionally redirect to actual practice.

### Belief

**Core driver:** Core values that don't change. Strong sense of purpose. Decisions flow from deeply-held principles.

**Language-learning implications:** Belief learners are sustained by purpose — they're learning the language for a *reason* that matters to them (family heritage, faith, service, meaningful work). When the reason is clear, they're resilient. When the reason is unclear or contradicted, they may quit despite skill.

**Path leanings:** Flexible — depends on the underlying purpose.

**Section emphasis:**
- Section 1 (Lesson Overview): connect to deeper purpose when relevant
- Section 6 (Cultural Note): meaning, ethics, values embedded in language and culture

**Tone guidance:** Acknowledge purpose. "This phrase reflects values that..."

**Derailers:** May lose motivation if learning feels disconnected from purpose. The app can ask their motivation during onboarding and reference it.

### Consistency

**Core driver:** Treats everyone the same. Values fairness, clear rules, predictable procedures. Doesn't like arbitrary exceptions.

**Language-learning implications:** Consistency learners want clear rules they can apply uniformly. They may struggle with languages that have many exceptions ("why is this verb irregular?") and benefit from systematic explanations. They appreciate predictable lesson structure (the 12-section template helps them).

**Path leanings:** Path I on grammar (explicit) — they want the system explicit.

**Section emphasis:**
- Section 3 (Grammar Focus): emphasize the systematic, even when noting exceptions
- Section 7 (Drill): predictable structure week to week

**Tone guidance:** Systematic. Acknowledge irregularities honestly but place them within the broader system.

**Derailers:** Frustration with irregularities. The app can frame exceptions as historical artifacts (Context theme overlap) rather than arbitrary.

### Deliberative

**Core driver:** Careful, cautious decision-making. Anticipates risks. Moves forward only after consideration.

**Language-learning implications:** Deliberative learners take time before speaking — they want to be sure before producing. They benefit from extensive preparation. They're often resistant to Output-First methods that ask them to speak before feeling ready.

**Path leanings:** Strongly Path I (Input-First). They need to feel prepared. Forcing them into early output is counterproductive.

**Section emphasis:**
- Section 4 (Reading) and 5 (Listening): rich input, plenty of preparation
- Section 11 (Self-Assessment): they'll genuinely use this to gauge readiness

**Tone guidance:** Respect their pace. "When you feel ready..." not "speak now!"

**Derailers:** May postpone speaking indefinitely. The app can offer low-risk speaking options (recording themselves, talking to themselves) before high-risk (conversation with native speaker).

### Discipline

**Core driver:** Routine and structure. Daily habits. Order and predictability. Plans the day, the week, the month.

**Language-learning implications:** Discipline learners thrive on consistent daily practice. The framework's habit-formation principle (Part 8.11) is their natural mode. They benefit from clear schedules, predictable lesson structure, recurring time slots.

**Path leanings:** Flexible — discipline applies to any path equally.

**Section emphasis:**
- All sections: structured, predictable
- Section 11 (Self-Assessment): they'll track consistency

**Tone guidance:** Structured. "This week, build in 20 minutes daily for..."

**Derailers:** Rigidity. Life interrupts routines; they may treat a missed day as failure. The app should normalize occasional misses as part of long-term consistency.

### Focus

**Core driver:** Takes a direction and pursues it. Prioritizes ruthlessly. Filters out distractions. Knows what to ignore.

**Language-learning implications:** Focus learners concentrate on one language at a time and one priority within that language. They may resist learning multiple things at once. They benefit from clear weekly priorities (the curriculum's structure helps).

**Path leanings:** Flexible — but they'll commit to whatever path they choose and not bounce around.

**Section emphasis:**
- Section 1 (Lesson Overview): clear weekly priority
- Section 12 (Weekly Challenge): one clear thing to accomplish

**Tone guidance:** Crisp, prioritized. "This week's one thing is..."

**Derailers:** May ignore important secondary skills. The app should occasionally remind them to address weaker areas (Part 8.7).

### Responsibility

**Core driver:** Psychological ownership of commitments. Dependable. Embraces honesty and loyalty. "I said I would, so I will."

**Language-learning implications:** Responsibility learners make commitments to learning and keep them. They may benefit from public commitment (telling someone they're learning) or commitment to a tutor (financial accountability). They're sustained by integrity.

**Path leanings:** Flexible.

**Section emphasis:**
- Section 12 (Weekly Challenge): explicit commitment language ("by Friday, I will...")

**Tone guidance:** Treat them as committed adults. They don't need motivation tricks; they need clear commitments.

**Derailers:** Over-commitment to other obligations can crowd out language learning. The app can help them protect dedicated time.

### Restorative

**Core driver:** Adept at fixing problems. Sees what's broken and works to restore it. Diagnostic instinct.

**Language-learning implications:** Restorative learners are good at identifying their own weak spots and working on them. They benefit from honest feedback that names errors specifically. They may also be drawn to languages they've previously failed at (high school Spanish, college Latin) for the satisfaction of fixing earlier failure.

**Path leanings:** Flexible. Path I on grammar (so they can diagnose specifically).

**Section emphasis:**
- Section 7 (Drill): targeted to weak spots
- Section 11 (Self-Assessment): they'll engage seriously with what's not working

**Tone guidance:** Honest about gaps. "This is a common error — here's the fix."

**Derailers:** May over-focus on errors and lose sight of progress. The app should balance error-correction with progress acknowledgment.

---

## INFLUENCING DOMAIN

### Activator

**Core driver:** Turns thoughts into action. Wants to do, not just discuss. Energy increases with movement.

**Language-learning implications:** Activator learners want to *use* the language immediately. They're impatient with extensive preparation; they want to try it now. Speak from day one, apps, immediate immersion appeal to them.

**Path leanings:** Strongly Path II (Output-First). Don't make them wait — get them speaking.

**Section emphasis:**
- Section 8 (Speaking) and 12 (Weekly Challenge): immediate, actionable
- Section 3 (Grammar Focus): give them what they need to start using, not exhaustive theory

**Tone guidance:** Action-oriented. "Right now, you can already say..."

**Derailers:** May skip important foundation if it doesn't feel actionable. The app can frame foundation as immediately applicable.

### Command

**Core driver:** Presence. Takes control of situations. Makes decisions. Comfortable with conflict and directness.

**Language-learning implications:** Command learners want to be effective in the language, not just competent — they want to lead conversations, make their points clearly, navigate disagreement. They benefit from learning how to be direct and how to take conversational initiative in the target language.

**Path leanings:** Path II (Output-First) usually. They want to be operational.

**Section emphasis:**
- Section 8 (Speaking): include conversational leadership — how to interrupt politely, redirect, ask follow-up questions, push back
- Section 10 (Cultural/Pragmatic Notes): how directness varies across cultures

**Tone guidance:** Direct. They appreciate confidence and clarity.

**Derailers:** May come across as too direct in cultures where indirectness is the norm. The app should explicitly address this.

### Communication

**Core driver:** Easily puts thoughts into words. Good conversationalist and presenter. Enjoys finding the right words.

**Language-learning implications:** Communication learners are natural fits for language learning — articulation is their gift. They'll enjoy the challenge of finding the right word, the perfect phrase, the elegant turn. They benefit from rich vocabulary and idiom focus.

**Path leanings:** Path II (Output-First) usually. They want to talk.

**Section emphasis:**
- Section 2 (Vocabulary): rich vocabulary, idioms, ways to express the same thing with different nuances
- Section 8 (Speaking) and 9 (Writing): emphasize expressive range

**Tone guidance:** Wordsmith-respecting. "There are several ways to say this — each with a slightly different feel..."

**Derailers:** May plateau when their L1 ability outpaces their L2 expressiveness and feel frustrated. The app should normalize this gap as part of acquisition.

### Competition

**Core driver:** Measures progress against others. Loves contests, comparisons, winning.

**Language-learning implications:** Competition learners are motivated by comparison — they want to know how their progress stacks up against benchmarks, other learners, native-speaker norms. They benefit from levels, tests, rankings (HSK levels, JLPT certifications, CEFR placement).

**Path leanings:** Flexible — whatever produces measurable wins.

**Section emphasis:**
- Section 11 (Self-Assessment): include benchmarks against typical learners at this level
- Section 12 (Weekly Challenge): can include "compete" framings (timed exercises, accuracy targets)

**Tone guidance:** Competitive. "Most learners at this level can do X — can you?"

**Derailers:** May lose motivation if they feel they're behind. The app should also include comparison-against-past-self.

### Maximizer

**Core driver:** Pushes for excellence, not just competence. Refines strengths toward mastery. Doesn't settle for "good enough."

**Language-learning implications:** Maximizer learners want to be excellent, not just functional. They'll refine pronunciation, register, idiomatic naturalness long past the point most learners stop. They may resist "good enough is good enough" framing.

**Path leanings:** Often Path I (Input-First) because they want native-like quality, not just communication. Path I on grammar to understand the system fully.

**Section emphasis:**
- Section 8 (Speaking): pronunciation refinement, register accuracy
- Section 10 (Cultural/Pragmatic Notes): pragmatic excellence, native-like usage

**Tone guidance:** Excellence-oriented. "Beyond just being understood, here's how to sound truly natural..."

**Derailers:** Perfectionism can block production. They may not speak because their output isn't yet excellent. The app should occasionally remind them that production at "good enough" generates the feedback needed to reach excellent.

### Self-Assurance

**Core driver:** Inner confidence. Trusts own judgment. Doesn't need external validation. Comfortable making decisions.

**Language-learning implications:** Self-Assurance learners aren't easily shaken by mistakes or critique. They'll attempt boldly. They may benefit less from extensive prep and more from learning by doing.

**Path leanings:** Path II (Output-First) often — they don't need readiness, they have it intrinsically.

**Section emphasis:**
- Section 8 (Speaking) and 12 (Weekly Challenge): bold, ambitious targets
- Less need for Section 11 (Self-Assessment) hand-holding

**Tone guidance:** Confident, direct. They don't need reassurance.

**Derailers:** May overestimate readiness and produce errors confidently. The app should provide honest feedback even when not requested.

### Significance

**Core driver:** Wants to make a big impact. Independent. Prioritizes work that increases influence and recognition.

**Language-learning implications:** Significance learners are motivated by what the language will *let them do* in the world — engage with important communities, work in international roles, contribute to causes that matter, build reputation as someone who bridges cultures. They want their learning to matter.

**Path leanings:** Flexible — driven by impact.

**Section emphasis:**
- Section 6 (Cultural Note): connection to impactful figures, movements, opportunities
- Section 12 (Weekly Challenge): include impactful applications

**Tone guidance:** Impact-oriented. "This is the kind of language that enables you to engage with [significant context]..."

**Derailers:** May lose motivation if learning feels incremental and unrecognized. The app should occasionally highlight what they've enabled themselves to do.

### Woo

**Core driver:** Loves meeting new people and winning them over. Energized by social novelty. Comfortable with strangers.

**Language-learning implications:** Woo learners thrive on language exchange events, new conversation partners, social novelty. They speak from day one without inhibition. They may have less depth in any one relationship but enormous breadth.

**Path leanings:** Strongly Path II (Output-First). Social interaction is the fuel.

**Section emphasis:**
- Section 8 (Speaking) and 12 (Weekly Challenge): variety of social contexts, new partners, language exchange events
- Section 10 (Cultural/Pragmatic Notes): how to make a good first impression, small-talk norms

**Tone guidance:** Social. "This week, meet three new..."

**Derailers:** Shallow practice that doesn't build depth. The app can encourage occasional deep dives with one partner alongside the breadth.

---

# THEME COMBINATION GUIDANCE

Beyond individual themes, combinations create distinctive profiles. The app should attend to these patterns when present in a learner's top 10.

## High Strategic Thinking Density (5+ Strategic Thinking themes in top 10)

This is an "intellectual depth" profile. The learner wants to understand the system, see the patterns, know the history, and operate analytically. Heavy emphasis on Sections 3 (Grammar), 6 (Cultural Note historical/philosophical), and 10 (Pragmatic depth). Path I on both axes (Input-First, Explicit Grammar) usually fits. Avoid gamification pressure — they're motivated by depth, not streaks.

## High Executing Density (5+ Executing themes)

This is a "productive consistency" profile. Visible progress and completion drive motivation. Heavy emphasis on Sections 7 (Drill), 11 (Self-Assessment with tracking), 12 (Weekly Challenge with clear done criteria). Flexible on paths but consistent on daily practice.

## High Influencing Density (5+ Influencing themes)

This is a "social impact" profile. Want to use language to connect, persuade, and impact. Strongly Path II (Output-First). Heavy emphasis on Sections 8 (Speaking) and 12 (Weekly Challenge with social application).

## High Relationship Building Density (5+ Relationship Building themes)

This is a "connection-focused" profile. Want to use language to build deep human connection. Often Path II or balanced. Heavy emphasis on Sections 6 (Cultural Note about people), 8 (Speaking with specific partners), 10 (Pragmatic depth).

## Notable Two-Theme Combinations

- **Input + Intellection:** Etymological/historical/theoretical depth. Show the full architecture of patterns.
- **Input + Learner:** Voracious resource consumer. Curate carefully or they'll overwhelm themselves.
- **Connectedness + Context:** Wants to see the language in its cultural-historical web. Heavy cultural note treatment.
- **Strategic + Analytical:** Wants the most efficient path. Make tradeoffs explicit; they'll optimize.
- **Achiever + Discipline:** Daily practice machine. Build clear daily structure.
- **Activator + Communication:** Speak from day one, find partners now. Path II strongly.
- **Empathy + Harmony:** Sensitive to social risk in producing. Provide pragmatic safety; gentle output paths.
- **Maximizer + Analytical:** Refinement-oriented. Native-like quality matters; explicit instruction on register and pragmatics.
- **Ideation + Strategic:** Loves seeing patterns and picking the best path. Show alternatives; let them choose.
- **Relator + Developer:** Best served by a long-term tutor relationship. Suggest finding one.
- **Belief + Significance:** Driven by deep purpose. Ask their reason during onboarding; reference it.
- **Futuristic + Achiever:** Long-term vision + daily execution. Bridge today's work to long-term outcome regularly.
- **Context + Connectedness:** Wants to see how everything connects historically. Heavy historical-cultural treatment.

## Reading the Domain Distribution

The relative balance of domains in a learner's top 10 reveals their motivational gravity. A learner with 8 Strategic Thinking themes and 2 Relationship Building themes (and zero Executing/Influencing in the top tier) — like the framework's example user — is fundamentally a depth-and-connection learner, not a productivity-and-impact learner. Lesson design should mirror this. Conversely, a learner with 6 Executing themes and 3 Influencing themes is a do-it-and-make-it-matter learner — lesson design emphasizes action and visible impact.

---

# WHEN GALLUP PROFILE IS NOT PROVIDED

Most learners won't have taken the Gallup assessment. The app should:
- Treat the Gallup profile as optional during onboarding
- Default to the balanced lesson design described in Part 10 of pedagogy-foundations when no profile is provided
- Offer a lightweight alternative: a 5-question self-identification that places the learner roughly in a domain ("I'm motivated mostly by: completing things / persuading others / building relationships / understanding patterns")
- Make clear that the Gallup integration is enhancement, not gating

The lessons should remain excellent for learners without a profile. The profile is a calibration tool, not a prerequisite.

---

*End of Gallup CliftonStrengths Pedagogy for Language Learning. Embed in the framework. When a learner provides their top 10 strengths during onboarding, the prompt builder pulls the relevant mappings and includes them in the lesson-generation prompt.*
`;
