// lib/references/index.ts
// Auto-generated by scripts/embed-references.ts
// Imports all reference content and provides a lookup helper by language code.

import { pedagogyFoundations } from './pedagogy';
import { gallupPedagogy } from './gallup-pedagogy';
import { learnerProfilePedagogy } from './learner-profile-pedagogy';
import { japaneseAddendum } from './japanese-addendum';
import { mandarinAddendum } from './mandarin-addendum';
import { arabicReference } from './arabic-ref';
import { bengaliReference } from './bengali-ref';
import { cebuanoReference } from './cebuano-ref';
import { danishReference } from './danish-ref';
import { dutchReference } from './dutch-ref';
import { englishReference } from './english-ref';
import { filipinoReference } from './filipino-ref';
import { frenchReference } from './french-ref';
import { germanReference } from './german-ref';
import { greekReference } from './greek-ref';
import { hebrewReference } from './hebrew-ref';
import { hindiReference } from './hindi-ref';
import { indonesianReference } from './indonesian-ref';
import { irishReference } from './irish-ref';
import { italianReference } from './italian-ref';
import { japaneseReference } from './japanese-ref';
import { koreanReference } from './korean-ref';
import { mandarinReference } from './mandarin-ref';
import { norwegianReference } from './norwegian-ref';
import { persianReference } from './persian-ref';
import { polishReference } from './polish-ref';
import { portugueseReference } from './portuguese-ref';
import { russianReference } from './russian-ref';
import { spanishReference } from './spanish-ref';
import { swahiliReference } from './swahili-ref';
import { swedishReference } from './swedish-ref';
import { thaiReference } from './thai-ref';
import { turkishReference } from './turkish-ref';
import { ukrainianReference } from './ukrainian-ref';
import { urduReference } from './urdu-ref';
import { vietnameseReference } from './vietnamese-ref';

export { pedagogyFoundations, gallupPedagogy, learnerProfilePedagogy, japaneseAddendum, mandarinAddendum, arabicReference, bengaliReference, cebuanoReference, danishReference, dutchReference, englishReference, filipinoReference, frenchReference, germanReference, greekReference, hebrewReference, hindiReference, indonesianReference, irishReference, italianReference, japaneseReference, koreanReference, mandarinReference, norwegianReference, persianReference, polishReference, portugueseReference, russianReference, spanishReference, swahiliReference, swedishReference, thaiReference, turkishReference, ukrainianReference, urduReference, vietnameseReference };

const LANGUAGE_REFERENCES: Record<string, string> = {
  ar: arabicReference,
  bn: bengaliReference,
  ceb: cebuanoReference,
  da: danishReference,
  nl: dutchReference,
  en: englishReference,
  tl: filipinoReference,
  fr: frenchReference,
  de: germanReference,
  el: greekReference,
  he: hebrewReference,
  hi: hindiReference,
  id: indonesianReference,
  ga: irishReference,
  it: italianReference,
  ja: japaneseReference,
  ko: koreanReference,
  zh: mandarinReference,
  'no': norwegianReference,
  fa: persianReference,
  pl: polishReference,
  pt: portugueseReference,
  ru: russianReference,
  es: spanishReference,
  sw: swahiliReference,
  sv: swedishReference,
  th: thaiReference,
  tr: turkishReference,
  uk: ukrainianReference,
  ur: urduReference,
  vi: vietnameseReference,
};

const LANGUAGE_ADDENDA: Record<string, string> = {
  ja: japaneseAddendum,
  zh: mandarinAddendum,
};

export function getLanguageReference(langCode: string): string {
  return LANGUAGE_REFERENCES[langCode] || '';
}

// Returns the language-specific pedagogical addendum if one exists.
// Returns null when the language has no addendum (most languages).
export function getLanguageAddendum(langCode: string): string | null {
  return LANGUAGE_ADDENDA[langCode] || null;
}
