// Auto-generated by scripts/embed-references.ts
// Source: japanese-curriculum-reference.md
// Do not edit by hand. Re-run the embedding script if the source changes.

export const japaneseReference = `# Japanese Curriculum Reference

**Purpose.** This is the Japanese-specific knowledge base for the language learning project. It applies the universal pedagogical framework (see \`pedagogy-foundations.md\`) to Japanese: how Japanese is characterized along the seven dimensions, why specific variety decisions were made, the full 200-week curriculum architecture aligned to JLPT levels, Japanese-specific resources and assessment paths, and notes on what English speakers find hard about Japanese specifically.

**Companion documents.**
- \`pedagogy-foundations.md\` — Universal principles + the seven-dimensional framework
- \`spanish-curriculum-reference.md\` — Spanish-specific reference (the model for this document)
- \`claude-code-prompt.md\` — The build spec for the lesson-generator app (Spanish data embedded; Japanese data to be added)
- This document — Japanese-specific reference

**For builders.** Japanese requires non-trivial adaptation of the lesson template (Part 10 details). Specifically, every lesson needs a Kanji Track section, and pronunciation work emphasizes pitch accent rather than the more familiar segmental phonemes.

---

# PART 1 — JAPANESE LANGUAGE PROFILE

## 1.1 Basic Facts

- **Native speakers:** ~125 million (almost all in Japan)
- **Total speakers (including L2):** ~128 million
- **Geographic distribution:** Japan (essentially exclusively); small heritage-speaker communities in Brazil (largest Japanese diaspora), Peru, Hawaii, and the U.S. West Coast
- **Official status:** Japan (de facto official, not constitutionally specified); Palau's Angaur State (one of three official languages)
- **ISO 639-1 code:** ja
- **Linguistic family:** Japonic (its own small family; relationship to Korean, Altaic, and others is debated but not established)

## 1.2 The Seven Dimensions Applied to Japanese

### Phonology — *Close phoneme inventory, but pitch-accent and rhythm matter*

The segmental phonology is surprisingly approachable for English speakers:

- **5 simple vowels** (a, i, u, e, o) — identical inventory to Spanish; never reduced to schwa
- **Most consonants familiar** — k, s, t, n, m, h, y, r, w, p, b, d, g, plus the special ん (moraic n)
- **The Japanese "r"** is a tap, similar to Spanish single r — easier than English speakers expect

But the suprasegmental and rhythm features are where English speakers struggle:

- **Pitch accent (高低アクセント)** — words have pitch patterns that distinguish meaning. 雨 (ame, "rain", HL) vs. 飴 (ame, "candy", LH). 橋 (hashi, "bridge", LH) vs. 箸 (hashi, "chopsticks", HL). Wrong pitch usually doesn't break comprehension but instantly marks you as foreign.
- **Long vowels** are phonemic. おばさん (obasan, "aunt") vs. おばあさん (obāsan, "grandmother"). Skipping this matters.
- **Doubled consonants (sokuon, っ)** are phonemic. きて (kite, "come!") vs. きって (kitte, "stamp"). 
- **Mora-timed rhythm** — each mora (kana unit) takes roughly equal time, unlike stress-timed English. This produces the characteristic even cadence of Japanese.
- **Devoiced vowels** — i and u between voiceless consonants are devoiced (です sounds like "des"). Common but rarely taught explicitly.

**Implication:** Pitch accent training from Week 1 (in shadowing, not abstract drilling). Long-vowel and double-consonant awareness from Week 1 with the script. Pronunciation focus is heavier in early weeks than Spanish despite the simpler phoneme inventory.

### Writing System — *Mixed; the biggest structural difference from Spanish*

Japanese uses three scripts simultaneously plus occasional Latin:

- **Hiragana (ひらがな)** — 46 base characters + diacritics. Used for native Japanese grammatical particles, verb endings, and words without kanji. Phonetic syllabary.
- **Katakana (カタカナ)** — 46 base characters (same sounds as hiragana, different shapes). Used for foreign loanwords, onomatopoeia, emphasis, scientific names.
- **Kanji (漢字)** — Chinese-derived logographic characters. ~2,136 jōyō kanji for basic literacy; educated readers know ~3,000+. Each kanji has multiple readings (on-yomi from Chinese, kun-yomi native Japanese).
- **Romaji (ローマ字)** — Latin alphabet. Used in branding, transitional learning materials, and certain technical contexts. **Should be phased out by Week 3** in the curriculum to prevent dependency.

A typical Japanese sentence mixes all three native scripts: 私はラーメンを食べました (Watashi wa rāmen wo tabemashita — "I ate ramen"). Watashi/wa/wo/mashita = kanji+hiragana grammatical scaffolding; rāmen = katakana for foreign word; tabe = kanji root.

**Implication:** This is the largest structural adaptation from Spanish.

- Weeks 1–2 are pure script work (hiragana + katakana). No grammar yet — these scripts must be readable before lessons can use them.
- From Week 3 onward, kana are used in every lesson — never romaji except for pitch-accent notation.
- **Kanji is a parallel track** — every lesson from Week 3 onward includes a Kanji Section with ~10–25 new kanji per week. Cumulative target: ~100 by end of N5, ~300 by end of N4, ~650 by end of N3, ~1,000 by end of N2, ~2,000 by end of N1.
- Kanji learning method: combination of meaning + writing + reading + compound vocabulary. Spaced repetition (Anki, WaniKani) is essential.

### Morphology — *Agglutinative*

Japanese builds words by stacking predictable suffixes. Unlike Spanish fusional inflection (where one ending carries multiple meanings), Japanese suffixes are modular — each does one thing, and they combine cleanly.

- **Two verb classes:** ichidan (一段, "one-row", a.k.a. ru-verbs) and godan (五段, "five-row", a.k.a. u-verbs), plus two irregular verbs (来る kuru "to come" and する suru "to do").
- **Verb conjugation** = base form + suffixes. To make 食べる (taberu, "eat") into "wasn't eaten by someone": 食べ-られ-な-かった (tabe-rare-na-katta = root-passive-negative-past). Each piece is predictable.
- **Adjectives also inflect:**
  - い-adjectives (e.g., 高い takai "expensive") conjugate like verbs: 高くない (not expensive), 高かった (was expensive)
  - な-adjectives (e.g., 静か shizuka "quiet") behave like nouns + な: 静かな部屋 (quiet room), 静かじゃない (not quiet)
- **Particles (助詞) handle grammatical role** — は (topic), が (subject), を (direct object), に (indirect object, target, time), で (location of action, instrument), へ (direction), と (with, and), から (from), まで (until), の (possessive, modifier). Mastering particles IS mastering basic Japanese grammar.
- **Politeness affects verb forms throughout** — see Register section below.

**Implication:** Suffix-stacking drills replace conjugation tables. Particle work is THE central grammar challenge of N5–N4. The te-form (Week 20) is the single highest-leverage grammar topic — once mastered, it unlocks dozens of downstream patterns.

### Word Order — *SOV (verb-final); modifiers precede modified*

Japanese is rigorously verb-final. Modifiers (adjectives, relative clauses) come before the noun they modify. This requires real cognitive restructuring for English speakers.

- 私はラーメンを食べる (Watashi wa rāmen wo taberu) — "I ramen eat"
- 昨日駅で買った本 (kinō eki de katta hon) — "[Yesterday at-station bought] book" = "The book I bought at the station yesterday"
- Subjects are commonly omitted when context makes them clear — this is dramatically more frequent than in Spanish pro-drop.
- Topic-comment structure (with は) is very different from English subject-predicate.

**Implication:** Word-order practice from Week 5 onward, with sentence-building drills that force production in correct order. Relative clauses (Week 25) are a major restructuring moment.

### Register — *Rich honorific system (keigo)*

Japanese encodes social relationships grammatically. The same verb has different forms depending on who is speaking, who is being spoken to, and who is being spoken about. **This is non-negotiable to learn early** — wrong register is socially serious in a way that wrong grammar isn't.

Three main keigo categories:

- **丁寧語 (teineigo, polite language)** — the です/ます forms. Default polite register. Introduced Week 5.
- **尊敬語 (sonkeigo, honorific language)** — elevates the subject (the person you're talking ABOUT). Used for customers, superiors, strangers in formal contexts. 食べる → 召し上がる (to eat → to consume, hon.).
- **謙譲語 (kenjōgo, humble language)** — humbles the speaker (you, when talking about yourself in relation to someone of higher status). 食べる → いただく (to eat → humbly receive/eat).

Plus the plain/casual form (常体 jōtai) for friends, family, internal monologue, and writing in certain registers.

A complete competent speaker uses all four registers fluidly, switching multiple times in a single conversation as topics and addressees shift.

**Implication:** Polite form (です/ます) is the default from Week 5. Plain form is introduced Week 31 with explicit register-switching practice. Keigo proper (sonkeigo + kenjōgo) gets its own multi-week treatment Weeks 61–67 with practice in business and service contexts. From there on, register awareness is woven into every lesson.

### Cultural-Pragmatic Distance — *Distant*

Japanese is one of the most culturally distant languages for English speakers among major world languages. Communication operates on fundamentally different defaults:

- **High-context communication** — much is left unsaid; reading the air (空気を読む kūki wo yomu) is a named cultural skill
- **Indirectness as politeness** — direct requests can feel rude; circumlocution and hedging are admired
- **Silence has communicative value** — pauses don't need to be filled; comfortable silence is normal
- **Face culture (面子 mentsu)** — maintaining the dignity of all parties is a primary conversational goal
- **In-group / out-group distinction (内 uchi vs. 外 soto)** — language shifts dramatically based on whether you're talking about people in your group or others'
- **Vertical relationships (縦社会 tate-shakai)** — age, seniority, and hierarchical position shape every interaction
- **Apology frequency** — すみません (sumimasen) functions as "sorry", "thank you", and "excuse me" — used dramatically more often than English equivalents
- **Subject omission as a cultural value** — explicitly stating "I" can come across as self-centered

**Implication:** Very high cultural-note density. Pragmatic content is taught alongside grammar, not as garnish. The lesson template's Cultural Note section often anchors the Speaking and Writing exercises, not the other way around.

### Resource Availability — *Major language; abundant*

Japanese has world-class learning resources due to global anime/manga/J-pop fandom and historical economic interest.

- **Comprehensive textbook series** — Genki (most popular), Minna no Nihongo, Tobira
- **Free online resources** — Tofugu, Tae Kim's Guide, Imabi (advanced), Maggie Sensei
- **Kanji-specific tools** — WaniKani (~$9/mo, exceptional), Heisig's Remembering the Kanji method
- **Reading practice** — NHK News Easy (graded news), Satori Reader, manga at every level
- **Listening** — JapanesePod101, Nihongo con Teppei, Anime, J-dramas
- **Tutoring** — iTalki, Preply, Cafetalk (Japan-based platform)
- **Language partners** — Tandem, HelloTalk; Japanese learners of English are abundant

**Implication:** Specific resources can be recommended at every level. The kanji-track recommendations in particular benefit from tools that don't exist for other writing systems (WaniKani is essentially a science-of-learning-applied-to-kanji product).

---

# PART 2 — VARIETY DECISION

## 2.1 The Decision

**Standard Japanese (標準語 hyōjungo)**, based on the Tokyo dialect, as the productive base. This is the unambiguous primary choice.

Exposure to regional dialects (especially **関西弁 Kansai-ben** — Osaka/Kyoto, the second-most-encountered dialect) as receptive content at advanced levels (Weeks 130+). Brief exposure to **東北弁 Tōhoku-ben**, **博多弁 Hakata-ben** (Fukuoka), and **沖縄方言 Okinawan** as cultural awareness.

## 2.2 Rationale

Unlike Spanish, Japanese has very clear central gravity:

- **Hyōjungo is universally understood** — taught in schools, used in national media, expected in formal contexts everywhere
- **Tokyo's media dominance** — NHK, J-dramas, anime, news all default to hyōjungo
- **Regional dialects are real but stratified** — Kansai-ben is widely recognized and used in comedy; other dialects have weaker cross-regional presence
- **No equivalent to Spanish's Latin America vs Spain split** — there's no "alternative production base" the way Mexican Spanish is to Castilian

This is a simpler variety decision than Spanish required.

## 2.3 What Plain/Polite/Keigo Are NOT

Important distinction: **plain form, polite form, sonkeigo, and kenjōgo are not varieties or dialects — they are registers within standard Japanese.** All speakers use all of them, choosing based on situation. The curriculum teaches all four progressively as part of the core language.

## 2.4 Written vs. Spoken Japanese

Significant register differences between everyday speech and formal writing:

- Spoken Japanese uses many particles and sentence-ending markers (よ yo, ね ne, わ wa, etc.) that don't appear in writing
- Formal writing uses kango (Sino-Japanese compounds) much more heavily than speech
- Some grammar patterns are essentially written-only (である de aru as a formal copula)

The curriculum addresses both, weighted toward spoken Japanese in early levels and adding written register from N3.

---

# PART 3 — CURRICULUM ARCHITECTURE

## 3.1 At a Glance

- **Total length:** 200 weeks (~3.8 years at one lesson per week)
- **Pacing:** one lesson per week plus daily practice (60–90 min/day recommended — significantly more than Spanish due to kanji track)
- **Total study time at recommended pace:** ~1,800–2,200 hours, approximately matching the Foreign Service Institute's estimate for Category IV languages
- **Level structure:** Five JLPT levels (N5 → N1), with CEFR mappings noted. Beyond-N1 polish in final weeks.

## 3.2 The Five Levels

| Level | Weeks | Span | JLPT Goal | CEFR Equiv | Kanji (cumulative) | Vocab (cumulative) |
|---|---|---|---|---|---|---|
| N5 — Foundations | 1–30 | 30 weeks | JLPT N5 | A1 to lower A2 | ~100 | ~800 |
| N4 — Elementary | 31–60 | 30 weeks | JLPT N4 | A2 to lower B1 | ~300 | ~1,500 |
| N3 — Intermediate | 61–110 | 50 weeks | JLPT N3 | B1 | ~650 | ~3,750 |
| N2 — Upper-Intermediate | 111–160 | 50 weeks | JLPT N2 | B2 | ~1,000 | ~6,000 |
| N1 — Advanced | 161–195 | 35 weeks | JLPT N1 | C1 (low C2) | ~2,000 | ~10,000+ |
| Beyond N1 — Mastery polish | 196–200 | 5 weeks | — | C2 polish | 2,000+ | 12,000+ |

**Note on JLPT vs. CEFR mapping.** The JLPT measures different competencies than CEFR — it emphasizes reading and listening (no productive speaking or writing tested), while CEFR measures all four skills. JLPT N1 is widely considered to fall somewhere between CEFR C1 and C2 on the receptive side, but a learner with JLPT N1 may have only B2 productive ability without dedicated speaking and writing practice. **The curriculum compensates by including substantial productive practice at every level**, so a learner completing this curriculum should reach genuine C1+ ability, not just receptive N1.

## 3.3 Pacing Philosophy

- **N5 (Weeks 1–30):** Slow, careful, scaffolded. Weeks 1–4 are pure script and pronunciation. Grammar foundations from Week 5, with the polite form (です/ます) as the default register throughout. End at JLPT N5 readiness.
- **N4 (Weeks 31–60):** Acceleration. Plain form introduced Week 31. Te-form mastery Weeks 20–30 unlocks compound grammar. Giving/receiving verbs (Weeks 41–42) — a famously difficult topic — get dedicated treatment.
- **N3 (Weeks 61–110):** Keigo deep-dive (Weeks 61–67). Reading and listening to native-leaning content begins. Most grammar patterns have been introduced; this level deepens and refines.
- **N2 (Weeks 111–160):** The longest level. N2 is famously vocabulary- and grammar-pattern-heavy with ~200 distinct patterns. Reading authentic literature, news, and business material.
- **N1 (Weeks 161–195):** The advanced level. Subtle distinctions between near-synonymous patterns. Classical literature exposure. Specialized professional Japanese.
- **Polish (Weeks 196–200):** Classical Japanese (kobun) exposure, dialects, mastery capstone.

## 3.4 The Kanji Parallel Track

Unlike Spanish, Japanese requires a sustained parallel learning track for kanji throughout the curriculum. Target pacing:

| Phase | Weeks | New Kanji per Week | Cumulative |
|---|---|---|---|
| N5 | 5–30 | ~4 new + reinforcement | ~100 by Week 30 |
| N4 | 31–60 | ~7 new + reinforcement | ~300 by Week 60 |
| N3 | 61–110 | ~7 new + reinforcement | ~650 by Week 110 |
| N2 | 111–160 | ~7 new + reinforcement | ~1,000 by Week 160 |
| N1 | 161–195 | ~30 new + reinforcement | ~2,000 by Week 195 |

(Weeks 1–4 have no new kanji — those weeks are dedicated to hiragana, katakana, and basic pronunciation/grammar foundations.)

**Each lesson from Week 5 onward includes a Kanji Section** with the week's new kanji presented as: character + on-yomi readings + kun-yomi readings + meanings + 2–3 example compound words + stroke order recommendation. Daily Anki or WaniKani review is non-negotiable for kanji retention.

---

# PART 4 — WEEK-BY-WEEK OVERVIEW

The full structured data will live in \`lib/curricula/japanese.ts\` (to be built). This section is the readable overview. Early weeks are detailed because foundation matters most; later weeks are grouped because the patterns are familiar.

## 4.1 Level N5 — Foundations (Weeks 1–30)

| W | Title | Core focus |
|---|---|---|
| 1 | **Hiragana Part 1** | Vowels and k/s/t/n-rows (あ-の); pitch accent introduction; no kanji yet |
| 2 | **Hiragana Part 2 + Katakana intro** | h/m/y/r/w rows + ん; diacritics; complete hiragana; katakana vowels |
| 3 | **Katakana mastery** | Complete katakana; reading short loanword phrases; long vowels and doubled consonants |
| 4 | **Pronunciation deep dive + first phrases** | Pitch accent patterns; mora-timed rhythm; greetings and self-introduction phrases |
| 5 | Self-introduction; です | はじめまして; 私は〜です; question marker か; first kanji: 人 日 月 火 |
| 6 | Demonstratives; の particle | これ/それ/あれ; possession with の; first 5 kanji this week |
| 7 | Yes/no questions; negation | じゃありません; も and と; numbers 1–10 |
| 8 | Location and existence | あります vs います; に particle for location |
| 9 | Numbers and counters | Counters (~kō, ~mai, ~hon); numbers to 1,000 |
| 10 | Time, days, schedule | Telling time; days of week; schedule vocabulary |
| 11 | い-adjectives | Present positive; i-adjective basics |
| 12 | な-adjectives | Present positive; na-adjective basics; contrast with i-adjectives |
| 13 | Adjective conjugation | Past, negative, past negative for both adjective types |
| 14 | Verbs introduction | Masu form; ichidan vs godan classification; first verbs |
| 15 | Verb conjugation | Present, past, negative, past negative — polite form |
| 16 | Particles deep dive | を, に, で, へ — when to use which |
| 17 | は vs が — the famous distinction | Topic vs subject; when each is appropriate |
| 18 | Family vocabulary | Internal family (うち) vs others' family (よそ); humble/honorific terms |
| 19 | Daily routines | Time expressions; frequency adverbs; routine vocabulary |
| 20 | **Te-form formation** | The rules for forming te-form by verb class; this is the highest-leverage grammar week |
| 21 | Te-form uses | Connecting actions; ~てください for requests |
| 22 | Te-iru | Continuous action; resultant state; habitual action |
| 23 | Permission and prohibition | ~てもいい; ~てはいけない |
| 24 | Dictionary form uses | ことができる (can); ことがある (have experience) |
| 25 | Modifying nouns with clauses | Relative clauses with plain verb forms (preview of plain form) |
| 26 | Want and desire | ~たい form; ~がほしい |
| 27 | Comparatives | より, ~のほうが, 一番 |
| 28 | Japanese counters | Mai, hon, hiki, ko, satsu, dai — and the systematic exceptions |
| 29 | Connectives | が (but), から (because), が・けど・でも |
| 30 | **N5 Review and JLPT N5 prep** | Mock N5; all four skills; kanji review (~100) |

## 4.2 Level N4 — Elementary (Weeks 31–60)

| W | Title | Core focus |
|---|---|---|
| 31 | **Plain form introduction** | Casual register; when to use; first explicit register-switching practice |
| 32 | Plain past, plain negative | Full plain-form conjugation across verbs and adjectives |
| 33 | Quotative と | "Said that…"; thinking quotative |
| 34 | Conditionals overview | と, たら, ば, なら — preview |
| 35 | Conditionals deep dive | When to use each conditional; meaning distinctions |
| 36 | Volitional form | ~よう/~ましょう; ~ようと思う |
| 37 | Potential form | "Can do"; ichidan rareru, godan eru |
| 38 | Passive form | Formation; direct passive vs. adversative passive |
| 39 | Causative form | Make/let someone do |
| 40 | Causative-passive | Be made to do (combination) |
| 41 | **Giving and receiving Part 1** | あげる (give out), くれる (give to me/in-group); directionality |
| 42 | **Giving and receiving Part 2** | もらう (receive); humble/honorific forms; te-form + giving verbs |
| 43 | Te-form + purpose verbs | ~に行く/来る/帰る; movement with purpose |
| 44 | Purpose: ために vs ように | Distinguishing the two "in order to" patterns |
| 45 | Should and must | ~べき; ~なければならない/~なきゃ; ~ないといけない |
| 46 | Seems / appears | そう, よう, みたい — distinguishing |
| 47 | Hearsay | ~そう (hearsay), ~らしい |
| 48 | Try doing | ~てみる |
| 49 | Have done before | ~たことがある |
| 50 | Completion and finality | ~てしまう / ~ちゃう |
| 51 | Workplace vocabulary | Office; meetings; basic business interactions |
| 52 | Travel vocabulary | Transportation; hotels; tourism in Japan |
| 53 | Shopping | Department stores; convenience stores; bargaining (limited in Japan) |
| 54 | Health and medical | Body parts; symptoms; doctor's visit |
| 55 | Communication | Phone, email basics; texting conventions |
| 56 | Food and restaurants | Japanese cuisine; ordering; restaurant etiquette |
| 57 | Directions | Asking for and giving directions in cities |
| 58 | Hobbies and interests | Talking about hobbies; club culture |
| 59 | Geography and regions of Japan | Honshū, Hokkaidō, Kyūshū, Shikoku, Okinawa — overview |
| 60 | **N4 Review and JLPT N4 prep** | Mock N4; all four skills; kanji review (~300) |

## 4.3 Level N3 — Intermediate (Weeks 61–110)

| W | Title | Core focus |
|---|---|---|
| 61 | **Keigo introduction** | Three levels overview; when each is used |
| 62 | Sonkeigo special verbs | いらっしゃる, おっしゃる, なさる, ご覧になる, etc. |
| 63 | Sonkeigo pattern | お/ご + verb + になる |
| 64 | Kenjōgo special verbs | 参る, 申し上げる, いたす, 拝見する, etc. |
| 65 | Kenjōgo pattern | お/ご + verb + する |
| 66 | Keigo in business contexts | Customer service language; phone keigo |
| 67 | Keigo practice scenarios | Service interactions; formal email; introductions |
| 68 | News and journalism Japanese | Headlines; bureaucratic register; NHK News Easy practice |
| 69 | Formal writing patterns | である copula; written discourse markers |
| 70 | Conditional ば deeper | Specific uses; idiomatic patterns |
| 71 | Conditional たら deeper | Versatile uses; temporal vs hypothetical |
| 72 | Even if | ~ても, ~でも; subjunctive concession |
| 73 | Although | のに, くせに — and their emotional connotations |
| 74 | While | ~ながら (simultaneous), ~あいだ (during) |
| 75 | Right after | ~た時, ~たとたん |
| 76 | As soon as | ~や否や, ~たちに |
| 77 | As long as | ~限り |
| 78 | Unless | ~なければ, ~ない限り |
| 79 | Excessively | ~すぎる |
| 80 | Finishing/completing | ~終わる, ~始める, ~続ける |
| 81 | Easy/hard to do | ~やすい, ~にくい |
| 82 | Way of doing | ~方; ~ようす |
| 83 | Manga and anime Japanese | Common idioms; sound effects (giseigo); youth speech |
| 84 | Music in Japanese | Lyrics analysis; J-pop, enka, hip-hop conventions |
| 85 | Movies and TV | J-drama language; film criticism vocabulary |
| 86 | Sports vocabulary | Baseball, sumo, soccer, martial arts |
| 87 | Politics and economy basics | Diet (国会), key political vocabulary |
| 88 | Environment and society | Climate, social issues vocabulary |
| 89 | Education in Japan | School system; university; exam culture |
| 90 | Technology and internet | Modern vocabulary; common loanwords |
| 91 | Religion and spirituality | Shinto, Buddhism, syncretism; shrine/temple etiquette |
| 92 | Japanese history overview | Major periods (Jōmon → Edo → Meiji → Shōwa → Heisei → Reiwa) |
| 93 | Regional culture deep dive | Differences between Kantō, Kansai, Tōhoku, Kyūshū |
| 94 | Festivals and holidays | Major festivals (matsuri); seasonal celebrations |
| 95 | Food culture | Regional cuisines; seasonality; etiquette |
| 96 | Modern subcultures | Otaku, kawaii, gyaru, salaryman culture |
| 97 | Business culture introduction | Hierarchy; meeting culture; business cards (meishi) |
| 98 | Personal relationships | Friendship, dating, marriage, life events in Japan |
| 99 | Idiomatic expressions and proverbs | 諺 (kotowaza); 四字熟語 (yojijukugo) introduction |
| 100 | N3 mid-checkpoint | Self-assessment; identify weak areas |
| 101–105 | N3 grammar consolidation | 50+ N3 grammar patterns in context |
| 106–109 | Reading and listening at level | Short stories; podcasts; J-dramas |
| 110 | **N3 Review and JLPT N3 prep** | Mock N3; all four skills; kanji review (~650) |

## 4.4 Level N2 — Upper-Intermediate (Weeks 111–160)

| Weeks | Focus | Notes |
|---|---|---|
| 111–120 | Advanced grammar patterns part 1 | Patterns like ~ばかりか, ~どころか, ~に限らず, ~を問わず |
| 121–130 | Advanced grammar patterns part 2 | ~あまり, ~ものの, ~がたい, ~ずにはいられない |
| 131–135 | Formal writing mastery | Essays, reports, formal letters |
| 136–140 | Reading literature | Short stories: Murakami (accessible), Kawabata, Tanizaki excerpts |
| 141–145 | News reading and listening | NHK; newspaper articles; political/economic discourse |
| 146–150 | Business Japanese | Negotiation, presentations, business correspondence |
| 151–155 | Specialized vocabulary | Choose 2 fields: medical, legal, scientific, IT, finance |
| 156–159 | N2 grammar review | Pattern-by-pattern review and practice |
| 160 | **N2 Review and JLPT N2 prep** | Mock N2; kanji review (~1,000) |

## 4.5 Level N1 — Advanced (Weeks 161–195)

| Weeks | Focus | Notes |
|---|---|---|
| 161–170 | N1 grammar patterns | The 100+ distinct N1 patterns; many with subtle distinctions from N2 versions |
| 171–175 | Literature deeper | Full short novels; modern classics |
| 176–180 | Classical/literary register | 〜であり, 〜たり, archaic patterns in formal writing |
| 181–185 | Professional Japanese deepening | Specialized field reading; conference Japanese |
| 186–190 | Rhetoric and persuasion | Speech preparation; debate; presentation |
| 191–194 | N1 grammar review | Pattern review; nuance distinctions |
| 195 | **N1 Review and JLPT N1 prep** | Mock N1; kanji review (~2,000) |

## 4.6 Beyond N1 — Mastery Polish (Weeks 196–200)

| Weeks | Focus | Notes |
|---|---|---|
| 196 | Classical Japanese (kobun) | Reading premodern texts; basic classical grammar |
| 197 | Dialects | Kansai-ben mastery; awareness of Tōhoku, Kyūshū |
| 198 | Pop culture mastery | Internet slang; meme literacy; current-events fluency |
| 199 | Final comprehensive review | Self-test all skills; identify final gaps |
| 200 | **Capstone project** | Choose: (a) 5,000-character essay, (b) 30-minute podcast in Japanese, (c) novel translation excerpt, (d) JLPT N1 official exam |

---

# PART 5 — CULTURAL ROTATION STRATEGY

Unlike Spanish (which spans 21 countries), Japanese culture is geographically concentrated but has rich internal diversity. Cultural notes rotate across:

- **Major regions** — Kantō (Tokyo area), Kansai (Osaka/Kyoto), Tōhoku, Hokkaidō, Chūbu, Kyūshū, Shikoku, Okinawa
- **Historical periods** — Heian aristocratic culture, Edo merchant culture, Meiji modernization, postwar economic miracle, Lost Decades, Reiwa era
- **Contemporary subcultures** — Otaku, kawaii, salaryman, host/hostess clubs, youth styles, urban vs. rural
- **Traditional arts** — Tea ceremony (sadō), flower arrangement (ikebana), calligraphy (shodō), Noh, Kabuki, Bunraku, Rakugo
- **Modern arts** — Manga, anime, J-cinema, J-pop, contemporary literature
- **Religious-cultural practices** — Shintō shrines, Buddhist temples, syncretism, festivals (matsuri)
- **Japanese diaspora** — Brazil (largest Japanese diaspora globally), Peru, Hawaii, U.S. West Coast
- **Aspects of daily life** — Food culture, fashion, gift-giving (omotenashi), bath culture (onsen)
- **Pain points and frank topics** — Tatemae vs. honne (public face vs. true feelings), karoshi (death from overwork), declining birthrate, otaku stigma — Japan's challenges discussed honestly at higher levels

**Lesson-generator instruction:** Cultural notes should be specific (a named place, person, era, festival, food) rather than generic "Japanese culture." Rotate to avoid Tokyo-centrism. Address modern Japan honestly, including its challenges, alongside its admirable traditions.

---

# PART 6 — RESOURCES FOR JAPANESE

## 6.1 Comprehensible Input

- **[Comprehensible Japanese](https://cijapanese.com/)** (YouTube + paid) — direct equivalent of Dreaming Spanish; primary recommendation A1–B1
- **[Nihongo con Teppei](https://nihongoconteppei.com/)** — popular podcast at multiple levels
- **[JapanesePod101](https://www.japanesepod101.com/)** — comprehensive paid platform
- **[NHK News Web Easy](https://www3.nhk.or.jp/news/easy/)** — graded news with furigana; A2–B1
- **YouTube channels:** That Japanese Man Yuta, Kaname Naito, Speak Japanese Naturally

## 6.2 Structured Courses

- **Textbook series:**
  - **Genki I & II** (most popular for self-study; covers N5–N4)
  - **Minna no Nihongo** (standard in Japanese language schools)
  - **Tobira: Gateway to Advanced Japanese** (N3–N2)
  - **Quartet** (newer; N3–N2)
- **Free online:**
  - **Tae Kim's Guide to Japanese Grammar** — concise grammar reference
  - **Tofugu** — articles and explanations
  - **Imabi** — extremely thorough advanced grammar reference
  - **Maggie Sensei** — friendly grammar explanations

## 6.3 Kanji-Specific Tools

- **[WaniKani](https://www.wanikani.com/)** (~$9/month) — best-in-class kanji learning via SRS with mnemonics; covers ~2,000 kanji in 1–2 years
- **[Anki](https://apps.ankiweb.net/)** with shared kanji decks — free alternative
- **Heisig's Remembering the Kanji** — book; learn meanings only first, then readings
- **[Jisho.org](https://jisho.org/)** — best free dictionary
- **Kanji handwriting apps** for stroke order

## 6.4 Conversation

- **[iTalki](https://www.italki.com/)** — Japanese tutors ($15–35/hr; pricier than Spanish but available)
- **[Cafetalk](https://cafetalk.com/)** — Japan-based platform with Japanese teachers
- **[HelloTalk](https://www.hellotalk.com/)** and **[Tandem](https://tandem.net/)** — language exchange (Japanese learners of English abound)
- **[Meetup](https://www.meetup.com/)** — Japanese conversation groups in many cities

## 6.5 Graded Reading

- **N5–N4:** Tadoku graded readers; NHK News Web Easy; Crystal Hunters manga (designed for learners)
- **N3:** Satori Reader (excellent with built-in dictionary), short stories aimed at learners
- **N2:** Yotsuba&! manga (easy modern Japanese); newspaper articles
- **N1+:** Murakami Haruki (accessible literary), Yoshimoto Banana, classical literature with notes

## 6.6 Native Media by Level

- **N5–N4 receptive (challenging but doable):** Shirokuma Café (anime with simple dialogue), Doraemon
- **N3:** Slice-of-life anime (Yotsuba, Aria); J-dramas with subtitles
- **N2:** Most anime and J-dramas without subtitles; variety shows
- **N1+:** News, complex dramas, classical/historical content, comedy (manzai, rakugo)

## 6.7 Music for Listening Practice

- **J-Pop:** Kenshi Yonezu (current top); Aimer; Yorushika; YOASOBI
- **Rock:** Mr. Children; ONE OK ROCK; Radwimps
- **Hip-hop:** Suchmos; Awich
- **Traditional:** Enka (演歌) — older but linguistically rich
- **Anime soundtracks:** Joe Hisaishi (Ghibli); RADWIMPS (Your Name, Weathering With You)

## 6.8 Pronunciation and Pitch Accent Tools

- **[OJAD (Online Japanese Accent Dictionary)](https://www.gavo.t.u-tokyo.ac.jp/ojad/eng)** — pitch accent for any word
- **Forvo** — native speaker recordings
- **YouTube: Dogen** — comprehensive pitch accent course
- **Shadowing**: any podcast at your level; mimic pitch and rhythm

---

# PART 7 — DAILY PRACTICE FRAMEWORK (JAPANESE-FLAVORED)

| Activity | Time | Frequency | Japanese-specific notes |
|---|---|---|---|
| **Kanji SRS** (WaniKani or Anki) | 15–25 min | Daily, non-negotiable | The single most important daily habit; missing days compounds rapidly |
| Vocab SRS (Anki) | 10–15 min | Daily | Cards from each lesson + JLPT lists |
| Comprehensible input | 15–25 min | Daily | Comprehensible Japanese primary; switch to native at N3 |
| Active output (journaling) | 10 min | Daily | Write 2–5 sentences daily in Japanese |
| Conversation with native | 30 min | 1–2× per week from Week 8 | iTalki, Cafetalk, or language partner |
| Pitch accent practice | 5 min | 3× per week | Shadowing exercises |
| Reading at level | 15 min | 4× per week | Graded readers early; native at N2 |
| Listening practice | Anytime | Daily | Podcasts, music, anime — passive okay |

**Japanese-specific habits worth adopting:**

- Switch phone language to Japanese around Week 15 (after katakana for menu items is solid)
- Watch one episode of slice-of-life anime per week with Japanese subtitles (not English)
- Read at least one manga page per day — even at N5
- Practice handwriting kanji on paper at least 2× per week (motor memory aids retention)
- At higher levels, do shadowing 5 minutes daily for pitch and rhythm

**Total daily commitment: 60–90 minutes minimum.** This is higher than Spanish for good reasons: kanji acquisition has no shortcut, listening to natural speed requires sustained exposure, and the pragmatic distance demands more cultural input. Learners who try to do Japanese on Spanish-level time investment generally fail to reach N1.

---

# PART 8 — ASSESSMENT MILESTONES

## 8.1 JLPT (日本語能力試験 — Japanese Language Proficiency Test)

The standard external assessment, administered by Japan Foundation. Five levels: N5 (easiest) to N1 (hardest). Held twice yearly (July and December) in many countries. Lifetime validity.

**Format:** Reading + Listening + Vocabulary/Grammar. Does NOT test speaking or writing.

| Level | Recommended curriculum week | Format details |
|---|---|---|
| JLPT N5 | End of Week 30 | 1h 45m; ~800 vocab, ~100 kanji |
| JLPT N4 | End of Week 60 | 2h; ~1,500 vocab, ~300 kanji |
| JLPT N3 | End of Week 110 | 2h 20m; ~3,750 vocab, ~650 kanji |
| JLPT N2 | End of Week 160 | 2h 35m; ~6,000 vocab, ~1,000 kanji |
| JLPT N1 | End of Week 195 | 2h 50m; ~10,000 vocab, ~2,000 kanji |

Exam fee varies by location: ~$50–100 USD typically.

**Caveats about JLPT:**

- Does NOT test speaking or writing. A learner can pass JLPT N1 while being unable to hold a fluent conversation.
- Pure receptive measure. The curriculum's productive practice (Speaking and Writing exercises) compensates for this — do NOT skip them.
- Heavy emphasis on reading speed, especially at N2 and N1.

## 8.2 J.TEST (Test of Practical Japanese)

Alternative test, more practical-business oriented. Held more frequently than JLPT. Some employers prefer it.

## 8.3 BJT (Business Japanese Proficiency Test)

Specifically for business Japanese. Useful if business proficiency is the goal.

## 8.4 Self-Assessment

The lesson template's self-assessment checklist applies. For Japanese, weekly self-assessment should additionally rate:

- **Kanji retention rate** — how many of recent weeks' kanji can you still recognize and read?
- **Listening at native speed** — what percentage of a natural conversation/podcast can you follow?
- **Productive register accuracy** — are you choosing polite vs. plain correctly without thinking?

---

# PART 9 — COMMON CHALLENGES FOR ENGLISH SPEAKERS

## 9.1 Kanji as an Endless Mountain

There is no shortcut. ~2,000 jōyō kanji × multiple readings each = thousands of distinct character-reading pairs to memorize. Most learners hit "kanji burnout" at some point. **Curriculum response:** parallel track from Week 5, paced sustainably (~7 new per week), with WaniKani/Anki SRS as daily anchor. Frequent low-stakes review prevents catastrophic forgetting.

## 9.2 Particles, Especially は vs が

Famously difficult. は marks topic; が marks subject. The distinction shapes everything in Japanese. Native speakers cannot fully articulate the rules. **Curriculum response:** introduced separately (Weeks 5, 8) then contrasted Week 17, then revisited continually with progressively subtler distinctions through N3.

## 9.3 SOV Word Order and Long Modifier Chains

English speakers naturally produce English-ordered Japanese ("watashi wa eats sushi"). Real Japanese also has very long pre-noun modifier chains ("the book I bought yesterday at the station") that come before the noun. Both require active restructuring practice. **Curriculum response:** sentence-building drills from Week 5; relative clauses introduced Week 25 with sustained practice.

## 9.4 The Te-Form

Forming the te-form correctly requires memorizing transformation rules for each verb subclass. Many learners avoid the work and produce mangled Japanese as a result. **Curriculum response:** dedicated Week 20 with intensive drilling; revisited in Weeks 21–23.

## 9.5 Giving and Receiving Verbs

あげる、くれる、もらう plus their te-form combinations encode social relationships in ways English has no equivalent for. The same action ("I gave my friend a book" vs. "my friend gave me a book") requires different verbs, not just different word order. **Curriculum response:** two full weeks (41–42) dedicated; revisited in keigo weeks.

## 9.6 Keigo

The honorific system is genuinely complex. Japanese natives themselves struggle with sonkeigo/kenjōgo in business contexts (entire books are written for Japanese adults entering the workforce). **Curriculum response:** introduced gradually (polite form Week 5, plain form Week 31), then dedicated multi-week treatment Weeks 61–67, then woven into every subsequent lesson.

## 9.7 Pitch Accent

Often skipped by self-learners. Wrong pitch is intelligible but unmistakably foreign. **Curriculum response:** introduced Week 1; shadowing exercises in pronunciation sections throughout; not heavily drilled in early weeks but never abandoned.

## 9.8 Listening Speed and Reduction

Native Japanese speech is fast, with extensive vowel devoicing, sentence-ending particle clusters, and dialectal reduction. Even N2 learners often understand reading far better than listening. **Curriculum response:** listening from Week 4; graded difficulty; NHK News Easy recommended through N3; native speed introduced gradually.

## 9.9 Receptive vs. Productive Asymmetry

JLPT-driven learning produces strong reading and listening with weak speaking and writing. The curriculum compensates with mandatory productive exercises every week. **Curriculum response:** Speaking and Writing exercises non-negotiable; tutoring recommended from Week 8.

## 9.10 The "Knowing What to Say" Pragmatics Wall

Many learners reach high JLPT levels but freeze in real Japanese interactions because they don't know what to say — when to apologize, how to refuse, what to say at a wake, how much to share. This isn't grammar; it's pragmatic competence. **Curriculum response:** heavy cultural-note density throughout; weekly challenges force real-world tasks; specific pragmatic instruction at N3+.

## 9.11 Cultural Burnout

Some Western learners get exhausted by perceived "social complexity" of Japanese and reach a wall around N2. **Curriculum response:** explicit framing — these features are not arbitrary obstacles but coherent systems; affective filter framing in all materials.

## 9.12 The Plateau at N3→N2

Most well-known plateau in Japanese learning. N2 introduces ~200 distinct grammar patterns and ~2,500 new vocab items. The slog is real. **Curriculum response:** N2 gets 50 weeks (the longest level) for a reason; chunked into manageable sub-themes.

---

# PART 10 — JAPANESE-SPECIFIC NOTES FOR LESSON GENERATION

Notes for the AI generating each weekly Japanese lesson, in addition to the universal pedagogical principles.

## 10.1 Lesson Template Adjustments for Japanese

The universal 12-section template applies with these adjustments:

- **Add Section 13: Kanji Focus** (after Spaced Repetition Cards) — present the week's new kanji with on-readings, kun-readings, meanings, 2–3 example compounds, and a brief mnemonic if useful. (Skip for Weeks 1–4 which have no kanji yet.)
- **Section 2 (Key Vocabulary)** — for each word, show both kana spelling and kanji spelling (if applicable), with pitch accent notation where relevant (e.g., かんじ ②, meaning pitch drops after the 2nd mora).
- **Section 3 (Grammar Focus)** — Japanese grammar is often best taught as sentence patterns rather than abstract rules. Use the pattern + example format.
- **Section 5 (Listening Exercise)** — until Week 8, listening should be at clearly slower-than-native speed; from Week 8 onward, gradually increase toward native pace.
- **Section 8 (Speaking Exercise)** — include explicit pitch accent practice for at least one item per lesson at all levels.

## 10.2 Script Conventions

- **Weeks 1–2:** Romaji acceptable for guidance, but introduce hiragana actively
- **Weeks 3–4:** Hiragana required; furigana (kana above kanji) okay
- **Weeks 5–30:** Furigana on all kanji new and unfamiliar; never romaji except for pitch accent notation
- **Weeks 31–100:** Furigana only on N3+ kanji
- **Weeks 101+:** Furigana only on N1+ or rare kanji
- **C2/Polish:** Native-like text density

## 10.3 Vocabulary Selection

- Pull from JLPT vocabulary lists at the appropriate level
- Show both kanji and kana spelling
- Include pitch accent in IPA-like notation when teachable (e.g., 「箸」 [HL] vs 「橋」 [LH])
- Mark casual vs. polite vs. formal register
- Foreign loanwords (katakana words) should be included throughout — they're a huge part of modern Japanese vocab

## 10.4 Example Sentence Composition

- Use authentic-feeling Japanese — not English-translated patterns
- Show register consistency within each example (don't mix plain and polite arbitrarily)
- Subjects often dropped where natural — don't add 私は just to mirror English
- Include particles correctly and prominently

## 10.5 Cultural Notes

- High density throughout the curriculum
- Name specific places, people, eras, festivals
- Address modern challenges honestly at higher levels (work culture, declining birthrate, regional decline, etc.) — not just traditional aesthetics
- Avoid stereotypes (no "samurai and sushi" defaults)

## 10.6 Listening Recommendations

- A1–A2 (N5): Comprehensible Japanese; Nihongo con Teppei beginner
- A2–B1 (N4–N3): NHK News Web Easy; intermediate podcasts; slice-of-life anime with subs
- B1–B2 (N3–N2): JapanesePod101 intermediate; J-dramas with Japanese subs; anime without subs
- B2+ (N2+): Native podcasts; full speed news; YouTube vlogs
- Always note approximate listening level when recommending

## 10.7 Reading Passages by Level

Write the passage yourself, calibrated to level. Mora counts (a Japanese mora ≈ one kana character) are more meaningful than word counts:

- **N5:** ~150–200 mora; present tense; high furigana density
- **N4:** ~250–350 mora; past tense; furigana on N3+ kanji
- **N3:** ~400–600 mora; varied tenses; furigana on N2+ kanji
- **N2:** ~700–1,000 mora; complex sentences; native-style register
- **N1:** ~1,200–1,800 mora; literary or specialized; minimal furigana
- **C2/Polish:** Native-like density

## 10.8 Grammar Explanations

- In English through N3 (B1); transitioning to Japanese for grammar terms at N2+
- Use the sentence-pattern format: **Pattern → Example → Translation → Explanation → Common Pitfall**
- Contrast with English where helpful, especially for particle nuance

## 10.9 Drill Variety

- Mix at least three of: particle fill-in, conjugation transformation, sentence reordering (SOV practice), translation (both directions), kanji reading, kanji writing
- Avoid pure multiple-choice except for nuance items

## 10.10 Pronunciation Section

Every lesson includes pronunciation work:

- **N5:** Pitch accent of new vocabulary; mora-timing practice
- **N4:** Sentence-level intonation; sentence-ending particle patterns (よ, ね, etc.)
- **N3+:** Shadowing exercises; dialect awareness
- **N2+:** Reduced/fast speech patterns

## 10.11 The Weekly Challenge

Should be especially concrete for Japanese given the pragmatic distance. Examples:

- N5: Order a coffee in Japanese (at a Japanese café if available, or roleplay with a tutor)
- N4: Write a self-introduction (jiko shōkai) and recite it aloud
- N3: Have a 10-minute conversation in keigo with a tutor about your week
- N2: Comment on a Japanese YouTube video in natural Japanese
- N1: Give a 5-minute presentation in Japanese on a chosen topic

---

*End of document. This is the Japanese-specific reference for the language learning project. The next deliverable would be the structured curriculum data (\`lib/curricula/japanese.ts\`) with all 200 weeks as TypeScript objects matching the schema used for Spanish.*
`;
