// Auto-generated by scripts/embed-references.ts
// Source: mandarin-curriculum-reference.md
// Do not edit by hand. Re-run the embedding script if the source changes.

export const mandarinReference = `# Mandarin Chinese Curriculum Reference

**Purpose.** This is the Mandarin-specific knowledge base for the language learning project. It applies the universal pedagogical framework (see \`pedagogy-foundations.md\`) to Mandarin Chinese: how Mandarin is characterized along the seven dimensions, why specific variety decisions were made, the full 190-week curriculum architecture aligned to HSK levels, Mandarin-specific resources and assessment paths, and notes on what English speakers find hard about Mandarin specifically.

**Companion documents.**
- \`pedagogy-foundations.md\` — Universal principles + the seven-dimensional framework
- \`spanish-curriculum-reference.md\` — Spanish-specific reference
- \`japanese-curriculum-reference.md\` — Japanese-specific reference (closest in writing-system burden)
- \`korean-curriculum-reference.md\` — Korean-specific reference (closest in pragmatic distance)
- \`claude-code-prompt.md\` — The build spec for the lesson-generator app
- This document — Mandarin-specific reference

**Mandarin compared to other curricula so far.** Mandarin's central paradox is that its grammar is genuinely simple — no verb conjugation, no noun gender, no case system, almost no inflection at all — while its phonology (tones) and writing system (characters) are among the most demanding learner investments of any major world language. The pedagogical implication is that lessons can move quickly through grammar but must move carefully through tones and characters, both of which need sustained daily attention from Week 1.

---

# PART 1 — MANDARIN CHINESE LANGUAGE PROFILE

## 1.1 Basic Facts

- **Native speakers:** ~920 million (most-spoken native language in the world)
- **Total speakers (including L2):** ~1.1 billion
- **Geographic distribution:** Mainland China (普通话 Putonghua), Taiwan (國語 Guóyǔ), Singapore (华语 Huáyǔ as one of four official languages), Malaysia (significant Chinese-Malaysian population), and worldwide Chinese diaspora communities
- **Official status:** People's Republic of China, Republic of China (Taiwan), Singapore (co-official), UN official language, WHO official language
- **ISO 639-1 code:** zh
- **Linguistic family:** Sino-Tibetan → Sinitic → Mandarin
- **Important clarification:** "Chinese" is often used informally to refer to Mandarin, but Chinese is actually a family of related languages (Mandarin, Cantonese 粵語, Shanghainese 上海話, Hokkien 閩南語, Hakka 客家話, etc.) that share a writing system but are mutually unintelligible when spoken. This curriculum is Mandarin specifically.

## 1.2 The Seven Dimensions Applied to Mandarin

### Phonology — *Tonal; the defining challenge*

Mandarin's phoneme inventory is actually manageable for English speakers. The defining feature is tone.

**The tones:**

- **First tone (mā 妈)** — high level pitch, sustained
- **Second tone (má 麻)** — rising pitch, like an English question
- **Third tone (mǎ 马)** — low dipping pitch (in isolation; modifies in connected speech)
- **Fourth tone (mà 骂)** — sharp falling pitch, like an English command
- **Neutral tone (ma 吗)** — short, light, unstressed; on grammatical particles and second syllables of compound words

Wrong tones produce wrong words. The famous example: 妈麻马骂吗 = mother, hemp, horse, scold, question particle — all spelled "ma" but distinguished by tone. Unlike Japanese pitch accent (where wrong pitch sounds foreign but is intelligible), wrong tones in Mandarin frequently break comprehension entirely.

**Tone sandhi (combination rules):**

- Two third tones together: the first becomes second tone (你好 nǐ hǎo → actually pronounced ní hǎo)
- 不 (bù) becomes bú before another fourth tone
- 一 (yī) changes based on what follows: yì before tones 1/2/3, yí before tone 4
- These rules are learned implicitly but should be explicitly taught

**Other phonological features:**

- **5 vowels** (basic) with a few diphthongs
- **About 21 consonant initials** including some unfamiliar ones:
  - The aspirated/unaspirated distinction (p/b, t/d, k/g, ch/j, ts/dz) — Chinese uses Pinyin's b/p, d/t, g/k for unaspirated/aspirated voiceless, not voiced/voiceless as in English
  - Retroflex consonants (zh, ch, sh, r) — tongue curled back; distinct from dental (z, c, s)
  - The "ü" vowel (written ü or u depending on context) — like German ü
  - The "x" sound — like sh but tongue forward, sharper
  - The "q" sound — like ch but tongue forward
- **Syllable structure is restricted** — most syllables are CV or CVC (with the C limited to n or ng); no complex consonant clusters; Mandarin has far fewer possible syllables than English (~400 unique syllables × 4-5 tones)
- **Homophones abound** — because the syllable inventory is small, many characters share pronunciation; context disambiguates

**Implication:** Tones drilled from Week 1, every single lesson, for the entire curriculum. Pinyin (the romanization system) introduced Week 1 and remains a learning tool throughout. Retroflex vs. dental consonant pairs systematically drilled in early weeks. The "ü" sound needs explicit instruction. Tone sandhi rules introduced Week 5, reinforced throughout.

### Writing System — *Logographic; the parallel mountain*

Chinese characters (汉字 hànzì) are logographic — each character represents a morpheme (usually a one-syllable unit of meaning), not a phoneme. This is structurally different from any alphabet or syllabary.

**Scale of the challenge:**

- ~3,000 characters needed for basic literacy (newspaper reading)
- ~5,000 characters for educated reading
- ~8,000 characters for full literary breadth
- Most characters have one pronunciation but some have multiple (多音字 duōyīnzì); 行 can be xíng (walk, OK) or háng (row, profession)
- Most characters are composed of meaningful sub-components (radicals 部首 and phonetic components 声旁) that can be learned systematically

**Simplified vs. Traditional:**

- **Simplified characters (简体字)** — used in Mainland China, Singapore, Malaysia, UN documents. Result of a mid-20th-century reform that reduced stroke counts and simplified shapes. ~20% of characters differ between systems.
- **Traditional characters (繁體字 / 正體字)** — used in Taiwan, Hong Kong, Macau, and most overseas Chinese communities. The historical form; more strokes; aesthetically prized by many.
- They are **largely mutually readable with effort** — once you know one system, learning the other is mostly memorization of the differing characters (a matter of weeks, not years).

**Pinyin (拼音)** — the official Romanization system using Latin alphabet with tone marks. Critical learning tool for beginners. Should be used as a pronunciation aid but **phased out as primary text by Week 8**, replaced by characters with pinyin annotations (similar to Japanese furigana over kanji).

**Implication:** This is the largest single time investment in Mandarin learning. **Character study is a parallel track** from Week 3, with ~10–15 new characters per week sustained for the entire curriculum. Daily SRS (Anki, Pleco's built-in flashcards, or Skritter for handwriting practice) is non-negotiable. Pinyin-with-characters from Week 8 onward; pinyin-only never in main lesson text after Week 2.

### Morphology — *Analytic / isolating; the great Mandarin shortcut*

Mandarin's grammatical structure is the polar opposite of fusional Spanish or agglutinative Japanese/Korean. Words are mostly invariable; grammar is encoded through word order, particles, and adverbs rather than inflection.

- **No verb conjugation** — 我吃 (I eat), 你吃 (you eat), 他吃 (he eats), 我们吃 (we eat) — all use the same form 吃 (chī, "eat")
- **No tense inflection** — time is shown through context, adverbs (昨天 yesterday, 明天 tomorrow), and aspect markers
- **Aspect particles do work tense would do in other languages:**
  - **了 (le)** — completed action / change of state (incredibly nuanced; one of the most studied particles)
  - **过 (guo)** — experiential past ("have ever done")
  - **着 (zhe)** — ongoing state / continuous
- **No grammatical gender, no case, no number on nouns** — 一本书 (one book), 五本书 (five books) — the noun 书 doesn't change
- **Measure words (量词)** — every counted noun requires a measure word: 一只猫 (one cat), 一本书 (one book), 一杯水 (one cup of water). Different measure words for different categories of objects.
- **Modular vocabulary** — many words are compounds of two single-character morphemes whose meanings combine logically: 电 (electricity) + 脑 (brain) = 电脑 (computer); 火 (fire) + 车 (vehicle) = 火车 (train)

**The deceptive simplicity:**

"No conjugation" sounds easy but the aspect particles 了, 过, 着 are subtle and famously hard to use correctly. Particle placement, fronting structures, and topic-comment patterns require active study. The lack of inflection means ambiguity is resolved by word order and particles — and those rules are precise.

**Implication:** Grammar instruction is lighter than Japanese/Korean but the focus shifts to **particle nuance, word order patterns, and measure words**. The 了 particle gets dedicated multi-week treatment (it's that important). Measure words are introduced systematically from Week 6 with periodic vocabulary additions.

### Word Order — *SVO with topic-comment overlay*

Subject-Verb-Object is the default — close to English. But Mandarin frequently uses topic-comment structure, fronting the topic to the start of the sentence:

- 我喜欢苹果 (Wǒ xǐhuan píngguǒ) — "I like apples" (SVO)
- 苹果我喜欢 (Píngguǒ wǒ xǐhuan) — "Apples, I like (them)" (topic-comment)

Other important word-order rules:

- **Time before action, place before action** — 我明天在家吃饭 (I tomorrow at-home eat) is correct; rearranging breaks the sentence
- **The 把 (bǎ) construction** — fronts the object before the verb: 我把书放在桌子上 (I take-the-book and put it on the table) — used for object-disposal actions
- **The 是...的 (shì...de) construction** — emphasizes a particular detail in a past event: 我是昨天来的 (It was YESTERDAY that I came)
- **Modifiers precede the modified noun** — like English (red car, not car red), but Mandarin builds longer modifier strings before nouns with the particle 的 (de)

**Implication:** Word order is mostly familiar (SVO base), but the 把 construction, the 是...的 construction, and topic-comment fronting are major patterns that need explicit practice. Time/place positioning rules introduced Week 9.

### Register — *Relatively simple grammatically; complex lexically*

Mandarin does not encode social relationships in verb forms the way Japanese keigo or Korean speech levels do. No conjugation = no register-encoded inflection. This is structurally simpler than Japanese or Korean.

However, register is encoded through **vocabulary choice**, not grammar:

- **Polite vocabulary** — 您 (nín, formal "you") vs. 你 (nǐ, regular "you"); 请 (qǐng, please) softens requests
- **Classical/literary register** — Modern Mandarin coexists with Classical Chinese (文言文 wényánwén), a different language used in literary, formal, and historical contexts. Educated Mandarin speech and writing borrows extensively from classical Chinese, especially via four-character idioms (成语 chéngyǔ) — thousands of them, used freely in formal and even casual speech.
- **Formality through sentence patterns** — certain patterns sound formal or literary; learning these distinguishes intermediate from advanced learners
- **Honorifics through titles** — 老师 (teacher), 先生 (Mr.), 女士 (Ms.), 教授 (Professor) — used commonly in address
- **Regional politeness norms vary** — Beijing speech can sound abrupt to Taiwanese ears; Taiwanese Mandarin uses softer particles like 啦 (la) and 哦 (ò) more frequently

**Implication:** No multi-week register deep-dive like Japanese keigo or Korean speech levels is needed. Instead, register awareness is built progressively through vocabulary and sentence-pattern choices. Chengyu (four-character idioms) gets dedicated treatment from B2 onward — they're a marker of educated Mandarin.

### Cultural-Pragmatic Distance — *Distant*

Chinese culture is one of the most distant from English-speaker norms among major world languages, with deep historical roots and rapid contemporary transformation:

- **Face culture (面子 miànzi)** — central concept; maintaining the dignity of all parties is a primary conversational goal; making someone "lose face" is a serious social violation
- **Guanxi (关系)** — networks of reciprocal obligation and relationship; doing business, navigating bureaucracy, and getting things done all depend on guanxi
- **Indirectness in confrontation** — disagreement is often communicated indirectly; "可以" (kěyǐ, "it's okay/it works") can mean "yes" or "no thanks" depending on context
- **Confucian hierarchy** — age, seniority, family position shape interactions, though less rigidly grammatically encoded than in Korean
- **Modesty norms** — accepting compliments directly is impolite; deflecting ("没有没有", "哪里哪里") is expected
- **Numerical superstitions** — 4 (sounds like "death") avoided; 8 (sounds like "prosperity") prized; affects phone numbers, addresses, prices
- **Food culture as social ritual** — meals are communal, family-style; refusing food can be impolite; banqueting culture is central in business
- **Modern China is changing fast** — first-tier city culture differs enormously from rural China; younger generations diverge from older norms; cultural references date quickly
- **Sensitive topics exist** — political topics (Taiwan, Hong Kong, Xinjiang, Tibet, historical events) require neutral handling; cultural notes should not endorse any political position

**Implication:** High cultural-note density. Modern dynamism honored alongside traditional depth. Sensitive topics handled neutrally and matter-of-factly when they appear. Note when cultural patterns differ between Mainland and Taiwan/Singapore.

### Resource Availability — *Major language; massive resource base*

Chinese has the largest learner community of any non-Western language, supported by both Chinese government investment and international demand:

- **Free YouTube content** — Mandarin Blueprint, Mandarin Corner, ChinesePod, Yoyo Chinese
- **Apps** — Pleco (the standard dictionary), Skritter (character writing), Du Chinese (graded readers), HelloChinese (gamified beginner)
- **Textbook series** — Integrated Chinese (most popular university series in US), New Practical Chinese Reader, HSK Standard Course
- **Native media** — C-dramas, films, music, news, and a vast literary tradition spanning thousands of years
- **Tutoring** — iTalki and italki have enormous Chinese tutor presence; rates competitive ($8–25/hr); also italki Cafe and Preply, plus Mainland-based platforms
- **Language partners** — abundant Chinese learners of English on Tandem, HelloTalk
- **In-China options** — Confucius Institutes worldwide; Mainland universities offer year-long intensive programs at very competitive prices

**Implication:** Specific high-quality recommendations available at every level. Pleco is essentially required (the standard reference dictionary app). The character-learning ecosystem (Skritter, Anki shared decks) is exceptionally well developed.

---

# PART 2 — VARIETY DECISION

## 2.1 The Decision

**Mandarin Putonghua (普通话)**, the Beijing-based standard used in Mainland China, as the spoken variety. **Simplified characters (简体字)** as the writing system. Exposure to **Traditional characters (繁體字)** and **Taiwanese Mandarin (國語)** as receptive content at advanced levels (Weeks 150+).

## 2.2 Rationale

- **Mainland standard is the most widely taught** — the majority of Mandarin learners and resources globally use Putonghua + simplified
- **Most Mandarin speakers worldwide use simplified** — 1.3+ billion people; resources skew dramatically in this direction
- **Inter-readable system** — once Mandarin is solid, switching to traditional is a matter of learning the ~20% of characters that differ, plus a few vocabulary variations. Not learning a new language.
- **The differences between Mainland and Taiwanese Mandarin are real but bounded** — different vocabulary in some domains (e.g., 软件/軟體 for "software"), different sentence-ending particle preferences, slight pronunciation differences. Mutually intelligible by huge margin.

## 2.3 What This Decision Excludes (and How They're Treated)

**Cantonese (粵語 / 廣東話)** is a separate language, not a Mandarin dialect. Mutually unintelligible with Mandarin when spoken (despite sharing the writing system). Spoken in Hong Kong, Macau, Guangdong Province, and overseas Chinese communities. Important for some learners (Hong Kong residents, HK cinema fans) but not included in this curriculum. Treated as a separate language to learn separately if interested.

**Other Chinese languages** (Shanghainese, Hokkien, Hakka, etc.) — same logic. Separate languages within the Sinitic family.

**Classical Chinese (文言文)** — the historical literary language. Brief exposure at C2 level (Week 188) for cultural enrichment; not a primary focus. Heavily borrowed from in modern formal writing via chengyu and literary phrases.

## 2.4 Taiwan-Specific Considerations

Learners specifically interested in Taiwan should still start with this curriculum (which is Putonghua/simplified-based) but plan to:
- Switch to traditional characters around Level 3 (Week 60+)
- Add Taiwanese Mandarin vocabulary lists (台灣國語常用詞)
- Expose to Taiwan-produced media (台灣偶像劇, etc.)
- Note pronunciation differences (Taiwanese Mandarin tends to be softer; fewer retroflex consonants; different neutral tone usage)

The curriculum can be adapted in roughly 5–10 weeks of dedicated effort to shift from Mainland to Taiwan focus at any post-Level-3 point.

---

# PART 3 — CURRICULUM ARCHITECTURE

## 3.1 At a Glance

- **Total length:** 190 weeks (~3.6 years at one lesson per week)
- **Pacing:** one lesson per week plus daily practice (60–90 min/day recommended — similar to Japanese, both for the character mountain and ongoing tone work)
- **Total study time at recommended pace:** ~1,700–2,100 hours, approaching FSI's Category IV estimate
- **Level structure:** Six main levels aligned to old HSK 1–6 (the more familiar system), with HSK 7–9 (the new reform) treated as the mastery polish at the end

## 3.2 The Six Levels

| Level | Weeks | Span | Goal | CEFR Equiv | Characters (cumulative) | Vocab (cumulative) |
|---|---|---|---|---|---|---|
| Level 1 — Foundations | 1–30 | 30 weeks | HSK 1–2 | A1 to lower A2 | ~600 | ~1,200 |
| Level 2 — Elementary | 31–60 | 30 weeks | HSK 3 | A2 to lower B1 | ~900 | ~2,200 |
| Level 3 — Intermediate | 61–110 | 50 weeks | HSK 4 | B1 to lower B2 | ~1,200 | ~3,200 |
| Level 4 — Upper-Intermediate | 111–150 | 40 weeks | HSK 5 | B2 | ~1,500 | ~4,500 |
| Level 5 — Advanced | 151–180 | 30 weeks | HSK 6 | C1 | ~2,500 | ~6,000 |
| Level 6 — Mastery | 181–190 | 10 weeks | HSK 7–9 | C1+/C2 | ~3,000+ | ~9,000+ |

**Note on HSK structure.** The HSK was reformed in 2021 to a 9-level system (HSK 3.0). The older HSK 1–6 system remains widely recognized. This curriculum uses old HSK 1–6 as the level milestones (more familiar to most learners and resources) with HSK 7–9 as the mastery extension. New HSK levels are slightly more demanding than old HSK at equivalent numbers (e.g., new HSK 6 ≈ old HSK 6 + extra characters).

**Receptive vs. productive asymmetry.** HSK tests reading and listening; older HSK 6 has a writing component but no speaking. Like JLPT, learners can pass HSK without conversational fluency. **The curriculum's mandatory speaking and writing exercises every week** are essential to compensate.

## 3.3 Pacing Philosophy

- **Level 1 (Weeks 1–30):** Pinyin and tones intensively Weeks 1–2. Character introduction from Week 3. Tone sandhi rules Week 5. Measure words from Week 6. Aspect particle 了 introduced Week 18. By Week 30: HSK 1–2 readiness, ~600 characters.
- **Level 2 (Weeks 31–60):** Aspect particles deep-dive (了 / 过 / 着) Weeks 31–35. 把 construction Week 40. 是...的 construction Week 42. Resultative complements introduced. Reading native-aimed content begins.
- **Level 3 (Weeks 61–110):** The longest level — HSK 4 introduces ~600 new grammar patterns and ~2,000 new vocabulary items. Where most learners hit the wall. Curriculum slows down deliberately. Chengyu introduced systematically from Week 80.
- **Level 4 (Weeks 111–150):** HSK 5 grammar; literary register; native media consumption shifts from beginner-aimed to genuine native (news, C-dramas, films).
- **Level 5 (Weeks 151–180):** HSK 6 grammar patterns (~600 more); classical influence on modern formal Chinese; specialized fields (business, legal, medical).
- **Level 6 (Weeks 181–190):** Classical Chinese exposure; advanced chengyu; dialect awareness (brief); capstone.

## 3.4 The Character Parallel Track

Like Japanese kanji, Mandarin character study runs parallel to language study throughout the curriculum. Target pacing:

| Phase | Weeks | New Characters per Week | Cumulative |
|---|---|---|---|
| Foundations | 3–30 | ~15 new + reinforcement | ~600 by Week 30 |
| Elementary | 31–60 | ~10 new + reinforcement | ~900 by Week 60 |
| Intermediate | 61–110 | ~6 new + reinforcement | ~1,200 by Week 110 |
| Upper-Intermediate | 111–150 | ~8 new + reinforcement | ~1,500 by Week 150 |
| Advanced | 151–180 | ~30 new + reinforcement | ~2,500 by Week 180 |
| Mastery | 181–190 | ~50+ new + reinforcement | ~3,000+ by Week 190 |

(Weeks 1–2 have no new characters — those weeks are pinyin and tone foundation only.)

**Each lesson from Week 3 onward includes a Character Section** with the week's new characters: simplified form (+ traditional in parentheses where they differ), pinyin with tone, meaning, key compound words, radical breakdown, stroke order recommendation. Daily SRS review (Anki, Pleco, or Skritter) is required. Handwriting practice with stroke order is recommended at least 2x per week for early levels.

## 3.5 The Tone Parallel Track

Unlike characters (which front-load and then sustain), tones need **continuous attention** at every level. Every lesson includes a Tone Focus mini-section:

- **Foundations:** Tone identification, production, and basic combinations
- **Elementary:** Tone sandhi rules in connected speech; tone drift errors
- **Intermediate:** Sentence-level prosody; tone in fast speech
- **Upper-Intermediate and beyond:** Tone in regional accents; tone in colloquial reductions; tone errors that have fossilized

Plateau learners frequently develop fossilized tone errors (wrong tone learned for a specific word) that become hard to fix later. Continuous low-stakes correction in every lesson is the prevention.

---

# PART 4 — WEEK-BY-WEEK OVERVIEW

The full structured data will live in \`lib/curricula/mandarin.ts\` (to be built). Early weeks detailed; later weeks grouped.

## 4.1 Level 1 — Foundations (Weeks 1–30)

| W | Title | Core focus |
|---|---|---|
| 1 | **Pinyin Part 1 + Tones** | Vowels and basic initials; the four tones in isolation; minimal-pair listening drills |
| 2 | **Pinyin Part 2 + Tone Sandhi** | Retroflex vs. dental consonants; aspirated vs. unaspirated; tone sandhi (3rd+3rd, 不, 一); reading pinyin fluently |
| 3 | **First characters** | 你 我 他 是 不 的 — high-frequency characters; introductions in pinyin + characters |
| 4 | Greetings, self-introduction | 你好, 我叫..., 我是...人; basic introduction phrases; first 15 characters |
| 5 | Yes/no questions; question particle 吗 | 你是学生吗?; subject-verb structure |
| 6 | **Measure words intro** | The concept; 一个, 一本, 一只; numbers 1–10 |
| 7 | Numbers, ages, dates | Sino-numbers up to 1000; 多少 vs. 几 |
| 8 | Time expressions | 现在, 今天, 明天, 昨天; telling time |
| 9 | **Word order rules** | Time before action; place between subject and verb; building basic sentences |
| 10 | Family vocabulary | 爸爸 妈妈 哥哥 姐姐 etc.; 有 (have) constructions |
| 11 | Locations and prepositions | 在 (at); 上 下 里 外 (on/under/inside/outside); 这儿 那儿 |
| 12 | Common verbs and objects | 吃 喝 看 听 学习 工作; building VO sentences |
| 13 | Likes and dislikes | 喜欢 / 不喜欢; preferences |
| 14 | Adjectives | Predicate adjectives (no 是); 很; comparative 比 introduction |
| 15 | More adjectives; degree | 太...了, 真, 非常, 特别; intensifiers |
| 16 | Negation | 不 vs. 没; when each is used |
| 17 | Demonstratives + measure words | 这本书, 那只猫, 这些, 那些 |
| 18 | **Aspect particle 了 — Part 1** | Completed action; sentence-final 了; introduction only |
| 19 | Direction and movement | 来 去; directional complements 上来, 下去, 出来 |
| 20 | Modal verbs | 会, 能, 可以 — the three "can" verbs and their distinctions |
| 21 | Modal verbs continued | 要, 想, 应该; want, should |
| 22 | Asking for and giving information | Question words 什么 谁 哪儿 怎么 为什么 |
| 23 | Daily routines | Morning to night vocabulary; time + action |
| 24 | Food and ordering | At a restaurant; 一份, 一碗, 一杯 |
| 25 | Shopping and money | 多少钱; 块, 毛, 分; bargaining basics |
| 26 | Transportation | 坐 (by), 骑 (ride); 公共汽车, 地铁, 出租车 |
| 27 | Weather and seasons | Weather expressions; seasonal vocabulary |
| 28 | Health and body | Body parts; common ailments; pharmacy basics |
| 29 | Travel basics | Hotel, airport, asking directions |
| 30 | **Level 1 Review and HSK 1–2 prep** | Mock HSK 2; ~600 characters; all four skills |

## 4.2 Level 2 — Elementary (Weeks 31–60)

| W | Title | Core focus |
|---|---|---|
| 31 | **Aspect particle 了 — Part 2** | Verb-suffix 了 vs. sentence-final 了; common confusions |
| 32 | **Aspect particle 了 — Part 3** | Change of state; the "1+1=2" combined uses |
| 33 | **Aspect particle 过** | Experiential past; "have you ever..." |
| 34 | **Aspect particle 着** | Ongoing state; manner of action; 一边 X 一边 Y |
| 35 | Continuous action | 在 + verb; 正在 + verb; 呢 sentence ending |
| 36 | Reduplicated verbs | Short, casual aspect: 看看, 试试, 想一想 |
| 37 | Resultative complements | 看见, 听见, 学好, 吃完; verb + result |
| 38 | More resultative complements | Common pairs; productive uses |
| 39 | Directional complements | 进来, 出去, 回来, 上去; literal and metaphorical |
| 40 | **The 把 (bǎ) construction** | Object-fronting for disposal; when to use |
| 41 | More 把 construction | Common patterns; pitfalls |
| 42 | **The 是...的 (shì...de) construction** | Emphasis on time, place, manner of past events |
| 43 | Comparison patterns | 比, 没有, 一样, 跟...一样, 比较 |
| 44 | Approximate quantities | 多, 左右, 大概, 大约 |
| 45 | Conjunctions and connectors | 因为...所以, 虽然...但是, 不但...而且 |
| 46 | Conditionals | 如果, 要是, 的话 |
| 47 | More conditionals | 只要...就, 只有...才; necessary vs. sufficient conditions |
| 48 | Time clauses | 的时候, ...以前, ...以后 |
| 49 | Causative and request structures | 让 (let/make), 叫, 请, 使 |
| 50 | Passive voice | 被 (bèi); when used in Chinese (less common than English passive) |
| 51 | Workplace vocabulary | Office; meetings; job interviews |
| 52 | School and education | School system; subjects; exam culture |
| 53 | Travel within China | Geography, major cities, transportation |
| 54 | Communication | Phone manner; email and texting (微信 WeChat dominant) |
| 55 | Internet and social media | 微信, 微博, 抖音; modern vocabulary |
| 56 | Banking and paperwork | Forms; ID; basic transactions; ATM vocabulary |
| 57 | Health and medical | More medical vocabulary; doctor's office; traditional Chinese medicine (中医) |
| 58 | Shopping and consumer life | Markets, malls, Taobao; modern shopping |
| 59 | Food deeper | Regional cuisines; dim sum; hot pot; tea culture |
| 60 | **Level 2 Review and HSK 3 prep** | Mock HSK 3; ~900 characters |

## 4.3 Level 3 — Intermediate (Weeks 61–110)

| Weeks | Focus | Notes |
|---|---|---|
| 61–65 | Advanced grammar patterns Part 1 | 越来越, 越...越, 一...就, 一边...一边, 又...又 |
| 66–70 | Advanced grammar patterns Part 2 | 不是...而是, 与其...不如, 既然...就, 即使...也 |
| 71–75 | Complex modifiers and 的 | Long 的-clauses; restrictive vs. non-restrictive modification |
| 76–80 | **Chengyu (四字成语) introduction** | Four-character idioms; first 50 most useful; structure and origins |
| 81–85 | Chinese history overview | Major dynasties; Three Kingdoms; Tang & Song high points; Ming-Qing; Republic; modern era (sensitively) |
| 86–90 | Traditional culture | Confucianism, Daoism, Buddhism; ancestor veneration; Chinese New Year; Mid-Autumn Festival; etc. |
| 91–95 | Contemporary culture | First-tier vs. rural China; tech (BAT companies); social media culture; generational gaps |
| 96–100 | Reading native content | Du Chinese intermediate; short essays; modern Chinese authors (鲁迅 in simple selections) |
| 101–105 | Listening at level | C-drama; Slow Chinese podcast; mainland vs. Taiwan accents |
| 106–110 | **HSK 4 prep and review** | Mock HSK 4; intermediate-level grammar review |

## 4.4 Level 4 — Upper-Intermediate (Weeks 111–150)

| Weeks | Focus | Notes |
|---|---|---|
| 111–120 | HSK 5 grammar patterns | ~100 distinct patterns; many use literary or formal register |
| 121–125 | Chengyu deeper | Next 100 useful chengyu; productive use in writing and speech |
| 126–130 | Chinese literature | Modern short stories: 鲁迅 Lu Xun, 莫言 Mo Yan (accessible excerpts), 余华 Yu Hua |
| 131–135 | News and current events | Newspaper Chinese; broadcast register; political vocabulary (neutral framing) |
| 136–140 | Business Chinese | Negotiations, meetings, business correspondence; guanxi vocabulary |
| 141–145 | Specialized vocabulary | Choose 2 fields: medical, legal, IT, finance, academic |
| 146–149 | HSK 5 grammar review | Pattern-by-pattern review and practice |
| 150 | **HSK 5 prep and mock exam** | Full HSK 5 mock; ~1,500 characters |

## 4.5 Level 5 — Advanced (Weeks 151–180)

| Weeks | Focus | Notes |
|---|---|---|
| 151–160 | HSK 6 grammar patterns | Subtle distinctions between near-synonyms; literary patterns; formal register |
| 161–165 | Literature deepening | Full short novels; poetry (Tang poetry introduction); criticism vocabulary |
| 166–170 | Classical influences on modern Chinese | Recognizing classical structures in modern formal writing; common borrowings |
| 171–175 | Professional Chinese deepening | Specialized field reading; conference Chinese; academic Chinese |
| 176–179 | Rhetoric and persuasion | Speech preparation; debate; argument structures |
| 180 | **HSK 6 prep and mock exam** | Full HSK 6 mock; ~2,500 characters |

## 4.6 Level 6 — Mastery (Weeks 181–190)

| Weeks | Focus | Notes |
|---|---|---|
| 181–183 | **HSK 7–9 advanced patterns** | The most advanced grammar patterns; near-native subtle distinctions |
| 184–185 | **Traditional characters mastery** | Systematic exposure to the ~20% of characters that differ; reading Taiwan/HK content |
| 186–187 | Classical Chinese (文言文) introduction | Reading premodern texts; understanding sageuk-equivalent (古装剧) dialogue |
| 188 | Regional varieties awareness | Brief survey of Cantonese, Shanghainese, Hokkien (receptive awareness only); Mandarin regional accents |
| 189 | Final comprehensive review | Self-test all skills; identify final gaps |
| 190 | **Capstone project** | Choose: (a) 5,000-character essay in Chinese, (b) 30-minute podcast in Chinese, (c) take official HSK 6 or HSK 7–9, (d) literary translation excerpt |

---

# PART 5 — CULTURAL ROTATION STRATEGY

Chinese culture is geographically and historically vast. Cultural notes rotate across:

- **Regions of China** — Beijing, Shanghai, Guangdong (Cantonese-speaking but worth knowing), Sichuan, Yunnan, Xi'an (historical capital), Northeast (Dongbei), Tibet (sensitively), Xinjiang (sensitively), Inner Mongolia
- **Taiwan and Hong Kong** — distinct cultural ecosystems; cinema, music, literature; political situation handled neutrally
- **Historical periods** — Bronze Age, Spring & Autumn / Warring States, Han, Tang (golden age), Song, Yuan, Ming, Qing, Republic (1912–1949), People's Republic, Reform era (1978–), contemporary
- **Traditional culture** — Confucianism, Daoism, Buddhism (Chinese forms); calligraphy, painting, traditional opera, tea ceremony, traditional medicine, kung fu / martial arts traditions
- **Modern arts** — C-dramas, films (Zhang Yimou, Chen Kaige, Jia Zhangke; Hong Kong: Wong Kar-wai, Stephen Chow; Taiwan: Hou Hsiao-hsien, Ang Lee), C-pop, contemporary literature
- **Festivals** — Chinese New Year (Spring Festival), Mid-Autumn Festival, Dragon Boat Festival, Qingming Festival, Lantern Festival
- **Food culture** — eight regional cuisines (八大菜系); tea culture; banquet etiquette; street food
- **Chinese diaspora** — Singapore, Malaysia, Indonesia, Thailand, Vietnam, US, Canada, Australia; overseas Chinese communities and their distinct sub-cultures
- **Modern challenges and dynamism** — urbanization, generational change, tech sector, environmental issues, gender dynamics, declining birth rate — discussed honestly at higher levels
- **Sensitive topics** — Cultural Revolution, Tiananmen, Taiwan status, Hong Kong, Xinjiang, Tibet — handled neutrally and factually, neither endorsing nor demonizing any political position; learners should be aware these topics exist and are discussed differently in Mainland vs. Taiwan vs. Western contexts

**Lesson-generator instruction:** Cultural notes should be specific (named places, people, eras, dishes, festivals). Rotate to avoid Beijing-centrism — represent the cultural geography of the Chinese-speaking world. Address modern dynamism alongside traditional depth. Handle politically sensitive topics neutrally and factually when they appear, neither endorsing nor demonizing any position; the curriculum's role is to enable communication, not to take political sides.

---

# PART 6 — RESOURCES FOR MANDARIN

## 6.1 Comprehensible Input

- **Mandarin Blueprint** (YouTube + paid) — comprehensive method-based approach; primary recommendation A1–B1
- **Mandarin Corner** (YouTube) — natural Chinese conversations with subtitles at multiple levels
- **ChinesePod** — long-running podcast with structured lessons at every level
- **Slow Chinese** (慢速中文) — podcasts at slower speed; A2–B1
- **Yoyo Chinese** — beginner-friendly video courses

## 6.2 Structured Courses

- **Textbook series:**
  - **Integrated Chinese** (most popular in US universities; covers HSK 1–4)
  - **New Practical Chinese Reader** (alternative; widely used)
  - **HSK Standard Course** (officially aligned to HSK; uses simplified)
- **Free online:**
  - **AllSet Learning Chinese Grammar Wiki** — exceptional grammar reference, organized by HSK level
  - **Hacking Chinese** — strategy and learning-method articles
  - **East Asia Student** — character and grammar resources

## 6.3 Character and Vocabulary Tools

- **[Pleco](https://www.pleco.com/)** — the standard Chinese dictionary app; essential for every learner. Free version is excellent; paid add-ons unlock OCR, handwriting input, flashcards
- **[Skritter](https://skritter.com/)** — character writing practice with SRS; recommended for retaining handwriting ability
- **[Du Chinese](https://www.duchinese.net/)** — graded reading app with built-in dictionary
- **[Anki](https://apps.ankiweb.net/)** with HSK shared decks — free SRS
- **[The Chairman's Bao](https://www.thechairmansbao.com/)** — graded news with built-in dictionary

## 6.4 Tutoring

- **[iTalki](https://www.italki.com/)** — abundant Mandarin tutors at competitive rates
- **[Preply](https://preply.com/)** — similar
- **[italki Cafe](https://www.italki.com/)** — informal language exchange
- **In-China options** — many universities offer year-long intensive programs at very competitive prices (~$3,000–8,000/year for tuition); Confucius Institutes worldwide

## 6.5 Reading Practice by Level

- **HSK 1–2:** Du Chinese beginner; Mandarin Companion graded readers
- **HSK 3:** Du Chinese intermediate; Sinolingua graded readers
- **HSK 4:** The Chairman's Bao; short essays
- **HSK 5+:** native articles from People's Daily, BBC Chinese (BBC中文), South China Morning Post Chinese; modern fiction
- **HSK 6+:** native literature — 余华 (Yu Hua), 莫言 (Mo Yan), 阎连科 (Yan Lianke), classical poetry with notes

## 6.6 C-Drama, C-Movie, and Variety Shows by Level

Watch with **Chinese subtitles** when available. Most C-dramas natively include Chinese subtitles (Mainland production convention).

- **Beginner (Level 1–2):** Limited options at this level; better to use learner-aimed content
- **Intermediate (Level 3):** Slice-of-life and youth dramas with clearer dialogue
- **Upper-intermediate (Level 4):** Mainstream C-dramas; mainland Chinese family dramas; Taiwanese dramas
- **Advanced (Level 5+):** Films by Zhang Yimou (《英雄》Hero, 《活着》To Live), Wong Kar-wai (《花樣年華》In the Mood for Love — Cantonese but cultural staple), Jia Zhangke; historical dramas (古装剧); art films

## 6.7 Music for Listening Practice

- **C-pop:** Jay Chou (周杰伦) — defines a generation; Mayday (五月天), JJ Lin (林俊杰), Eason Chan (陈奕迅)
- **Folk/Indie:** Faye Wong (王菲), Tanya Chua (蔡健雅), Eve Ai (艾怡良)
- **Classic Chinese music:** Teresa Teng (邓丽君) — slower, clearer enunciation; excellent for listening practice
- **Hip-hop:** Higher Brothers, Vava (post-Rap of China era)
- **Lyrics analysis:** Many fan sites provide Chinese lyrics with English translations

## 6.8 Pronunciation and Tone Tools

- **Pleco audio** — every dictionary entry has native pronunciation
- **Forvo** — native speaker recordings
- **YouTube: Mandarin Blueprint pronunciation series**
- **Tone trainer apps** — Yoyo Chinese has good tone training tools
- **Shadowing:** any Slow Chinese episode or ChinesePod lesson; repeat aloud immediately after the speaker

---

# PART 7 — DAILY PRACTICE FRAMEWORK (MANDARIN-FLAVORED)

| Activity | Time | Frequency | Mandarin-specific notes |
|---|---|---|---|
| **Character SRS** (Anki / Pleco / Skritter) | 15–25 min | Daily, non-negotiable | The single most important daily habit; missing days compounds rapidly |
| **Tone practice** | 5 min | Daily | Listen + repeat; shadowing helps; never let tones slip |
| Vocab SRS | 10 min | Daily | Cards from each lesson + HSK lists |
| Comprehensible input | 15–25 min | Daily | Mandarin Blueprint, Mandarin Corner; switch to native at intermediate |
| Active output (journaling) | 10 min | Daily | Write 2–5 sentences daily in Chinese characters |
| Conversation with native | 30 min | 1–2× per week from Week 8 | iTalki tutor or Tandem partner |
| Reading at level | 15 min | 4× per week | Du Chinese early; native at HSK 5+ |
| Listening practice | Anytime | Daily | Podcasts, music, C-dramas — passive okay |

**Mandarin-specific habits worth adopting:**

- Switch phone language to Chinese around Week 25 (after enough character literacy)
- Use Pleco daily — point-tap dictionary access transforms reading practice
- Practice handwriting at least 2× per week through Level 3 (motor memory aids retention; some level of handwriting ability matters)
- Watch one C-drama episode per week with Chinese subtitles from Week 30+
- Use WeChat if you have any Chinese contacts or language partners
- Listen to one Chinese podcast or song daily for tone exposure
- Read aloud daily even at beginner levels — Chinese is a particularly auditory language

**Total daily commitment: 60–90 minutes minimum.** Similar to Japanese, for similar reasons: character study has no shortcut, and tone maintenance requires daily exposure. Trying to do Mandarin on Spanish-level time investment is the most common failure pattern.

---

# PART 8 — ASSESSMENT MILESTONES

## 8.1 HSK (汉语水平考试 — Hànyǔ Shuǐpíng Kǎoshì)

The official Chinese government proficiency test. Held multiple times yearly worldwide. Old HSK (6 levels) and new HSK 3.0 (9 levels) both currently exist; old HSK is more widely recognized; new HSK is the official future direction.

**Format:** Listening + Reading + Writing (writing only for HSK 4+; speaking is a separate optional component HSKK).

| Level | Curriculum week | Format |
|---|---|---|
| HSK 1 | Week 15 | Beginner; ~150 vocab |
| HSK 2 | Week 30 | Beginner-elementary; ~300 vocab |
| HSK 3 | Week 60 | Elementary; ~600 vocab; writing included |
| HSK 4 | Week 110 | Intermediate; ~1,200 vocab |
| HSK 5 | Week 150 | Upper-intermediate; ~2,500 vocab |
| HSK 6 | Week 180 | Advanced; ~5,000 vocab |
| HSK 7–9 | Week 190 | New 9-level reform; ~11,000 vocab |

Exam fees vary by country and level: ~$25–150 USD.

**HSKK (HSK Speaking Test)** — separate optional component testing oral proficiency. Highly recommended for learners who want a complete proficiency record, since HSK alone is heavily receptive. Three levels (Elementary, Intermediate, Advanced).

**Caveats:**

- HSK has been criticized for being too receptive — readers can pass higher levels without conversational fluency. The curriculum's mandatory speaking exercises and HSKK option compensate.
- New HSK 3.0 (2021 reform) is slightly more demanding than old HSK at equivalent numbers.
- HSK 6 is impressive but not the ceiling — new HSK 9 is the new ceiling.

## 8.2 TOCFL (華語文能力測驗)

Taiwan's equivalent of HSK, uses traditional characters. Six levels. Recognized worldwide. If your goal is Taiwan or you prefer traditional characters, TOCFL may be more relevant than HSK.

## 8.3 Self-Assessment

The lesson template's self-assessment checklist applies. For Mandarin, additionally rate weekly:

- **Tone accuracy** — does someone correct your tones in conversation? How often?
- **Character retention** — what percentage of recent weeks' characters can you still recognize and read?
- **Listening at native speed** — what percentage of a C-drama scene can you follow?
- **Measure word accuracy** — are you using the right measure word for each noun category without thinking?

---

# PART 9 — COMMON CHALLENGES FOR ENGLISH SPEAKERS

## 9.1 Tones — The Foundational Challenge

Tones are the most-discussed challenge of Mandarin and the most often underestimated. Wrong tones produce wrong words. English speakers initially can barely hear tone differences; production lags hearing by months. **Curriculum response:** drilled Week 1; minimal-pair work Weeks 1–8; continuous attention in every subsequent lesson. Plateau learners who skipped early tone work often have to redo it.

## 9.2 The Character Mountain

~3,000 characters for basic literacy. No shortcut. Most learners hit "character burnout" at some point. **Curriculum response:** parallel track from Week 3, paced sustainably, with Pleco/Anki/Skritter as daily anchor. The early weeks deliberately introduce high-frequency characters first (so basic reading becomes possible quickly).

## 9.3 Aspect Particles (了 / 过 / 着)

The famous trinity of Mandarin grammar difficulty. Nuanced uses; native speakers can't always articulate the rules. 了 alone is studied across multiple distinct functions. **Curriculum response:** 了 introduced Week 18, deepened Weeks 31–32; 过 and 着 each get dedicated weeks; contrasted throughout intermediate level.

## 9.4 Measure Words

Every counted noun needs a measure word, and there are dozens of measure words categorized by object type. 一只 for animals, 一本 for books, 一张 for flat things, 一辆 for vehicles, 一杯 for drinks, etc. Learners default to 个 (the general measure word) and sound non-native. **Curriculum response:** measure words introduced Week 6; new measure words added as vocab introduces new noun categories.

## 9.5 The 把 (bǎ) Construction

Fronts the object before the verb for "object disposal" actions. Has no English equivalent. Even intermediate learners avoid it. **Curriculum response:** introduced Week 40; intensive practice; revisited.

## 9.6 The 的 / 地 / 得 Trio

Three particles all pronounced "de" but used differently:
- 的 (de) — possessive / modifying noun: 我的书 (my book)
- 地 (de) — modifying verb adverbially: 慢慢地走 (walks slowly)
- 得 (de) — complement of degree/result: 跑得很快 (runs very fast)

Native speakers themselves sometimes mix these in casual writing. **Curriculum response:** introduced incrementally; explicit comparison in Level 2.

## 9.7 Topic-Comment Structure

Mandarin allows (and often prefers) fronting the topic: 这本书我看过 ("This book, I've read it"). English speakers default to strict SVO and sound less natural. **Curriculum response:** introduced from Week 9; emphasized in reading and listening; production from Week 30.

## 9.8 Listening Speed and Reduction

Spoken Mandarin is fast, with extensive reduction (neutral tones, syllable shortening, contraction). Even HSK 5 learners often understand reading far better than listening. **Curriculum response:** listening starts Week 4; graded difficulty; Slow Chinese podcast through Level 3; native speed gradually.

## 9.9 Homophones and Context Dependence

Mandarin's small syllable inventory means many characters share pronunciation. Listening depends heavily on context. **Curriculum response:** explicit homophone awareness from Level 2; chengyu practice helps because four-character idioms are essentially homophone-resistant chunks.

## 9.10 The Plateau at HSK 3→4

Most-discussed plateau in Chinese learning. HSK 4 introduces ~600 new grammar patterns and ~1,200 new characters. The slog is real. **Curriculum response:** Level 3 gets 50 weeks (the longest level) for this reason; chunked into manageable sub-themes.

## 9.11 Productive Asymmetry

HSK rewards receptive skill; speaking and writing lag. The curriculum's mandatory productive exercises and HSKK preparation compensate. **Curriculum response:** speaking and writing exercises every week; tutoring recommended from Week 8.

## 9.12 Cultural Pragmatic Wall

Higher-level learners often plateau because they don't know what to say — when to refuse food politely, how to navigate guanxi, how much modesty is expected. **Curriculum response:** heavy cultural-note density throughout; explicit pragmatic instruction at intermediate+.

## 9.13 Chengyu — The Marker of Educated Speech

Four-character idioms (成语) appear constantly in formal speech and writing. Not knowing them marks the speaker as basic. There are thousands. **Curriculum response:** systematic introduction from Week 80; most useful 100 by Level 4; ongoing accumulation through C2.

## 9.14 Simplified vs. Traditional Confusion

Learners committed to simplified can struggle when they encounter traditional content (Hong Kong news, Taiwan dramas, calligraphy, classical texts). **Curriculum response:** primarily simplified; explicit traditional exposure from Week 150; mastery-level switching ability Week 184.

---

# PART 10 — MANDARIN-SPECIFIC NOTES FOR LESSON GENERATION

Notes for the AI generating each weekly Mandarin lesson, in addition to the universal pedagogical principles.

## 10.1 Lesson Template Adjustments for Mandarin

The universal 12-section template applies with these adjustments:

- **Add Section 13: Character Focus** (after Spaced Repetition Cards) — present the week's new characters with: simplified form (+ traditional in parentheses where different), pinyin with tone marks, meaning, key compound words, radical breakdown, stroke order. (Skip for Weeks 1–2 which are pinyin/tone only.)
- **Add Section 14: Tone Focus** (after Character Focus) — every lesson, even at advanced levels. Practice items: minimal pairs from this week's vocab; tone sandhi instances; sentence-level prosody.
- **Section 2 (Key Vocabulary)** — for each word, show characters (simplified) + pinyin with tone marks + English meaning + example sentence. Include measure words alongside countable nouns where relevant.
- **Section 3 (Grammar Focus)** — Mandarin grammar is best taught as sentence patterns. Use the pattern + example format.
- **Section 5 (Listening Exercise)** — until Week 10, listening should be slow-paced (Slow Chinese or learner-aimed); from Week 10 onward, gradually increase toward native pace.
- **Section 8 (Speaking Exercise)** — include explicit tone practice in every lesson at all levels.

## 10.2 Script Conventions

- **Weeks 1–2:** Pinyin primary, no characters yet
- **Weeks 3–8:** Characters introduced; pinyin annotations on every character
- **Weeks 9–30:** Pinyin annotations on characters newly learned that week and on HSK 2+ characters
- **Weeks 31–80:** Pinyin only on HSK 3+ characters or unfamiliar
- **Weeks 81+:** Pinyin only on rare characters or specific pronunciation notes
- **Mastery polish:** Native-like character density

## 10.3 Romanization

Always use **Pinyin** (Hanyu Pinyin) — the official standard. Do not use Wade-Giles (older system, mostly historical) or other romanizations unless explicitly noted as a regional variant (e.g., Taiwan's Tongyong Pinyin or Zhuyin Fuhao/Bopomofo).

Always include tone marks (mā má mǎ mà) — not tone numbers (ma1 ma2 ma3 ma4) except in technical contexts.

## 10.4 Character Variant Convention

- **Simplified is primary** throughout the curriculum
- **Traditional is shown** when:
  - The character differs (e.g., 国/國, 学/學, 爱/愛) — show as 国 (國)
  - Reading authentically Taiwanese/HK content (Levels 5–6)
- **Same character in both systems** — show simplified only

## 10.5 Vocabulary Selection

- Pull from HSK vocabulary lists at appropriate level
- Show characters + pinyin + English + example sentence
- Include measure words for nouns
- Note if a word is more common in Mainland vs. Taiwan if meaningfully different
- Include high-frequency chengyu from Level 3 onward

## 10.6 Example Sentence Composition

- Use natural-sounding Mandarin — not English-translated patterns
- Show subject omission where natural — don't add 我 just to mirror English
- Include particles and measure words correctly and prominently
- Vary subjects beyond 我 and 你
- Use Chinese contexts (cities, foods, cultural events) where natural

## 10.7 Cultural Notes

- High density throughout
- Specific places, people, dynasties, festivals, dishes
- Rotate across Mainland regions + Taiwan + HK + diaspora
- Address modern China honestly at higher levels — tech, urbanization, generational change
- Handle sensitive topics (CR, Tiananmen, Taiwan, HK, Xinjiang, Tibet) neutrally and factually when they appear naturally; the curriculum's role is communication, not political position
- Note where Mainland and Taiwan diverge culturally without endorsing either

## 10.8 Listening Recommendations

- Level 1–2 (HSK 1–2): Mandarin Blueprint beginner; ChinesePod Newbie
- Level 2–3 (HSK 3): Slow Chinese podcast; ChinesePod Elementary–Intermediate; Mandarin Corner
- Level 3 (HSK 4): ChinesePod Intermediate–Upper; Slow Chinese; Easy C-dramas with Chinese subs
- Level 4 (HSK 5): Native podcasts (e.g., 故事FM, 大内密谈); mainstream C-dramas
- Level 5–6 (HSK 6 / 7–9): Full native — news, debate, documentary, literary podcasts

## 10.9 Reading Passages by Level

Calibrated to level (character counts — Chinese characters are denser than English words):

- **Level 1 (HSK 1–2):** ~100–200 characters; present tense; high furigana density
- **Level 2 (HSK 3):** ~250–400 characters; varied tenses with aspect particles; pinyin on new characters
- **Level 3 (HSK 4):** ~500–800 characters; complex sentences; mostly pinyin-free
- **Level 4 (HSK 5):** ~1,000–1,500 characters; native-style register
- **Level 5 (HSK 6):** ~2,000–3,000 characters; literary or specialized
- **Level 6 (HSK 7–9 / C2):** Native-like density

## 10.10 Grammar Explanations

- In English through Level 3 (HSK 4); transitioning to Chinese for grammar terms at Level 4+
- Pattern + example + translation + explanation + common pitfall format
- Contrast with English (and Japanese/Korean where helpful) for learners with prior East Asian language background

## 10.11 Drill Variety

- Mix at least three of: tone identification, character reading, character writing (early levels), particle fill-in, sentence reordering, translation (both directions), measure word selection, chengyu meaning matching (later levels)
- Avoid pure multiple-choice except for nuance items

## 10.12 Tone Section Practice

Every lesson includes a tone focus mini-section:

- **Level 1:** Tone identification; minimal pairs; basic combinations
- **Level 2:** Tone sandhi in connected speech; sentence-level prosody
- **Level 3:** Native-speed tone work; fast-speech reduction
- **Level 4+:** Tone in colloquial reductions; regional accent awareness

## 10.13 The Weekly Challenge

Examples calibrated to level:

- Level 1: Order food in Chinese at a Chinese restaurant (or roleplay)
- Level 2: Write a self-introduction (自我介绍) and recite it aloud
- Level 3: Have a 10-minute conversation in Chinese with a tutor
- Level 4: Comment on a Chinese YouTube/Bilibili video in natural Chinese
- Level 5: Give a 5-minute presentation in Chinese on a chosen topic
- Level 6: Engage in unscripted debate or interview in Chinese; or write a chengyu-rich essay

---

*End of document. This is the Mandarin Chinese-specific reference for the language learning project. The next deliverable (when ready for the build phase) would be the structured curriculum data (\`lib/curricula/mandarin.ts\`) with all 190 weeks as TypeScript objects matching the schema used for Spanish, Japanese, and Korean.*
`;
