// Auto-generated by scripts/embed-references.ts
// Source: mandarin-pedagogy-addendum.md
// Do not edit by hand. Re-run the embedding script if the source changes.

export const mandarinAddendum = `# Mandarin Pedagogical Addendum (Hacking Chinese-inspired)

**Purpose.** This addendum supplements \`mandarin-curriculum-reference.md\` with specific pedagogical techniques drawn from Olle Linge's *Hacking Chinese* (the blog at hackingchinese.com and the 2016 book *Hacking Chinese: A Practical Guide to Learning Mandarin*). These are Mandarin-specific applications of universal principles (see Part 8 of \`pedagogy-foundations.md\`). The Mandarin reference already covers variety decisions (Mainland Standard Mandarin vs Taiwan Mandarin), the seven dimensions, and the 200-week curriculum architecture; this addendum focuses on *how to teach* the bottleneck features of Mandarin.

This addendum should be embedded alongside the Mandarin reference when generating Mandarin lessons (it adds ~2,500 words). For other languages, the universal principles in pedagogy-foundations Part 8 apply, but this addendum is Mandarin-specific.

---

## 1. Tones Are Non-Negotiable, And Must Be Taught Correctly From Day One

**The principle.** Mandarin has four lexical tones plus a neutral tone. Tones are not optional or decorative — they distinguish meaning. *mā* (mother), *má* (hemp), *mǎ* (horse), *mà* (scold), and *ma* (question particle) are five completely different words. A learner with poor tones is not "fluent with a slight accent" — they are unintelligible.

**Why this matters specifically for Mandarin (Hacking Chinese's contribution).** Most courses teach tones in the first weeks and then move on. But research and practitioner experience show that early tone training is often inadequate or actively wrong. The third tone in particular is widely mistaught — many learners are told to pronounce it as a full "dipping" tone (falling then rising), when in natural speech it almost always appears as a low tone (just the falling portion). Linge's own experience: "I started learning Chinese in 2007, and misunderstood how the third tone is supposed to be pronounced. No one pointed this out or tried to correct my pronunciation until I had studied for almost two years."

**Specific implications:**
- Third tone in connected speech = low tone, not full dipping
- Third tone before another third tone → becomes second tone (third tone sandhi)
- Tones are produced relative to the speaker's pitch range, not absolute pitches
- Neutral tone is its own thing, not "no tone"
- Learners need to *hear* tones accurately before they can produce them — passive discrimination training improves active production

**Lesson-generation implication.** Section 8 (Speaking Exercise) for Mandarin must address tones explicitly from Week 1. Section 5 (Listening Exercise) should include tone-discrimination practice — hearing pairs of words distinguished only by tone. Section 3 (Grammar Focus) should include tone-change rules (sandhi) when relevant. Never treat tones as a one-week introduction to be put behind the learner.

## 2. Tone Pairs Are the Real Unit of Mandarin Pronunciation

**The principle.** Most Mandarin vocabulary is two-character (and therefore two-syllable) compounds. Mastering tones in isolation is not enough — learners need to master the 20 tone pair combinations (4 tones × 4 tones, plus 4 neutral-tone combinations). Some combinations are easy (1+1: 飞机 *fēijī*, airplane); others are notoriously hard (3+2: 美国 *Měiguó*, America — the falling-then-rising contour into a rising tone).

**Why this matters (Hacking Chinese's core insight).** "Mastering tone pairs is crucial for all students. So much of Chinese is made up of two-character words and terms. An enormous number of verbs, nouns and most of all adjectives are two characters, and the natural patterns of speech in Mandarin often involves breaking up sentences into two-character pieces." Learners who can pronounce individual tones in isolation but stumble on tone pairs will sound non-native even when each tone is technically correct.

**The 20 tone pairs to master:**
- 1+1, 1+2, 1+3, 1+4, 1+0
- 2+1, 2+2, 2+3, 2+4, 2+0
- 3+1, 3+2, 3+3 (→ 2+3), 3+4, 3+0
- 4+1, 4+2, 4+3, 4+4, 4+0

**Lesson-generation implication.** Section 8 (Speaking Exercise) for Mandarin should occasionally focus on a specific tone pair (e.g., "this week: 3+2 combinations like *měiguó*, *hǎoxiàng*, *zǎochén*"). Vocabulary in Section 2 should be tone-pair-labeled when introduced as compounds. Drill exercises in Section 7 can include tone-pair recognition and production tasks.

## 3. Phonetic-Semantic Compounds: The Key to 80%+ of Chinese Characters

**The principle.** At least 80% of all Chinese characters are phonetic-semantic compounds — they have one component that hints at meaning and one component that hints at pronunciation. This is the single most important insight for character learning, and it's often glossed over in textbooks.

**Example.** Consider these characters that all share the phonetic component 青 (qīng): 晴 (qíng, clear weather), 情 (qíng, feeling), 请 (qǐng, please), 清 (qīng, clear water). All are pronounced with some variation of "qing" because they share the 青 phonetic component. The other component hints at meaning: 日 (sun) for clear weather, 忄 (heart) for feeling, 讠 (speech) for please/request, 氵 (water) for clear water.

**Another example.** Characters using 马 (mǎ, horse) as a phonetic component: 妈 (mā, mother — with 女 woman for meaning), 吗 (ma, question particle — with 口 mouth for meaning), 骂 (mà, scold — with 口口 mouths for meaning). All pronounced "ma" with different tones because they share the 马 phonetic.

**Why this matters (Hacking Chinese's strongest position).** Linge argues this is the single biggest gap in mainstream Mandarin teaching. Methods that teach characters as pure pictographs (like Chineasy) fall apart quickly because most characters aren't pictographs — they're phonetic-semantic compounds. Methods that teach meaning without pronunciation (like Heisig's *Remembering the Hanzi*) force learners to do extra work later relinking sound to character.

**Lesson-generation implication.** From the first week characters are introduced, Section 2 (Key Vocabulary) should explicitly identify the phonetic and semantic components of new characters. When introducing a new character, mention any phonetic series it belongs to (e.g., "晴 is part of the 青 phonetic series — others include 情, 请, 清"). This is high-leverage: one explanation unlocks pattern recognition for dozens of future characters.

## 4. Always Learn Character Meaning AND Pronunciation Together

**The principle.** Never separate the meaning of a character from its pronunciation. Some popular methods (notably Heisig's *Remembering the Hanzi*) advocate learning meaning first, then layering pronunciation later. Hacking Chinese argues this is suboptimal for Mandarin because of the phonetic-semantic compound structure described above — separating sound from form actively hides the logic of how characters work.

**Why this matters.** If you learn 马 (horse) without learning it's pronounced "mǎ", then when you encounter 妈 (mother), 吗 (question particle), 骂 (scold), you have to memorize each pronunciation as if random. If you learned 马 = mǎ from the start, you can immediately predict that these related characters are all "ma"-something — the phonetic component does its job.

**Lesson-generation implication.** Section 2 (Key Vocabulary) must always present new characters with pinyin and meaning simultaneously, never separately. Section 7 (Drill) recall exercises should test the full triple (character ↔ pinyin ↔ meaning), not pairwise subsets.

## 5. Horizontal Character Learning: Learn Similar Characters Side-by-Side

**The principle.** When characters look similar or share components, learn them together rather than in isolation. This is "horizontal character learning" — building lateral connections in your mental web rather than treating each character as an isolated node.

**Why this matters.** Beginners can keep characters separate because they know few. As the inventory grows past ~500 characters, learners increasingly encounter characters that differ by only a stroke or two (e.g., 己 jǐ "self" vs 已 yǐ "already" vs 巳 sì "sixth earthly branch"). Trying to learn these in isolation produces persistent confusion. Side-by-side learning with explicit attention to the distinguishing features resolves it.

**Common horizontal sets:**
- Phonetic series: 青 → 晴 情 请 清 (described above)
- Visually confusable pairs: 己 vs 已 vs 巳; 末 mò "end" vs 未 wèi "not yet"; 干 gān "dry" vs 千 qiān "thousand"
- Semantically related characters: 看 kàn "look" vs 见 jiàn "see" vs 视 shì "view"; 走 zǒu "walk" vs 跑 pǎo "run" vs 跳 tiào "jump"

**Lesson-generation implication.** When Section 2 (Key Vocabulary) introduces a character that has a notorious visual confusion partner or belongs to a phonetic series, briefly mention the comparison. Section 10 (Cultural/Pragmatic Notes) or Section 7 (Drill) can occasionally feature horizontal comparison exercises.

## 6. Type, Don't Handwrite (for productive output)

**The principle.** Like the Japanese addendum's position, Hacking Chinese supports typing-first for productive use of Mandarin. Modern Mandarin is overwhelmingly typed via pinyin input method (IME) — the learner types pinyin and selects the correct character from a list. This requires *recognition* of characters but not *production* from memory.

**Why this is controversial for Mandarin specifically.** Traditional Chinese pedagogy emphasizes handwriting practice (听写 *tīngxiě* dictation) as foundational. Linge's nuanced position: handwriting is a separate skill that can be added later if the learner wants it, but it should not be the gating skill for productive use. Many serious Mandarin learners reach fluent reading and typing without fluent handwriting and consider this a reasonable tradeoff.

**For learners going to mainland China or Taiwan for academic/professional work**: some handwriting capability is socially expected. For learners studying Mandarin for business, travel, or media consumption: handwriting can be skipped or minimized.

**Lesson-generation implication.** Section 9 (Writing Exercise) for Mandarin should default to typed output (via pinyin IME) unless the learner specifically wants handwriting practice. Section 7 (Drill) can include recognition (character → pinyin → meaning) without requiring production. Mention that handwriting is optional and can be added later.

## 7. Simplified vs Traditional Characters: A Variety Choice

**The principle.** Mainland China uses Simplified characters (introduced in the 1950s-60s). Taiwan, Hong Kong, and Macau use Traditional characters. Singapore uses Simplified. Most Chinese diaspora communities historically used Traditional but increasingly mix.

**Practical guidance:**
- **Default to Simplified** for most learners — mainland is by far the largest target audience
- **Choose Traditional** if the learner's specific goal is Taiwan, Hong Kong, or classical Chinese reading
- **Eventually learn both** if going to advanced levels — about 60% of characters are identical or near-identical, and the remaining 40% have predictable mappings

**Lesson-generation implication.** The Mandarin curriculum reference already specifies a variety choice (typically Simplified Mainland Mandarin). Section 2 (Key Vocabulary) should present characters in the chosen variety with the other variety in parentheses for high-frequency characters where the difference matters (e.g., 国/國, 学/學, 爱/愛, 听/聽).

## 8. The +1 Rule Applied to Mandarin

**The principle.** Tofugu's "80%/+1 rule" (see pedagogy-foundations Part 8.1) applies to Mandarin with particular force because of the script-tone-vocabulary interdependence. A learner reading a sentence in Mandarin is processing characters, tones, and vocabulary simultaneously. If too many of these are unknown, the sentence becomes opaque.

**For Mandarin specifically:**
- Reading passages in Section 4 should use mostly known characters with new vocabulary clearly bounded
- Avoid sentences where multiple new elements stack (new character + new tone pair + new grammar in one sentence)
- When introducing a new grammar pattern, example sentences should use familiar characters and tone-tested vocabulary
- Pinyin should be provided alongside characters in A1-A2 reading passages; reduce at B1+, removed by B2

**Lesson-generation implication.** This is the most important constraint on Mandarin reading passages. Section 4 should always display characters with pinyin annotation at A1-A2, transitioning to pinyin-only-for-new-words at B1, then pinyin-only-for-rare-words at B2+.

## 9. SRS Habit — Anki / Pleco / Skritter — Non-Negotiable

**The principle.** Spaced Repetition Systems are essential for Mandarin specifically because of the sheer volume of characters (3,000+ for adult literacy, 8,000+ for full literacy) and vocabulary (HSK 6 = 5,000 words, real fluency requires more).

**Recommended SRS tools for Mandarin:**
- **Anki** (free, cross-platform) — community decks like "HSK 1-6" or "Spoonfed Chinese" are excellent
- **Pleco** (free with paid features) — Chinese dictionary with integrated SRS, the most popular Mandarin learner app
- **Skritter** (paid) — specialized for handwriting practice; only relevant if learner wants handwriting
- **Hack Chinese** (paid) — vocabulary SRS specifically designed for Mandarin

**Recommended SRS practice:**
- Daily review (15-30 minutes minimum at intermediate)
- New cards added at sustainable pace (10-20/day for committed learners)
- Test all directions: character → meaning, character → pinyin, pinyin → character, meaning → character (recognition is easier than production; both matter)

**Lesson-generation implication.** Section 11 (Self-Assessment) for Mandarin should include "Did I do my daily SRS reviews this week?" as a recurring checkpoint. Section 12 (Weekly Challenge) can occasionally specify SRS-related goals.

## 10. Listening Before Speaking — Multi-Speaker Variability Matters

**The principle.** Research shows that tone discrimination is best trained through exposure to multiple different speakers, not just one. A learner who has only ever heard their teacher's tones will struggle with native speakers whose voices have different pitch ranges and dialects. Linge developed a free tone training course specifically to provide this multi-speaker variability.

**Why this matters.** Tones are perceived relative to the speaker's pitch baseline. A male speaker's third tone might be in the same absolute frequency as a female speaker's first tone, but learners must internalize the relative contour, not absolute pitch. This only happens with varied input.

**Lesson-generation implication.** Section 5 (Listening Exercise) for Mandarin should recommend audio sources with varied speakers — podcasts with multiple hosts, news shows with different reporters, drama with male and female actors. Don't recommend single-speaker audio exclusively.

## 11. Compound Word Logic — Mandarin Vocabulary Is Often Transparent

**The principle.** Many Mandarin compounds are logically transparent once you know the component characters. This is a substantial cognitive advantage Mandarin offers over languages where vocabulary is morphologically opaque.

**Examples:**
- 电 (diàn, electric) + 话 (huà, speech) = 电话 (diànhuà, telephone)
- 电 + 脑 (nǎo, brain) = 电脑 (diànnǎo, computer)
- 电 + 影 (yǐng, shadow) = 电影 (diànyǐng, movie)
- 火 (huǒ, fire) + 车 (chē, vehicle) = 火车 (huǒchē, train)
- 飞 (fēi, fly) + 机 (jī, machine) = 飞机 (fēijī, airplane)

**Why this matters.** Adult learners benefit enormously from seeing these patterns explicitly. Once a learner internalizes that 电 means electric/electronic, they can predict the meaning of dozens of 电-compounds without explicit memorization.

**Lesson-generation implication.** Section 2 (Key Vocabulary) for Mandarin should regularly decompose new compounds into their component characters when the decomposition is logical and useful. This is high-leverage pattern instruction.

## 12. The Intermediate Wall (Mandarin specifically)

**The principle.** The intermediate wall (pedagogy-foundations Part 8.15) hits Mandarin learners particularly hard at the HSK 4 / B1 level because:
- A1-A2 progress feels fast (a few hundred characters, basic tone production, simple compounds)
- B1 is where the character inventory needs to grow from ~600 to ~1,200, and the rate of new compounds explodes
- B1-B2 is where the learner realizes they can read short articles but not novels, can have basic conversations but not nuanced ones
- The gap between HSK 4 (often called "intermediate" by tests) and genuine functional fluency is enormous

**For Mandarin learners specifically:**
- Name the wall at B1 — make it explicit in occasional lesson content that this difficulty is expected
- Topic-driven learning becomes essential from B2 — find Chinese content the learner actually wants to consume
- Encourage extensive reading via graded readers (Mandarin Companion, Chinese Breeze) at B1, transitioning to native content at B2+
- Listening should expand from textbook audio to authentic content (podcasts like Slow Chinese, then Mandarin Corner, then 锵锵三人行 or similar native shows)

**Lesson-generation implication.** B1 Mandarin lessons should occasionally include acknowledgment of difficulty. B2+ lessons should increasingly invite the learner to pursue their own topical interests.

## 13. Resource Recommendations (Hacking Chinese-informed)

Per Hacking Chinese and other respected sources, for Mandarin specifically:

**Beginner textbooks:**
- *Integrated Chinese* (Cheng & Tsui) — most popular university textbook in the US; classroom-style
- *New Practical Chinese Reader* — used widely in Chinese institutions
- *Chinese for Dummies* / *Mandarin Chinese: An Essential Grammar* — for self-study

**Reference:**
- *A Practical Chinese Grammar for Foreigners* — comprehensive grammar reference
- *Outlier Linguistics Dictionary* (in Pleco) — etymologically accurate character explanations
- *ABC Chinese Dictionary* (Pleco) — comprehensive Chinese-English

**Character learning:**
- Pleco (free, with paid add-ons) — the standard learner app
- Skritter (paid) — handwriting practice
- HanziCraft, Zhongwen.com — character decomposition tools online

**SRS:**
- Anki — free, with HSK and Spoonfed Chinese community decks
- Hack Chinese (paid) — Mandarin-specialized vocabulary SRS

**Listening / reading (graded):**
- *Mandarin Companion* graded readers (5 levels)
- *Chinese Breeze* graded readers
- *Du Chinese* app (graded reading with audio)
- Slow Chinese podcast (B1+)
- Mandarin Corner YouTube (varied levels)

**Authentic content (B2+):**
- NHK World / CGTN news in Mandarin
- Chinese podcasts on Apple/Spotify
- Chinese dramas on Viki, YouTube, iQiyi
- Chinese-language films

---

*End of Mandarin Pedagogical Addendum. Embed alongside \`mandarin-curriculum-reference.md\` when generating Mandarin lessons.*
`;
