// Auto-generated by scripts/embed-references.ts
// Source: spanish-curriculum-reference.md
// Do not edit by hand. Re-run the embedding script if the source changes.

export const spanishReference = `# Spanish Curriculum Reference

**Purpose.** This is the Spanish-specific knowledge base for the language learning project. It applies the universal pedagogical framework (see \`pedagogy-foundations.md\`) to Spanish: how Spanish is characterized along the seven dimensions, why specific variety decisions were made, the full 130-week curriculum architecture, Spanish-specific resources and assessment paths, and notes on what English speakers find hard about Spanish specifically.

**Companion documents.**
- \`pedagogy-foundations.md\` — Universal principles + the seven-dimensional framework
- \`claude-code-prompt.md\` — The build spec for the lesson-generator app (contains the machine-readable curriculum data)
- This document — Spanish-specific reference (the human-readable curriculum overview)

**For future language additions.** This document is the model. To add Japanese, Mandarin, Arabic, etc., produce a parallel \`[language]-curriculum.md\` file using the same section structure.

---

# PART 1 — SPANISH LANGUAGE PROFILE

## 1.1 Basic Facts

- **Native speakers:** ~500 million (second most-spoken native language after Mandarin Chinese)
- **Total speakers (including L2):** ~600 million
- **Geographic distribution:** Spain, Mexico, Central America, most of South America (excluding Brazil and the Guianas), parts of the Caribbean (Cuba, Dominican Republic, Puerto Rico), Equatorial Guinea in Africa, and a major minority language in the United States (~58 million speakers)
- **Official status:** 21 countries
- **ISO 639-1 code:** es
- **Linguistic family:** Indo-European → Italic → Romance → Ibero-Romance

## 1.2 The Seven Dimensions Applied to Spanish

### Phonology — *Close*

For English speakers, Spanish phonology is one of the friendlier territories. Five pure vowel sounds (a, e, i, o, u — never reduced to schwa), most consonants familiar. The challenging items are bounded and learnable:

- **Rolled R (rr):** novel motor skill; some learners take months to acquire
- **Tap R (single r between vowels):** quick to acquire
- **The "th" sound (distinción):** unique to Castilian Spain; receptive only for non-Spain learners
- **Voiced fricatives (b/v, d, g):** these are pronounced as soft fricatives between vowels, unlike English stops
- **Linking and syllabification:** Spanish links words at vowel boundaries far more than English; affects listening comprehension

**Implication:** Moderate pronunciation focus throughout the curriculum, with rolled R training from Week 1. No tone work needed. Intelligible pronunciation is achievable for adults with deliberate practice.

### Writing System — *Same alphabet*

Latin alphabet with minor additions: **ñ**, written accents (á, é, í, ó, ú, ü), and the inverted opening punctuation (¿ ¡). The alphabet itself is 27 letters (Spanish dropped *ch* and *ll* as separate letters in 2010 but they still appear in older sources).

Spanish spelling is highly **phonemic** — words are pronounced as written, with very few exceptions. This is a major advantage over French or English.

**Implication:** No separate script work needed. Reading can begin Week 1. Spelling work is minimal.

### Morphology — *Fusional with rich verbal inflection*

Spanish is fusional: a single verb ending can encode person, number, tense, and mood simultaneously. Verb conjugation is the curriculum's largest grammatical task by far.

- **17 simple + compound tenses** in active voice (present, preterite, imperfect, future, conditional × indicative/subjunctive plus perfect forms of each)
- **3 verb classes** (-AR, -ER, -IR) plus many irregulars
- **Two moods** (indicative + subjunctive) that the learner must distinguish constantly from B1 onward
- **Nouns and adjectives** also inflect for gender and number, with agreement throughout the noun phrase

**Implication:** Heavy paradigm work in A1–B2. Subjunctive is a major focus from Week 37 through B2. Conjugation memorization, while sometimes derided, is genuinely necessary — there's no shortcut.

### Word Order — *SVO with significant flexibility*

Subject-Verb-Object as the default, very close to English. But Spanish allows substantial reordering for emphasis, topic, and information structure — far more than English does. Subject pronouns are usually omitted (pro-drop language), since the verb ending tells you who.

**Implication:** Low restructuring cost for English speakers. Pro-drop must be taught early (Spanish speakers don't say "I" with every verb). Word-order flexibility is a B1–B2 topic.

### Register — *Simple to moderate*

The main register distinction is the **tú / usted** axis (informal / formal "you" singular). This is introduced Week 1 and worked with throughout. Use varies by country:

- Spain: tú dominant in most informal contexts; usted reserved for clear formality
- Mexico: more usted use, especially with elders
- Colombia: usted used between friends in some regions (more affectionate)
- Argentina/Uruguay: **vos** replaces tú as informal (the voseo)

The plural-you distinction adds another layer: **vosotros** (informal plural, Spain only) vs. **ustedes** (formal plural in Spain; ALL plural in Latin America).

**Implication:** T/V distinction is foundational from Week 1. Vosotros conjugations are introduced explicitly at Week 41 with the note that they are Spain-only. Voseo is mastered at C2 (Week 127).

### Cultural-Pragmatic Distance — *Close-to-moderate*

Spanish-speaking cultures vary widely, but for English speakers (especially American English speakers), the pragmatic distance is small to moderate. Politeness norms differ slightly (more frequent use of "por favor" and "gracias", more affectionate diminutives, more emotional expressiveness in some regions). Directness varies — Spaniards are often more direct than Anglo norms, while many Latin American cultures favor more indirectness. Regional variation is enormous — pragmatics in Buenos Aires differ from Mexico City differ from Madrid.

**Implication:** Moderate cultural-note density. Rotation across regions is essential to expose learners to the full diversity rather than producing "Mexican Spanish only" or "Spain Spanish only" learners.

### Resource Availability — *Major language; abundant*

Spanish is exceptionally well-resourced:

- Vast graded reader catalogs
- Multiple high-quality free YouTube channels (Dreaming Spanish, Easy Spanish)
- Major podcast networks at every level
- Affordable tutors on iTalki ($8–25/hour)
- Plentiful language partners on Tandem and HelloTalk
- A massive native media universe (telenovelas, Netflix Spanish-language originals, news)
- Cheap immersion travel options
- Free comprehensive grammar references (StudySpanish, SpanishDict)

**Implication:** Specific recommendations can be made at every level. No need for adapted approaches due to resource scarcity.

---

# PART 2 — VARIETY DECISION

## 2.1 The Decision

**Neutral Latin American Spanish** as the productive (speaking, writing) base. **Castilian (Peninsular) Spanish** and major regional varieties as receptive (listening, reading) targets layered in progressively.

## 2.2 Rationale

Spanish is **pluricentric** — no single variety is "the" Spanish. The choice is strategic, not linguistic.

- **Speaker count:** ~450 million Latin American speakers vs. ~47 million Peninsular speakers. Wider utility.
- **Mutual intelligibility:** All varieties are 95%+ mutually intelligible. Core grammar and vocabulary are shared. The differences are real but bounded.
- **Pronunciation clarity:** Neutral LatAm pronunciation uses *seseo* (c/z/s all pronounced /s/), which is simpler for beginners than Castilian *distinción*. It's also the variety used in dubbed media and most international broadcasting.
- **Media coverage:** Most Spanish-language Netflix originals, US-market broadcasting, and international press uses LatAm-leaning Spanish.

By the end of C1, the learner understands all varieties. By C2, they can switch register and dialect.

## 2.3 What This Decision Excludes

**It does not exclude Castilian Spain.** Learners who plan to live in Spain will have full comprehension by B2 and can shift to active production of Peninsular features (vosotros, distinción, Peninsular vocab) in their conversation practice. The curriculum gives them everything they need.

**It does not pick one Latin American country over others.** "Neutral LatAm" is a constructed register — it's what telenovela dubbing studios and international Spanish-language news anchors use. Mexican vocabulary appears (because Mexico is the largest Spanish-speaking country), but so do Argentine, Colombian, Cuban, and other regional flavors throughout.

## 2.4 Variety-Specific Introduction Schedule

- **Week 1:** Greetings vary regionally (¡Hola! universal; ¿Qué tal? Spain-leaning; ¿Qué onda? Mexico; ¿Qué hacés? Argentina)
- **Week 9:** Note that *tener que* (most common) coexists with *deber* (slightly more formal)
- **Week 13:** Vocabulary divergences noted (carro vs. coche, etc.)
- **Week 41:** Vosotros conjugations introduced explicitly
- **Week 55:** Castilian pronunciation immersion week
- **Week 79:** Mexico deep-dive
- **Weeks 101–102:** Caribbean + Andean + Chilean varieties
- **Weeks 125–126:** Peninsular Spanish full immersion
- **Weeks 127–128:** Rioplatense voseo (Argentina/Uruguay)

---

# PART 3 — CURRICULUM ARCHITECTURE

## 3.1 At a Glance

- **Total length:** 130 weeks
- **Pacing:** one lesson per week with daily practice between (30–45 min/day recommended)
- **Total study time at recommended pace:** ~270 hours of lessons + ~250 hours of daily practice = ~520 hours, approximately matching the Foreign Service Institute's 600-hour estimate for working proficiency in a Category I language
- **Level structure:** Six levels aligned to the Common European Framework of Reference

## 3.2 The Six Levels

| Level | Weeks | Span | Goal | Target Vocab |
|---|---|---|---|---|
| A1 — Foundations | 1–16 | 16 weeks | Survive basic interactions | ~500 words |
| A2 — Elementary | 17–32 | 16 weeks | Past tenses, simple conversation | ~1,200 words |
| B1 — Intermediate | 33–56 | 24 weeks | Opinions, hypotheticals, native content with effort | ~2,500 words |
| B2 — Upper-Intermediate | 57–80 | 24 weeks | Abstract topics, debate, most native content | ~4,500 words |
| C1 — Advanced | 81–104 | 24 weeks | Near-native fluency, professional use | ~7,000 words |
| C2 — Mastery | 105–130 | 26 weeks | Native-like proficiency in any context | 10,000+ words |

## 3.3 Pacing Philosophy

The curriculum loads heavier earlier:

- **A1–A2 (Weeks 1–32):** Heavy core grammar and high-frequency vocabulary. Every week introduces fundamental machinery.
- **B1 (Weeks 33–56):** The subjunctive arrives at Week 37 and dominates B1. This is the level where learners often plateau; the curriculum slows down here deliberately, with multi-week treatment of subjunctive triggers.
- **B2 (Weeks 57–80):** Compound tenses, advanced subjunctive, idiom, and the first sustained engagement with literature and news media. Grammar density still high.
- **C1 (Weeks 81–104):** Grammar lightens; the focus shifts to register, specialized domains (business, legal, medical, academic), and literature. Writing exercises grow in length and complexity.
- **C2 (Weeks 105–130):** Polish and breadth. Slang, regional varieties, advanced cultural and rhetorical content. The capstone week (130) produces a tangible mastery artifact (essay, podcast, DELE C2 exam, or public talk).

---

# PART 4 — WEEK-BY-WEEK OVERVIEW

The full structured data lives in \`lib/curricula/spanish.ts\`. This section is the readable overview.

## 4.1 Level A1 — Foundations (Weeks 1–16)

| W | Title | Core grammar/focus |
|---|---|---|
| 1 | Greetings, Alphabet, Pronunciation | Subject pronouns; tú/usted; vowels; rolled R intro |
| 2 | Numbers, Dates, Time | Numbers 0–1000; days/months; telling time |
| 3 | Ser vs. Estar — Intro | Both verbs in present; first rules |
| 4 | Nouns, Articles, Gender, Plurals | Gender patterns; el/la/los/las; un/una |
| 5 | Regular -AR Verbs | Full -AR conjugation; 20 high-frequency verbs |
| 6 | Regular -ER and -IR Verbs | -ER and -IR conjugations |
| 7 | Family & Possessives | mi/tu/su/nuestro with agreement |
| 8 | Describing People and Things | Adjective placement and agreement |
| 9 | High-Frequency Irregular Verbs | tener, ir, hacer, ver, dar, saber, conocer, querer, poder |
| 10 | Food, Restaurants, Ordering | querer + infinitive; polite requests |
| 11 | Daily Routines (Reflexive Intro) | Reflexive pronouns; routine verbs |
| 12 | Home, Rooms, Prepositions | hay; prepositions of place |
| 13 | Clothing, Shopping, Colors | Demonstratives; llevar/ponerse |
| 14 | Weather, Seasons, Activities | Weather expressions; gustar preview |
| 15 | Gustar and Similar Verbs | gustar construction; encantar, doler, etc. |
| 16 | A1 Review & Self-Assessment | Mock A1 across all four skills |

## 4.2 Level A2 — Elementary (Weeks 17–32)

| W | Title | Core grammar/focus |
|---|---|---|
| 17 | Present Progressive | estar + gerundio |
| 18 | Direct Object Pronouns | lo, la, los, las; placement |
| 19 | Indirect Object Pronouns | me, te, le, nos, os, les; redundancy |
| 20 | Combining Pronouns | IO before DO; le→se shift |
| 21 | Preterite — Regular Verbs | Regular -AR/-ER/-IR preterite |
| 22 | Preterite — Irregulars Set 1 | ser/ir, tener, estar, hacer, decir |
| 23 | Preterite — Stem Changes + More | Stem-changing -IR; poder, poner, etc. |
| 24 | Imperfect Tense | Regular forms; ser/ir/ver irregulars |
| 25 | **Preterite vs. Imperfect** | The critical distinction; meaning shifts |
| 26 | Travel & Transportation | Past-tense narration |
| 27 | Health & Body | doler; medical vocabulary |
| 28 | Future Plans (Ir a + inf) | Periphrastic future; pensar, acabar de |
| 29 | Comparatives & Superlatives | más/menos, tan/tanto; irregular forms |
| 30 | Reflexive Verbs Deep Dive | Inherent reflexives; meaning shifts |
| 31 | Por vs. Para | The eight or so uses of each |
| 32 | A2 Review & Self-Assessment | Mock A2 across all four skills |

## 4.3 Level B1 — Intermediate (Weeks 33–56)

| W | Title | Core grammar/focus |
|---|---|---|
| 33–34 | Future Simple Tense | Regular + 12 irregular stems; probability use |
| 35–36 | Conditional Tense | Politeness, hypotheticals, future-in-past |
| 37–38 | **Present Subjunctive — Introduction** | Formation; ojalá; WEIRDO preview |
| 39–40 | Subjunctive in Noun Clauses | WEIRDO triggers; emotion + impersonal |
| 41–42 | Affirmative Commands (incl. Vosotros) | tú, usted, ustedes; vosotros (Spain) |
| 43–44 | Negative Commands & Pronoun Placement | All subjunctive; accent rules |
| 45–46 | Relative Pronouns | que, quien, el cual, lo que, cuyo |
| 47–48 | Adverbs and Connectors | -mente; sequencing and cause-effect |
| 49–50 | Work & Professions / Interviews | Subjunctive in workplace contexts |
| 51–52 | Education & Academic Life | Reported speech in academic contexts |
| 53–54 | Technology & Communication | Anglicisms; digital register |
| 55 | **Castilian Spanish Immersion** | Vosotros, distinción, Peninsular vocab |
| 56 | B1 Review & Self-Assessment | Mock B1 (DELE B1 format) |

## 4.4 Level B2 — Upper-Intermediate (Weeks 57–80)

| W | Title | Core grammar/focus |
|---|---|---|
| 57–58 | **Imperfect Subjunctive** | Formation; uses including como si |
| 59–60 | Compound Past Tenses | Present perfect, pluscuamperfecto, future/conditional perfect |
| 61–62 | **Si Clauses** | Real, hypothetical, counterfactual conditionals |
| 63–64 | Passive Voice & Se Constructions | True passive vs. passive se vs. impersonal se |
| 65–66 | Reported Speech | Tense shifts; questions and commands |
| 67–68 | Subjunctive in Adverbial Clauses | Always-trigger vs. context-dependent |
| 69–70 | Subjunctive vs. Indicative — Mastery | Comprehensive review; opinion verbs |
| 71–72 | Idiomatic Expressions | 100+ idioms by theme |
| 73–74 | Literature — Short Stories | Reading + analysis; magical realism intro |
| 75–76 | News Media & Current Events | Print and broadcast journalism |
| 77–78 | Debate & Argumentation | Concession, contrast, cause-effect |
| 79 | Mexico Deep Dive | Mexican Spanish, culture, cinema |
| 80 | B2 Review & Self-Assessment | Mock B2 (DELE B2 format) |

## 4.5 Level C1 — Advanced (Weeks 81–104)

| W | Title | Core focus |
|---|---|---|
| 81–82 | Advanced Subjunctive Uses | Concession, indefinite antecedents, superlatives |
| 83–84 | Sequence of Tenses (Concordancia) | Tense matching in subordinate clauses |
| 85–86 | Compound Tenses Deep Dive | Perfect subjunctive, pluscuamperfecto subj. |
| 87–88 | Advanced Discourse Markers | Formal connectors and cohesion |
| 89–90 | Formal Writing — Essays | Essay structure; thesis development |
| 91–92 | Business Spanish | Correspondence, negotiation, meetings |
| 93–94 | Legal & Medical Spanish | Specialized vocabularies |
| 95–96 | Scientific & Tech Spanish | Passive voice in scientific writing |
| 97–98 | Spanish Literature (Classic + Contemporary) | Don Quijote excerpts; Lorca; Boom |
| 99–100 | Spanish Cinema (Spain + LatAm) | Almodóvar, Cuarón, Iñárritu, Del Toro |
| 101–102 | Regional Dialects Deep Dive | Caribbean, Andean, Chilean |
| 103 | Translation Skills | Cross-linguistic challenges |
| 104 | C1 Review & Self-Assessment | Mock C1 (DELE C1 format) |

## 4.6 Level C2 — Mastery (Weeks 105–130)

| W | Title | Core focus |
|---|---|---|
| 105–106 | Register, Tone, Pragmatics | Switching register; reading social cues |
| 107–108 | Slang by Region | Mexico, Spain, Argentina, Colombia, Chile |
| 109–110 | Idiomatic Mastery | Body, animals, refranes, proverbs |
| 111–112 | Wordplay, Humor, Irony | Puns, sarcasm, albur (Mexico) |
| 113–114 | Literature — Full Work | Read complete novella or play; critical response |
| 115–116 | Academic Discourse | Lectures, abstracts, peer review |
| 117–118 | Public Speaking & Rhetoric | Famous speeches; speech preparation |
| 119–120 | Specialized Field (Student's Choice) | Build glossary for chosen field |
| 121–122 | Old Spanish & Historical Varieties | Don Quijote in original; medieval forms |
| 123–124 | Creative Writing | Short fiction; poetry; pastiche |
| 125–126 | Peninsular Spanish Full Immersion | Vosotros production; distinción; Spain slang |
| 127–128 | Voseo (Rioplatense) | vos conjugations; Argentine literature/tango |
| 129 | Comprehensive Final Review | Self-test across all skills |
| 130 | **Capstone Project** | Essay, podcast, DELE C2 exam, or public talk |

---

# PART 5 — CULTURAL ROTATION STRATEGY

Spanish-speaking cultures are not monolithic. The curriculum deliberately rotates the cultural-note focus to avoid producing learners who only know Mexican or only know Spanish (Spain) culture. The rotation aims for coverage of:

- **Spain** — Madrid, Andalucía, Catalonia, the Basque Country
- **Mexico** — central, southern, northern (border culture)
- **Caribbean** — Cuba, Puerto Rico, Dominican Republic
- **Andean** — Peru, Bolivia, Ecuador
- **Southern Cone** — Argentina, Uruguay, Chile
- **Central America** — Guatemala, El Salvador, Honduras, Nicaragua, Costa Rica, Panama
- **Northern South America** — Colombia, Venezuela
- **U.S. Latino cultures** — Mexican-American, Cuban-American, Puerto Rican, Central American diaspora
- **Equatorial Guinea** — the African Spanish-speaking nation (briefly noted)

Lessons that map naturally to specific regions (e.g., Week 79 Mexico, Weeks 101–102 regional dialects, Weeks 125–128 Peninsular and Rioplatense) are anchored. Other lessons cycle their cultural notes deliberately to ensure broad coverage.

**Lesson-generator instruction:** When generating the cultural note for any week without a region anchor, pick a country that hasn't been featured recently. The Claude.ai prompt for each lesson can include a note about which countries have been recently featured (if the assistant wants to track this).

---

# PART 6 — RESOURCES FOR SPANISH

## 6.1 Comprehensible Input

- **[Dreaming Spanish](https://www.dreamingspanish.com/)** (YouTube + paid platform) — best-in-class comprehensible input video lessons, organized by level. Primary recommendation for A1–B2.
- **[Easy Spanish](https://www.youtube.com/c/EasySpanish)** — street interviews exposing regional speech. Strong from A2.
- **[Notes in Spanish](https://www.notesinspanish.com/)** — podcast with episodes at multiple levels.
- **[News in Slow Spanish](https://www.newsinslowspanish.com/)** — slow, clear news; A2–B2.
- **[Spanish with Paul](https://www.youtube.com/@SpanishwithPaul)** — clear grammar explanations.

## 6.2 Structured Courses (free)

- **Language Transfer "Complete Spanish"** — free audio course; the best grammar-intuition builder for A1–B1. Pair with curriculum weeks 1–40.
- **StudySpanish.com** — comprehensive free grammar reference.
- **SpanishDict** — best free dictionary and verb conjugator.

## 6.3 Conversation

- **[iTalki](https://www.italki.com/)** — one-on-one tutors and conversation partners ($8–25/hour). Start by Week 4.
- **[Preply](https://preply.com/)** — similar to iTalki.
- **[Tandem](https://tandem.net/)**, **[HelloTalk](https://www.hellotalk.com/)** — free language exchange apps.

## 6.4 Graded Reading

- **A1–A2:** Olly Richards, "Short Stories in Spanish for Beginners"
- **B1:** Paco Ardit graded readers; "Practice Makes Perfect: Spanish Reading and Comprehension"
- **B2:** Newspaper articles — *El País*, *BBC Mundo*, *La Nación*
- **C1+:** Native literature in this order: Isabel Allende → Mario Vargas Llosa → Julio Cortázar → Gabriel García Márquez → Roberto Bolaño

## 6.5 Native Media by Level

Watch with **Spanish subtitles**, not English (English subtitles cancel listening benefit).

- **A2:** *Extra en español* (sitcom for learners)
- **B1:** *Destinos* (telenovela for learners); *Coco* dubbed
- **B2:** *La Casa de Papel*, *Élite* (Spain); *Club de Cuervos*, *Narcos México* (Mexico); *Las Chicas del Cable*
- **C1:** *El Laberinto del Fauno*; *Roma*; *Volver*; *El Secreto de Sus Ojos*; *Amores Perros*

## 6.6 Music for Listening Practice

- **Pop/ballad:** Jorge Drexler (Uruguay), Natalia Lafourcade (Mexico), Rosalía (Spain), Jesse & Joy (Mexico)
- **Rock:** Café Tacvba (Mexico), Soda Stereo (Argentina), Heroes del Silencio (Spain)
- **Reggaetón / Urban:** Bad Bunny (Puerto Rico), Rosalía, J Balvin (Colombia)
- **Folk traditions:** Tango (Argentina), Flamenco (Spain), Bolero (Cuba/Mexico), Bachata (Dominican Republic), Cumbia (Colombia)

## 6.7 Pronunciation Tools

- **Forvo.com** — native speaker pronunciations of individual words by country
- **SpanishDict audio** — every dictionary entry has audio
- **Shadowing**: pick any podcast at your level and repeat each sentence immediately after the speaker

---

# PART 7 — DAILY PRACTICE FRAMEWORK (SPANISH-FLAVORED)

| Activity | Time | Frequency | Spanish-specific notes |
|---|---|---|---|
| Anki SRS review | 10–15 min | Daily | Use the cards generated in each weekly lesson |
| Comprehensible input | 15–20 min | Daily | Dreaming Spanish primary; switch to native media at B2 |
| Active output (journaling) | 10 min | Daily | Write 3–5 sentences per day in Spanish about your day |
| Conversation with native | 30 min | 1–2× per week from Week 4 | iTalki tutor or Tandem partner |
| Reading at level | 15 min | 4× per week | Graded readers early; news at B2; literature at C1 |

**Spanish-specific habit recommendations:**

- Switch your phone language to Spanish around Week 8
- Switch one app (e.g., Netflix browse interface) to Spanish from Week 4
- Listen to Spanish music in passive mode at any level (low-effort exposure)
- Keep a small notebook of new idioms and corrections from native speakers

---

# PART 8 — ASSESSMENT MILESTONES

Optional but useful for external validation.

## 8.1 DELE (Diploma de Español como Lengua Extranjera)

The official Spanish proficiency exam administered by Instituto Cervantes (Spain). Six levels matching CEFR. Recognized globally for employment, academic admission, and Spanish/EU citizenship applications.

**Suggested DELE schedule:**

| Level | Curriculum week | Format |
|---|---|---|
| DELE A1 | End of Week 16 | Reading, writing, listening, speaking |
| DELE A2 | End of Week 32 | Same format, longer |
| DELE B1 | End of Week 56 | Substantive — 3.5-hour exam |
| DELE B2 | End of Week 80 | Substantive — 3.5+-hour exam |
| DELE C1 | End of Week 104 | ~4-hour exam |
| DELE C2 | End of Week 130 | Highest level; multi-day in some centers |

Exam fees vary by country and level ($100–$250 USD typically).

## 8.2 SIELE

Newer, computer-based, faster turnaround. Valid for four years (vs. DELE's lifetime). Some institutions accept it; others still prefer DELE. Useful as a practice run before DELE.

## 8.3 Self-Assessment

The 12-section lesson template includes a self-assessment checklist (Section 11) at the end of every lesson. Honest 1–5 ratings on "I can…" statements. Anything ≤3 should be revisited before moving on.

---

# PART 9 — COMMON CHALLENGES FOR ENGLISH SPEAKERS

These are the well-documented pain points. The curriculum addresses each but learners should know them in advance.

## 9.1 Ser vs. Estar

Two verbs that both mean "to be." The distinction is consistent but requires Spanish-mode thinking. Common errors persist into B2 and beyond. **Curriculum response:** introduced Week 3, revisited and refined throughout.

## 9.2 Por vs. Para

Two prepositions for what English mostly handles with "for." Each has roughly 8 uses; learning the patterns takes time. **Curriculum response:** dedicated Week 31, then revisited via example sentences throughout B1–B2.

## 9.3 Subjunctive Mood

English has the subjunctive in vestigial form ("If I were…"); Spanish uses it constantly. The mental shift to recognize subjunctive triggers and produce subjunctive forms in real time is the central B1–B2 challenge. **Curriculum response:** introduced Week 37; sustained focus Weeks 37–70 (over 30% of B1–B2 lessons touch subjunctive).

## 9.4 Preterite vs. Imperfect

Two past tenses where English has one. Choosing between them shapes how a story is told. **Curriculum response:** introduced separately (Weeks 21–24), then contrasted in dedicated Week 25, then woven into all subsequent narrative work.

## 9.5 Pronoun Placement

Where to put object pronouns (before conjugated verbs, attached to infinitives/gerunds/positive commands) is mechanically fiddly. **Curriculum response:** built up gradually (Weeks 18–20, 41–44).

## 9.6 Rolled R

Some learners take months to acquire. Some never fully acquire it. Intelligible Spanish is possible without a perfect trill but the goal is to approach it. **Curriculum response:** introduced Week 1; pronunciation drills in early lessons; recommended exercises (tongue position; the "butter" approximation).

## 9.7 Listening Speed

Native Spanish is fast, with extensive vowel linking and consonant softening. Even B1 learners often understand reading far better than listening. **Curriculum response:** listening exposure starts Week 1; graded difficulty; News in Slow Spanish recommended early; native speed introduced gradually.

## 9.8 The Vocabulary Iceberg at B2→C1

After 4,000 high-frequency words, every new word is less frequent and the vocabulary growth slows. Learners often plateau here. **Curriculum response:** B2 and C1 broaden across domains (literature, news, business, academic) precisely to expand vocabulary breadth.

## 9.9 Regional Variation Overwhelm

Encountering Argentine voseo or Caribbean dropped-S for the first time can feel like a different language. **Curriculum response:** explicit deep-dives at Weeks 79, 101–102, 125–128 demystify the variation.

## 9.10 The Affective Plateau

Many learners hit a wall around B1–B2 where progress feels invisible despite continued study. This is normal — the curriculum doubles down on motivation supports (real-world tasks, conversation partners, native media) at exactly this stretch.

---

# PART 10 — SPANISH-SPECIFIC NOTES FOR LESSON GENERATION

Notes for the AI generating each weekly Spanish lesson, beyond the universal pedagogical principles:

## 10.1 Vocabulary Selection

- Default to neutral LatAm vocabulary
- When a word has a strong regional variant (carro/coche, computadora/ordenador, celular/móvil), include both with notation
- Pull from frequency lists (e.g., the RAE Corpus Frequency Dictionary) for level-appropriate selection
- Include collocations and fixed phrases, not just bare words

## 10.2 Example Sentence Quality

- Write sentences that sound natural to a native ear, not English-translation-y
- Use varied subjects (not always "yo" or "Juan")
- Reference Spanish-speaking contexts (cities, foods, cultural events) where natural
- Avoid robotic patterns ("María va al supermercado. María compra manzanas. Las manzanas son rojas.")

## 10.3 Cultural Notes

- Name specific places, people, foods, or traditions — never generic "Spanish-speaking culture"
- Rotate across countries
- Avoid stereotypes (no flamenco-and-bullfights default for Spain; no mariachi-only default for Mexico)
- Where contested or sensitive, present neutrally (e.g., political history)

## 10.4 Listening Recommendations

- Point to a specific real findable resource (YouTube video name + channel, podcast episode topic, song title + artist)
- Calibrate to level: A1–A2 → Dreaming Spanish; A2–B1 → News in Slow Spanish, Easy Spanish; B1–B2 → Notes in Spanish, mainstream YouTube; B2+ → native media, podcasts, music
- Vary regional accents over time

## 10.5 Reading Passage Composition

Write the passage yourself, calibrated to level:

- **A1:** 80–120 words; present tense; concrete vocabulary; short sentences
- **A2:** 150–200 words; preterite and imperfect; basic discourse markers
- **B1:** 250–350 words; introduction of future/conditional/subjunctive; varied sentence types
- **B2:** 400–500 words; compound tenses; complex sentences; nuanced vocabulary
- **C1:** 500–700 words; literary or journalistic register; idiom; sophisticated discourse
- **C2:** 700–1000 words; near-native quality; specialized vocabulary as appropriate

## 10.6 Grammar Explanations

- In English through B2; transitioning to Spanish at C1+
- Brief and example-heavy; not lengthy abstract treatments
- "Common Pitfalls" section names the specific errors English speakers make
- Contrast with English where helpful, but don't belabor it

## 10.7 Drill Variety

- Mix at least three of: fill-in-the-blank, conjugation, translation (both directions), multiple choice for nuance, sentence transformation
- No single drill type dominates
- Include answer key

## 10.8 Self-Assessment Checklist

- 5–8 "I can…" statements directly mapped to Learning Objectives
- Honest 1–5 rating
- Closing note: "Anything ≤3? Revisit this week before moving on."

---

*End of document. This is the Spanish-specific reference for the language learning project. When adding new languages, mirror this structure with the language-specific facts substituted.*
`;
