// Auto-generated by scripts/embed-references.ts
// Source: thai-curriculum-reference.md
// Do not edit by hand. Re-run the embedding script if the source changes.

export const thaiReference = `# Thai (ภาษาไทย / Phasa Thai) Curriculum Reference

**Purpose.** This is the Thai-specific knowledge base for the language learning project. It applies the universal pedagogical framework (see \`pedagogy-foundations.md\`) to Thai: how Thai is characterized along the seven dimensions, why specific variety decisions were made, the full 180-week curriculum architecture aligned to CEFR levels, Thai-specific resources and assessment paths, and notes on what English speakers find hard about Thai specifically.

**Companion documents.**
- \`pedagogy-foundations.md\` — Universal principles + the seven-dimensional framework
- \`vietnamese-curriculum-reference.md\` — closest analog for Southeast Asian tonal analytic grammar (though Thai has its own script while Vietnamese uses Latin; Thai has 5 tones, Vietnamese 6)
- \`mandarin-curriculum-reference.md\` — closest analog for tone system pedagogy (though Mandarin uses characters while Thai uses an abugida)
- \`korean-curriculum-reference.md\`, \`japanese-curriculum-reference.md\` — closest analogs for elaborate register/honorific systems
- \`hindi-curriculum-reference.md\` — closest analog for an Indic-derived abugida script (the Thai script ultimately descends from Brahmi via Khmer, like Devanagari)
- \`arabic-curriculum-reference.md\` — closest analog for FSI Category IV curriculum length and script-heavy entry
- \`claude-code-prompt.md\` — The build spec for the lesson-generator app
- This document — Thai-specific reference

**Thai's significance for the framework.** Thai extends the framework into Tai-Kadai (Kra-Dai) territory — a language family of ~95 million speakers centered on mainland Southeast Asia, encompassing Thai, Lao, Zhuang (southern China), Shan (Myanmar), and many smaller languages. Thai specifically tests the framework in genuinely new ways: the **Thai script's consonant class system** (where consonants belong to one of three classes — low, mid, high — and tone is determined by the combination of consonant class + tone mark + syllable structure) is one of the most intricate script-tone integration systems among world languages; **polite particles** that are gender-marked and mandatory (ครับ for male speakers, ค่ะ/คะ for female speakers); **Royal Thai (Rachasap)** as a distinct elevated register for talking about or to the monarchy; and **Buddhist monk register** for talking about or to monks. The seven dimensions still apply; significant adaptations are documented throughout.

**Thai compared to prior languages.** Thai shares structural features with Vietnamese (tonal, analytic, classifier-using, modifier-after-noun, Buddhist-cultural-context) but with a completely different writing system and tone-marking strategy. Thai shares cultural-religious features with neighboring Southeast Asian Theravada Buddhist countries (Cambodia, Laos, Myanmar) but is linguistically distinct from each. The **script + tone system together** is the dominant entry-level learning load — comparable to Mandarin character + tone learning but with the difference that the Thai script DETERMINES tone through systematic rules, not requiring separate tone memorization once script mastery is achieved.

**The script-tone integration (addressed upfront).** Thai is one of very few languages in the world where the writing system **encodes tone information through systematic rules** rather than just marking it with diacritics. Once a learner internalizes the consonant class system (44 consonants divided into 3 classes), the 4 tone marks, and the live/dead syllable rules, they can determine the tone of any Thai word by looking at it. This makes the script harder to learn upfront (compared to Vietnamese's straightforward diacritics) but pays substantial dividends: Thai readers don't need to memorize tone with each word the way Mandarin learners do. This unusual trade-off shapes the curriculum's pacing.

---

# PART 1 — THAI LANGUAGE PROFILE

## 1.1 Basic Facts

- **Native speakers:** ~60 million in Thailand; ~70 million worldwide including ethnic Thai populations elsewhere
- **Total speakers (L1 + L2):** ~70-80 million including L2 speakers within Thailand (ethnic Chinese, Malay Muslims, hill tribe communities, etc.)
- **Geographic distribution:** Thailand (national language, near-universal among citizens); significant communities in Thai diaspora — United States (~330K), Australia (~80K), Germany (~100K), United Kingdom (~50K), Sweden, Norway, Canada; ethnic Thai communities in Malaysia, Singapore, Cambodia, Laos, and Myanmar
- **Official status:** Thailand (sole national language); recognized minority language in Cambodia (Northwestern provinces) and historically in Malaysia
- **ISO 639-1 code:** th
- **Linguistic family:** Tai-Kadai (Kra-Dai) → Tai → Southwestern Tai → Thai. Close relatives: Lao (Laos national language, mutually intelligible with Northeastern Thai/Isan), Shan (Myanmar), Zhuang (southern China), Tai Lü (northern Thailand and southwestern China), Tai Dam (Vietnam)
- **Historical significance:** Thai literary tradition dates to the Sukhothai era (13th-14th centuries). King Ramkhamhaeng's stele inscription (1283 CE) is traditionally credited as the origin of Thai script, derived from Khmer script (which derives from Old Mon, which derives from Pallava, ultimately from Brahmi — meaning Thai script shares distant common ancestry with Devanagari, Bengali, and other Indic scripts). Thai has substantial **Sanskrit and Pali vocabulary** absorbed through Buddhist scriptures and royal/formal language; Theravada Buddhism (from Sri Lanka via Sukhothai) is the foundational cultural-religious matrix. Modern Thai literature dates primarily to the late 19th and early 20th centuries with the modernization reforms of Kings Mongkut (Rama IV) and Chulalongkorn (Rama V). The 20th century brought constitutional monarchy (1932), various military governments, the Cold War (Thailand never colonized but heavily influenced by US during Vietnam War era), economic boom and bust cycles, and contemporary political polarization (red-shirt vs. yellow-shirt movements, military coups in 2006 and 2014).

## 1.2 The Seven Dimensions Applied to Thai

### Phonology — *Heavy challenges; tones + aspiration + vowel length all phonemic*

Thai phonology is the central learning load for English speakers — comparable to Mandarin and Vietnamese in difficulty but with distinctive features.

**Tones — five phonemic tones:**

Standard Central Thai has **5 tones**:

| Tone | Thai name | Description | IPA approximation | Example syllable "kha" |
|---|---|---|---|---|
| 1 | สามัญ (sǎaman) | Mid-level | mid | kha (general greeting) |
| 2 | เอก (èek) | Low | low | khà (galangal root) |
| 3 | โท (thoo) | Falling | high-falling | khâ (to kill) |
| 4 | ตรี (trii) | High | high | khá (to be stuck) |
| 5 | จัตวา (jàttawaa) | Rising | low-rising | khǎ (leg) |

Five different words with very different meanings, distinguished only by tone. This is the central pronunciation challenge.

In transliteration (romanization), tones are marked with diacritics:
- No mark = mid tone
- \`à\` = low tone  
- \`â\` = falling tone
- \`á\` = high tone
- \`ǎ\` = rising tone

(Note: different romanization systems use different conventions; this curriculum uses the convention shown above.)

**Aspiration — phonemic:**

Thai distinguishes **aspirated vs. unaspirated** stops, which is phonemic (changes meaning):

| Unaspirated | Aspirated |
|---|---|
| ป (p) | ผ/พ (ph) |
| ต (t) | ถ/ท (th) |
| ก (k) | ข/ค (kh) |
| จ (c, like English "j") | ช (ch) |

For English speakers, this is genuinely difficult: English speakers don't distinguish aspirated vs. unaspirated stops phonemically (we have allophonic aspiration — the "p" in "pin" is aspirated but in "spin" it isn't, yet we hear both as the same /p/). In Thai, this distinction is meaningful: *paa* ปา (to throw) vs. *phaa* ผ้า (cloth) — different words.

**Vowel system — 9 pure vowels + 3 diphthongs, with phonemic length:**

| Short | Long | Examples |
|---|---|---|
| อะ /a/ | อา /aː/ | dam (black) vs. daam (handle) |
| อิ /i/ | อี /iː/ | sit (six) vs. siit (color) |
| อึ /ɯ/ | อือ /ɯː/ | high central unrounded — novel for English |
| อุ /u/ | อู /uː/ | |
| เอะ /e/ | เอ /eː/ | |
| แอะ /ɛ/ | แอ /ɛː/ | |
| โอะ /o/ | โอ /oː/ | |
| เอาะ /ɔ/ | ออ /ɔː/ | |
| เออะ /ə/ | เออ /əː/ | |

Plus diphthongs: เอีย /ia/, เอือ /ɯa/, อัว /ua/

**Vowel length is phonemic** — short and long vowels distinguish words. This is unusual for English speakers (English vowel length is allophonic, not phonemic).

**Consonants:**

- 21 consonant phonemes
- Aspirated/unaspirated distinctions as above
- Most consonants familiar to English speakers
- **Final consonants severely limited** — only /p, t, k, m, n, ŋ, j, w/ can end a syllable (plus phonetic glottal stop)
- Final stops (/p, t, k/) are unreleased — no audible breath release; English speakers often release them inappropriately
- Initial /ŋ/ ("ng-") is common at word start (a familiar challenge from Vietnamese, Filipino, etc.)
- Initial consonant clusters limited; some are common (*kr-, kh-, pr-, tr-*)

**Syllable structure — live vs. dead:**

This is critical for the tone system. Thai syllables are categorized as:

- **Live syllables (คำเป็น)** — end in long vowel, semivowel (j, w), or sonorant final (m, n, ŋ)
- **Dead syllables (คำตาย)** — end in short vowel or stop (p, t, k)

Whether a syllable is "live" or "dead" affects which tones are possible.

**Implication:** Heavy pronunciation focus in early weeks. Tones get dedicated treatment Weeks 2-4. Aspiration distinction explicit Week 1. Vowel length pairs introduced Week 1 and reinforced. The high central unrounded vowel (อึ/อือ) needs deliberate work (same as Vietnamese ư). Final consonant unreleasedness explicit. Live/dead syllable distinction taught when introducing the tone-mark system Weeks 6-8.

### Writing System — *Thai script (an abugida) with the consonant class system; one of the most intricate script-tone integrations in any language*

Thai uses its own indigenous script (อักษรไทย akson thai), a true abugida ultimately derived from Brahmi via Khmer. Created by King Ramkhamhaeng (traditional attribution, 1283 CE) with substantial modifications over the centuries. The script is **logical and rule-governed** but the rules are intricate.

**The basic inventory:**

- **44 consonants** (some are functionally redundant — representing the same sound but used for words of different etymological origins, primarily distinguishing Sanskrit/Pali loanwords from native Thai)
- **15 vowel symbols** (combined to make all vowel sounds; vowels written in various positions relative to the consonant)
- **4 tone marks** (mai ek อ่, mai tho อ้, mai tri อ๊, mai chattawa อ๋)
- **Other symbols** — abbreviation mark, repetition mark, special characters

**The consonant class system — central to reading Thai:**

This is what makes Thai script unique. The 44 consonants are divided into three classes:

| Class | Number | Examples (with English-equivalent sound) |
|---|---|---|
| **Low class (อักษรต่ำ)** | 24 letters | ค ค ฆ ง ช ซ ฌ ญ ฑ ฒ ณ ท ธ น พ ฟ ภ ม ย ร ล ว ฬ ฮ |
| **Mid class (อักษรกลาง)** | 9 letters | ก จ ด ต บ ป อ ฎ ฏ |
| **High class (อักษรสูง)** | 11 letters | ข ฃ ฉ ฐ ถ ผ ฝ ศ ษ ส ห |

**Tone determination — this is the central rule system:**

The tone of a Thai syllable is determined by **three factors interacting**:
1. **Consonant class** (low, mid, or high)
2. **Tone mark** (if any — mai ek, mai tho, mai tri, mai chattawa)
3. **Syllable type** (live or dead — determined by ending)

A simplified tone determination table (for live syllables):

| Consonant class | No tone mark | mai ek | mai tho | mai tri | mai chattawa |
|---|---|---|---|---|---|
| **Mid class** | mid | low | falling | high | rising |
| **High class** | rising | low | falling | — | — |
| **Low class** | mid | falling | high | — | — |

For dead syllables, the rules differ (high-class dead syllables get low tone; low-class dead syllables can get high or falling depending on vowel length; etc.).

**Why this matters pedagogically:** Once a learner internalizes:
1. Which consonants belong to which class (memorization task)
2. What the 4 tone marks look like
3. Live vs. dead syllable rules

...they can determine the tone of ANY Thai word by looking at it, without needing to memorize tones per word. This is the opposite of Mandarin (where every character's tone must be memorized) and even more systematic than Vietnamese (where diacritics show tone directly but don't predict it from rules).

**Vowel placement — non-linear:**

Unlike Latin-alphabet languages where vowels appear after consonants, Thai vowels appear in **various positions** relative to the consonant:

- **Before** the consonant: เ (e/ee), แ (ɛ/ɛɛ), โ (o/oo), ใ (ai), ไ (ai)
- **After** the consonant: ะ, า, อ
- **Above** the consonant: ิ (i), ี (ii), ึ (ɯ), ื (ɯɯ), ั
- **Below** the consonant: ุ (u), ู (uu)
- **Surrounding** the consonant: เ◌า (au), เ◌าะ (ɔ short), เ◌ือ (ɯa)

This non-linear reading is initially disorienting for learners used to left-to-right linear scripts.

**No spaces between words within sentences:**

Thai text does not separate words with spaces. Spaces are used at sentence-like boundaries (similar to paragraph or list breaks in other languages). This means learners must develop **word-segmentation skill** — recognizing where words begin and end in a continuous string of characters. This is significantly easier than it sounds (Thai word boundaries are usually clear from context and grammar) but disorienting at first.

**Sanskrit/Pali loanwords:**

Many Thai words come from Sanskrit and Pali (the language of Theravada Buddhist scripture). These loanwords often retain Sanskrit/Pali spelling patterns — including silent letters (marked with the *karan* mark อ์) and consonants in non-Thai-typical positions. Reading these requires recognizing the Indo-Aryan-influenced patterns.

**Historical context:**
- **Script created** by King Ramkhamhaeng (traditional attribution), 1283 CE, derived from Old Khmer script
- **Continuous development** through Ayutthaya and Bangkok periods
- **Modernization reforms** under King Chulalongkorn (Rama V, 1868-1910) standardized the script and educational use
- **Modern Thai script** essentially the same as developed in the early 20th century

**Implication:** Thai script taught systematically from Week 1 — alphabet introduction; class system explicit. Tone-determination rules introduced Weeks 6-10 progressively (mid class first, then high, then low). Transliteration used in early weeks for tone marking but learners weaned off by Week 10-12. Reading practice essential from Week 5. The script is the central Week-1-through-15 task; once mastered, Thai becomes much more accessible.

### Morphology — *Analytic/isolating, like Vietnamese; minimal inflection*

Thai is **analytic** like Vietnamese — words don't change form for tense, number, gender, case, etc. Grammar conveyed through:
1. Word order
2. Separate function words (particles, auxiliaries, classifiers)
3. Context

**Verbs don't conjugate:**

The verb กิน (gin, "to eat") appears identically in all contexts:

- ฉันกิน (chǎn gin) — "I eat" (present)
- ฉันกินแล้ว (chǎn gin láew) — "I ate" / "I have eaten" (with แล้ว "already")
- ฉันกำลังกิน (chǎn gamlang gin) — "I'm eating" (with กำลัง "currently")
- ฉันจะกิน (chǎn jà gin) — "I will eat" (with จะ "will")
- ฉันเคยกิน (chǎn khəəi gin) — "I have eaten before" (with เคย "have ever")
- เขากิน (khǎo gin) — "He eats" (same verb form, just different pronoun)

**No noun inflection:**
- Number: not marked on nouns; context or classifier indicates
- Gender: doesn't exist
- Case: doesn't exist; word order signals grammatical role

**Tense/aspect/modality particles** (analogous to Vietnamese):

- **แล้ว** (láew) — already, completed (after the verb)
- **กำลัง** (gamlang) — currently, progressive (before the verb)
- **จะ** (jà) — will, future intention (before the verb)
- **เคย** (khəəi) — have ever, experiential (before the verb)
- **กำลังจะ** (gamlang jà) — about to (before the verb)
- **ยัง** (yang) — still, yet, not yet (with ไม่ for negation)
- **ได้** (dâai) — was able to / managed to (after the verb; also "get/obtain")
- **เพิ่ง** (phə̂ng) — just (recently, before the verb)

Modal verbs:
- **สามารถ** (sǎamâat) — can, be able to (more formal)
- **ได้** (dâai) — can (informal)
- **ต้อง** (tɔ̂ng) — must, have to
- **ควร** (khuan) — should
- **อยาก** (yàak) — want to
- **ต้องการ** (tɔ̂ngkaan) — need, want (more formal)

**Classifiers — required with numbers and demonstratives:**

Like Vietnamese and Mandarin, Thai requires classifiers. The most common:

- **คน** (khon) — for people: *นักเรียนสองคน* "two students"
- **ตัว** (tua) — for animals, items of clothing, furniture: *แมวสามตัว* "three cats"
- **เล่ม** (lêm) — for books, knives, candles: *หนังสือสองเล่ม* "two books"
- **ใบ** (bai) — for leaves, paper, tickets, hats, fruits: *ตั๋วสองใบ* "two tickets"
- **คัน** (khan) — for vehicles, umbrellas, items with handles: *รถสองคัน* "two cars"
- **อัน** (an) — for generic small items (default): *อันนี้* "this one"
- **ลูก** (lûuk) — for round things, fruits, balls: *ส้มสองลูก* "two oranges"
- **เครื่อง** (khrɯ̂ang) — for machines, appliances, instruments: *คอมพิวเตอร์เครื่องนี้* "this computer"
- **องค์** (ong) — for monks, Buddha images, royals (Royal/Buddhist register): *พระสององค์* "two monks"
- **แห่ง** (hɛ̀ng) — for places, locations: *ที่นี่สองแห่ง* "two places here"

Classifier choice is meaningful — using the wrong classifier marks you as a learner or can sound strange/disrespectful.

**Reduplication:**

Thai uses reduplication (with the *mai yamok* symbol ๆ to indicate it):

- เด็ก ๆ (dek dek) — children (plural emphasis)
- เร็ว ๆ (rew rew) — quickly (intensified)
- บ่อย ๆ (bɔ̀i bɔ̀i) — often (intensified)

**Sino-Thai vocabulary layer:**

A substantial portion of Thai vocabulary comes from Chinese (especially Teochew Chinese, due to the historical immigration of Chinese to Thailand). Common in food vocabulary, business, and many everyday terms.

**Sanskrit/Pali vocabulary layer (formal/Buddhist register):**

Much of Thai's formal, religious, and royal vocabulary is Sanskrit or Pali in origin. This parallels how Vietnamese has Sino-Vietnamese formal vocabulary, Japanese has Chinese-derived kanji compounds, Korean has Sino-Korean vocabulary. Examples:

- กรุณา (karuṇaa, from Sanskrit *karuṇā*) — please, kindness
- ขอบคุณ (khɔ̀ɔp khun) — thank you (mixing Thai and Sanskrit)
- อาจารย์ (aajaan, from Sanskrit *ācārya*) — teacher
- มหาวิทยาลัย (mahaa-witthayaa-lai, from Sanskrit *mahā-vidyālaya*) — university (literally "great-knowledge-place")

**Compound words:**

Thai forms many compounds, especially from Sanskrit/Pali roots. The compound *รัฐมนตรี* (rathamontrii) "minister" combines *รัฐ* (state) and *มนตรี* (counselor) — both Sanskrit-derived.

**Implication:** Verb particles taught Weeks 11-13 (mirroring Vietnamese). Classifiers introduced Week 16 with sustained practice. Reduplication noted from A2. Sino-Thai and Sanskrit-Pali vocabulary patterns introduced at B1 with explicit etymology. The analytic nature is a learner relief (no conjugation tables!) but requires conscious thought about classifier choice and particle placement.

### Word Order — *SVO with modifier-after-noun; topic-comment common*

Thai is **SVO** (Subject-Verb-Object), like English and Vietnamese.

- ฉันกินข้าว (chǎn gin khâao) — "I eat rice" (S-V-O)
- เขาอ่านหนังสือ (khǎo àan nǎngsɯ̌ɯ) — "He reads books" (S-V-O)

**Modifiers FOLLOW the noun** (like Vietnamese, French, Spanish):

- บ้านใหญ่ (bâan yài) — "house big" (= big house)
- รถสีแดง (rót sǐi dɛɛng) — "car color red" (= red car)
- คนไทย (khon thai) — "person Thai" (= Thai person)
- หนังสือดี (nǎngsɯ̌ɯ dii) — "book good" (= good book)

**Possessive constructions** use ของ (khɔ̌ɔng) "of":

- หนังสือของฉัน (nǎngsɯ̌ɯ khɔ̌ɔng chǎn) — "book of me" (= my book)
- บ้านของเขา (bâan khɔ̌ɔng khǎo) — "house of him" (= his house)

**Relative clauses follow the noun** with ที่ (thîi) "that/which":

- คนที่ฉันรู้จัก (khon thîi chǎn rúu jàk) — "person whom I know"
- หนังสือที่ฉันอ่าน (nǎngsɯ̌ɯ thîi chǎn àan) — "book that I read"

**Topic-comment structure** common in casual speech:

- หนังสือเล่มนี้ ฉันอ่านแล้ว (nǎngsɯ̌ɯ lêm níi, chǎn àan láew) — "This book, I've already read [it]"

**Question formation:**

- **Yes/no questions** with various particles: *...ไหม (mǎi)*, *...หรือ (rɯ̌ɯ)*, *...หรือเปล่า (rɯ̌ɯ plàao)*
- **Wh-questions** with question words in position (no fronting like English):
  - อะไร (à-rai) — what
  - ใคร (khrai) — who
  - ที่ไหน (thîi-nǎi) — where
  - เมื่อไหร่ (mɯ̂a-rài) — when
  - ทำไม (tham-mai) — why
  - อย่างไร / ยังไง (yàang-rai / yang-ngai) — how
  - เท่าไหร่ / กี่ (thâo-rài / gìi) — how much/many

**Implication:** SVO taught from Week 5. Modifier-after-noun pattern Week 18. Question structures Weeks 8-9. Topic-comment introduced at A2.

### Register — *Polite particles + Royal Thai + Buddhist monk register*

Thai has one of the most elaborate register systems in the curriculum, comparable to Japanese keigo and Korean honorifics in complexity but with distinctive Thai features.

**Polite particles (mandatory in polite contexts):**

The most distinctive Thai politeness feature: **gendered, sentence-final polite particles** that must be added to make speech polite.

- **ครับ (khráp)** — used by male speakers at end of sentences/utterances
- **ค่ะ (khâ)** — used by female speakers at end of declarative sentences (falling tone)
- **คะ (khá)** — used by female speakers at end of questions (high tone)

These are not optional in polite contexts. Omitting them sounds rude or overly familiar. Using the wrong-gender particle marks you as a learner (foreigners using both consciously is sometimes seen as a feature/charm).

Example: ขอบคุณครับ (khɔ̀ɔp khun khráp) — "Thank you" said by a man
ขอบคุณค่ะ (khɔ̀ɔp khun khâ) — "Thank you" said by a woman

**Other polite/casual particles:**

- **นะ (ná)** — softens, makes more friendly
- **สิ (sì)** — emphatic (sometimes commanding)
- **ละ (lá)** — already, but with nuance
- **เถอะ (thə̀ə)** — let's, suggesting

**Royal Thai (Rachasap, ราชาศัพท์):**

A complete elevated vocabulary used when **speaking about or to the royal family**. Different verbs, nouns, and pronouns. This is genuinely a separate vocabulary system — not just register shifts but actually different words. For example:

- "to eat" — กิน (gin) regular vs. เสวย (sǎwə̌ə̌əi) royal
- "to walk" — เดิน (dəən) regular vs. ทรงพระดำเนิน (song phrá damnəən) royal
- "to die" — ตาย (taai) regular vs. สวรรคต (sǎwankhót) royal (for royalty)
- "head" — หัว (hǔa) regular vs. พระเศียร (phrá sǐan) royal
- "hand" — มือ (mɯɯ) regular vs. พระหัตถ์ (phrá hàt) royal

Rachasap is required when speaking or writing about the royal family. Failing to use Rachasap when discussing the King, Queen, or other royals is socially noticed and can be considered disrespectful. **This intersects with lèse-majesté law** — Thailand has strict laws against speaking ill of the monarchy (see Sensitivity section).

**Buddhist monk register:**

Similar to Rachasap, a distinct vocabulary used when speaking about or to Buddhist monks:

- "to eat" — ฉัน (chǎn) for monks (regular: กิน)
- "to die" — มรณภาพ (mɔɔrá-ná-phâap) for monks
- Special pronouns when addressing monks

Less elaborate than Rachasap but parallel in concept.

**Pronoun system — varies by formality, gender, age:**

| Term | English equivalent | Notes |
|---|---|---|
| ผม (phǒm) | I (male, polite-neutral) | Default for male speakers in polite contexts |
| ดิฉัน (dìchǎn) | I (female, formal) | Female formal |
| ฉัน (chǎn) | I (female casual / informal both genders) | Casual; can sound feminine when used by males |
| คุณ (khun) | you (polite-neutral) | Universal polite "you" |
| เธอ (thəə) | you (intimate/casual) / she | Multipurpose |
| เขา (khǎo) | he/she (third person) | Standard |
| ท่าน (thâan) | he/she (formal/respectful) | For respected persons |
| มัน (man) | it/he/she (informal/sometimes rude) | Casual or pejorative |
| เรา (rao) | we / I (casual self-reference) | Multipurpose |
| พวกคุณ (phûak khun) | you (plural, polite) | Group "you" |
| พี่ (phîi) | older sibling (used as pronoun) | Like Vietnamese anh/chị |
| น้อง (nɔ́ɔng) | younger sibling (used as pronoun) | Like Vietnamese em |

Thai uses kin terms as pronouns extensively (similar to Vietnamese), but the Thai system is less elaborate than the Vietnamese pronoun system and the polite particles do much of the work.

**Other register features:**

- **Sanskrit/Pali vocabulary** for formal, religious, royal contexts (parallel to Sino-Vietnamese in Vietnamese)
- **Sino-Thai vocabulary** also present (less elaborate than Sanskrit/Pali layer for register)
- **Regional vocabulary** — Northern (Lanna), Northeastern (Isan), Southern Thai have distinctive vocabulary
- **Code-switching with English** common in urban Bangkok contexts

**Implication:** Polite particles taught Week 2 — non-negotiable; gendered nature explained. Pronoun system Weeks 5-6. Rachasap introduced descriptively at B1 (Week 60+) — receptive understanding emphasized; productive use only needed if directly speaking to/about royalty. Buddhist monk register noted at B1.

### Cultural-Pragmatic Distance — *Distant; Theravada Buddhist context centrally*

Thai culture is distinctly Theravada Buddhist with strong monarchy reverence, Sanskrit-influenced literary tradition, and Sinified commercial elements. Quite distant from English-speaker defaults.

- **Theravada Buddhism (~93%)** — the dominant cultural-religious framework; visible everywhere (temples, monks, daily merit-making, Buddhist holidays); differs from Mahayana Buddhism (Vietnam, China, Japan, Korea) in significant doctrinal and practical ways
- **Monarchy reverence** — the Thai royal family is deeply revered; King Bhumibol (Rama IX, reigned 1946-2016) was the world's longest-reigning monarch at his death; current King Vajiralongkorn (Rama X); Rachasap vocabulary required; lèse-majesté laws strict
- **The wai (ไหว้)** — traditional Thai greeting, hands pressed together at chest with slight bow; height of hands and depth of bow indicates respect level; learned early
- **Smile culture** — "Land of Smiles" is more than a tourism slogan; Thais have many specific smiles for different contexts (smile of embarrassment, smile of apology, smile to defuse, smile of genuine pleasure); reading these is a cultural skill
- **"Greng jai" (เกรงใจ)** — consideration for others' feelings, reluctance to impose, not wanting to inconvenience; a foundational cultural concept; affects communication patterns (indirectness)
- **"Mai pen rai" (ไม่เป็นไร)** — "never mind / it's okay / no problem" — cultural philosophy of letting things go, not making issues out of small matters
- **"Sanuk" (สนุก)** — fun, enjoyment as a cultural value; Thais expect work and life to have *sanuk*; activity without sanuk is suspect
- **Hierarchical society** — age, status, education, position all matter; patron-client relationships pervasive; deference to elders and superiors elaborate
- **Avoiding direct confrontation** — face-saving (similar to broader East Asian patterns) but with distinctive Thai inflections; conflict expressed indirectly; harmony valued
- **Hospitality (ใจดี jaidii)** — kindness and generosity expected; sharing food
- **Food culture** — central to Thai identity; **regional cuisines distinctly different**:
  - **Central Thai** — Bangkok cuisine; pad thai, tom yum, green curry, mango sticky rice
  - **Northern (Lanna)** — Chiang Mai cuisine; khao soi, sai oua, nam prik nuum; less spicy, more herbal
  - **Northeastern (Isan)** — Lao-influenced; som tam (papaya salad), larb, gai yang, sticky rice; very spicy
  - **Southern** — Malay-influenced; massaman curry, gaeng som; coconut and turmeric; spicy
  - Rice central; chilies central; fish sauce central
- **Major holidays:**
  - **Songkran (April 13-15)** — Thai New Year; water festival (originally water-pouring on Buddha images and elders' hands, now also street water fights); biggest holiday
  - **Loy Krathong (November)** — water-lantern festival; floating krathongs on rivers
  - **Buddhist Lent (Khao Phansa, July-October)** — three-month rains retreat for monks
  - **Buddhist holy days** — observed throughout year
  - **King's birthday, Queen's birthday** — national holidays
  - **Constitution Day (December 10)** — 1932 constitutional monarchy
- **Geographic regions with distinct cultures:**
  - **Central Plain** — Bangkok, Ayutthaya; the "mainstream" Thai identity
  - **Northern Thailand (Lanna)** — Chiang Mai, Chiang Rai; distinctive Lanna culture, Northern Thai dialect (Kham Muang)
  - **Northeastern Thailand (Isan)** — Lao-related culture, Lao-related language (Isan/Northeastern Thai), distinctive food (som tam, larb), poverty historically
  - **Southern Thailand** — Malay-Muslim minority (~10% of southern population); ongoing low-level insurgency; multicultural Hat Yai, Phuket, Krabi
- **Ethnic diversity** — Han Chinese descent significant (5-15% depending on counting; Chinese-Thai are extensively integrated); Malay-Muslim minority (~4-5% of total population, concentrated in south); hill tribes in the north (Karen, Hmong, Akha, Lahu, Lisu); Khmer minority in northeast
- **Modern Thailand** — post-WWII economic transformation; Cold War context (US military presence during Vietnam War); 1997 Asian Financial Crisis impact; political polarization (yellow shirts vs. red shirts, 2000s-2010s); military coups 2006 and 2014; ongoing political tensions; tourism economy; tech and manufacturing growth; aging population concerns
- **Sensitive topics:**
  - **Monarchy** — **lèse-majesté laws (มาตรา 112)** make it illegal to defame, insult, or threaten the King, Queen, heir, or regent; penalties up to 15 years per count; vigorously enforced; foreigners have been convicted; **this affects what learners should produce in Thai about the royal family**
  - **Southern conflict** — ongoing insurgency in Yala, Pattani, Narathiwat (Malay-Muslim southern provinces) since 2004
  - **Political polarization** — red shirts (rural, pro-Thaksin) vs. yellow shirts (urban, royalist); military involvement; pro-democracy movements (2020-present)
  - **Sino-Thai vs. Thai identity** — generally well-integrated but sometimes contested
  - **LGBT+ situation** — relatively accepting culturally; legal recognition slower
  - **Sex industry** — Bangkok and Pattaya context; mostly avoid in standard curriculum

**Implication:** Very high cultural-note density. Buddhist context introduced from Week 2 (wai). "Greng jai," "mai pen rai," "sanuk" taught explicitly at B1. Regional Thai cuisine and culture rotation throughout. Royal language and lèse-majesté addressed neutrally at B1 (Week 62) with clear practical guidance for learners. Modern Thai dynamism (tech, contemporary arts, tourism) alongside traditional context.

### Resource Availability — *Major language with mature resource ecosystem*

Thai has a well-developed learning ecosystem:

- **Free YouTube content** — ThaiPod101 (extensive free content; also paid), Learn Thai with Mod (excellent), Pailin's Kitchen (Thai with cooking), Mike Pinpinto, Stu Jay Raj (linguistic depth)
- **ThaiPod101** — comprehensive paid platform; one of the better Pod101 series
- **Textbooks** — *Thai for Beginners* (Becker, Paiboon Publishing) — popular starter; *Foundations of Thai* (Marvin Brown) — classic AUA Language Center materials; *Linguaphone Thai*; *Thai Reference Grammar* (Smyth) — academic reference; *Thai: An Essential Grammar* (Smyth, Routledge); *Teach Yourself Thai* (Smyth)
- **Apps** — Duolingo Thai (decent quality), Drops, Memrise, Mango Languages, Pimsleur; Ling has good Thai course; Drops emphasizes script learning well
- **Dictionaries** — *Royal Institute Dictionary* (the authoritative Thai dictionary); *Thai-English Student's Dictionary* (Haas); Thai-English-Thai online dictionaries (Thai2English.com, ThaiCloud.com)
- **Native media** — Thai PBS (educational programming), Channel 3, Channel 7, Channel 9, GMM Grammy entertainment; *Thai Rath, Matichon, Bangkok Post (English), The Nation (English)* newspapers; Thai cinema (large industry); T-pop music (BLACKPINK's Lisa is Thai); abundant Thai YouTube
- **Tutoring** — iTalki has many Thai tutors (Thailand-based, very affordable: $5-15/hr); strong recommendation; AUA Language Center (Bangkok) is famous for natural-method Thai instruction
- **In-country options** — AUA Language Center (Bangkok and Chiang Mai); Chulalongkorn University Thai program (premier academic Thai); Walen Thai School; Pro Language; UNITY Thai School; many private schools throughout Thailand; intensive immersion options popular
- **Religious materials** — extensive Buddhist materials in Thai (chanting books, sutta translations, etc.) for those interested in Buddhist study

**Implication:** Specific high-quality recommendations available throughout. iTalki rates particularly favorable. In-Thailand language schools (AUA especially) offer immersion that's harder to replicate elsewhere. ThaiPod101 unusually well-developed.

---

# PART 2 — VARIETY DECISION

## 2.1 The Decision

**Standard Central Thai (Bangkok)** as the productive base — universal in education, media, government, and as the unmarked standard. Northern (Lanna), Northeastern (Isan — actually a Lao-related separate language), and Southern Thai as cultural-linguistic awareness only.

## 2.2 Rationale

- **Bangkok Central Thai is universal Standard Thai** — taught throughout Thailand; used in all official contexts and national media
- **Universal intelligibility** — every Thai speaker understands Standard Thai (it's the medium of education)
- **Resource availability** — overwhelmingly Standard Thai
- **No real alternative for productive learning** — unlike Mandarin (Simplified vs. Traditional characters), Spanish (LatAm vs. Spain), or Vietnamese (Northern vs. Southern), Thai doesn't have a comparably consequential variety choice; Central Thai is uncontroversially the standard

## 2.3 The Other Thai Varieties (Cultural-Linguistic Awareness)

**Northern Thai / Kham Muang (คำเมือง, ภาษาเหนือ)** — spoken in Chiang Mai, Chiang Rai, and northern provinces; distinctive vocabulary and accent; Lanna culture; Lanna script historically (now mostly written in Thai script); learners going to northern Thailand benefit from awareness but can function in Standard Thai.

**Northeastern Thai / Isan (ภาษาอีสาน)** — spoken in northeastern Thailand (~22M speakers); **technically a Lao variant** (Isan and Lao are mutually intelligible; both are Tai-Kadai but closer to each other than to Standard Thai); culturally distinct (Isan culture is Lao-influenced); Isan people are bilingual in Thai (universal) and Isan; Isan vocabulary and pronunciation distinctive.

**Southern Thai (ภาษาใต้)** — spoken in southern Thailand; faster speech, distinctive pronunciation, some unique vocabulary; Malay-Muslim south has additional Malay influences in vocabulary; learners in southern Thailand benefit from awareness.

**Phasa Phak Kang (Central Thai)** — what this curriculum teaches; the unmarked national standard.

## 2.4 Other Tai-Kadai Languages (NOT Thai)

The Tai-Kadai family includes many languages that are NOT Thai despite being related:

- **Lao** — Laos national language; ~30M speakers including Isan in Thailand; closely related to Isan/Northeastern Thai
- **Shan** — Myanmar (Shan State); ~3M speakers; related to Thai
- **Zhuang** — southern China (Guangxi); ~16M speakers; the largest Tai-Kadai language
- **Tai Lü, Tai Nüa, Tai Dam** — various smaller Tai languages
- **Various other Tai languages** in Vietnam, China, Laos

These are NOT Thai dialects but separate languages within the Tai-Kadai family. Each would warrant separate curriculum if covered.

## 2.5 What This Curriculum Excludes

- **Other Tai-Kadai languages** (Lao, Shan, Zhuang, etc.) — separate languages
- **Lanna script** — historical script for Northern Thai; cultural awareness only at C2
- **Khom Thai script** — historical Cambodian-derived script used for sacred texts; cultural awareness only at C2
- **Sukhothai-era classical Thai** — covered briefly at C2 (Ramkhamhaeng inscription)

---

# PART 3 — CURRICULUM ARCHITECTURE

## 3.1 At a Glance

- **Total length:** 180 weeks (~3.5 years at one lesson per week)
- **Pacing:** one lesson per week plus daily practice (45–60 min/day recommended — similar to Korean/Japanese)
- **Total study time at recommended pace:** ~1,000–1,200 hours, matching FSI's Category IV estimate
- **Level structure:** Six CEFR levels (A1–C2)

## 3.2 The Six Levels

| Level | Weeks | Span | CEFR Goal | Target Vocab |
|---|---|---|---|---|
| A1 — Foundations | 1–25 | 25 weeks | A1 | ~800 words |
| A2 — Elementary | 26–50 | 25 weeks | A2 | ~1,800 words |
| B1 — Intermediate | 51–90 | 40 weeks | B1 | ~3,500 words |
| B2 — Upper-Intermediate | 91–125 | 35 weeks | B2 | ~5,500 words |
| C1 — Advanced | 126–155 | 30 weeks | C1 | ~7,500 words |
| C2 — Mastery | 156–180 | 25 weeks | C2 | 10,000+ words |

## 3.3 Pacing Philosophy

- **A1 (Weeks 1–25):** **The Thai script gets systematic introduction** Weeks 1-15. Tones taught alongside script (Weeks 2-4 initial, then through tone-mark rules Weeks 6-10). Polite particles Week 2. Pronoun system Weeks 5-6. Tense particles Weeks 11-13. Classifiers Week 16. End at A1 readiness.
- **A2 (Weeks 26–50):** All major tense/aspect particles. Modal verbs. Verb extensions. Reading begins shifting to native materials (with extensive script practice). Buddhist register awareness.
- **B1 (Weeks 51–90):** **Longest level (40 weeks).** Script fluency consolidated. Royal Thai (Rachasap) introduced receptively. Cultural concepts taught.
- **B2 (Weeks 91–125):** Literary register; news Thai; classical and contemporary literature; cinema; music.
- **C1 (Weeks 126–155):** Grammar lightens. Specialized fields, Thai literature, classical Buddhism.
- **C2 (Weeks 156–180):** Classical scripts (Khom, Lanna) awareness, Sukhothai-era Thai, regional varieties mastery, capstone (Week 180).

---

# PART 4 — WEEK-BY-WEEK OVERVIEW

The full structured data will live in \`lib/curricula/thai.ts\` (to be built). Early weeks detailed; later weeks grouped.

## 4.1 Level A1 — Foundations (Weeks 1–25)

| W | Title | Core focus |
|---|---|---|
| 1 | **Thai script intro + pronunciation overview** | The 44 consonants in overview; vowel placement system (before/after/above/below); first 10 mid-class consonants; basic syllable reading; pronunciation of consonants and vowels |
| 2 | **Tones Part 1: The five tones** | Mid, low, falling, high, rising; listening discrimination; minimal pairs (mai/mài/mâi/mái/mǎi); polite particles ครับ/ค่ะ introduced (mandatory for politeness) |
| 3 | **Tones Part 2: Production** | Sustained tone production practice; combining tones; tone-pair drilling |
| 4 | **Tones Part 3: In context** | Tones in connected speech; tone sandhi (minor in Thai); tone consistency |
| 5 | **Greetings + pronoun introduction** | สวัสดี (sàwàtdii) hello; common greeting patterns; ผม/ฉัน/คุณ/เขา pronouns; gendered politeness in pronoun choice |
| 6 | **Tone marks Part 1: Mid-class consonants** | The four tone marks (mai ek, mai tho, mai tri, mai chattawa); how they work with mid-class consonants; live vs. dead syllables; first reading of toned words |
| 7 | **Tone marks Part 2: High-class consonants** | The 11 high-class consonants; tone determination with high class; the rising-default tone |
| 8 | **Tone marks Part 3: Low-class consonants** | The 24 low-class consonants; tone determination with low class; the mid-default tone; the importance of consonant class for reading |
| 9 | **Reading consolidation** | Mixed-class reading practice; common words encoding the tone system in action; the goal: read any Thai text and determine tone correctly |
| 10 | Self-introduction + basic verbs | ฉันชื่อ... (chǎn chɯ̂ɯ...) "My name is..."; first 20 high-frequency verbs (กิน, ไป, มา, พูด, อ่าน, ฟัง, ทำ, ดู, เป็น, มี, etc.) |
| 11 | **Past tense particle แล้ว** | The completed/perfective marker; placement; การใช้ ไปแล้ว, มาแล้ว, etc. |
| 12 | **Present continuous กำลัง** | The progressive marker; placement before verb |
| 13 | **Future tense จะ** | The future marker; placement before verb |
| 14 | Numbers — Thai and Sino-Thai | Thai numbers (หนึ่ง สอง สาม สี่ ห้า); Sino-Thai for prices/some contexts; reading number words |
| 15 | Time, dates, calendar | Telling time; Thai numerical calendar (Buddhist Era — BE 2569 vs CE 2026); days; months |
| 16 | **Classifiers introduction** | The classifier system; คน (people), ตัว (animals), เล่ม (books), ใบ (paper/tickets), อัน (generic); using with numbers |
| 17 | More classifiers | คัน, ลูก, เครื่อง, แห่ง, ขวด (bottles), หลัง (houses); learning the right classifier per noun |
| 18 | **Modifier-after-noun word order** | The Romance-like pattern: บ้านใหญ่ (house big = big house); contrast with English |
| 19 | Demonstratives | นี่ (this — pronoun) นั่น/โน่น (that); placement after noun: หนังสือเล่มนี้ (this book) |
| 20 | Possessives with ของ | ของ (khɔ̌ɔng) "of"; หนังสือของฉัน (my book); ของ + pronoun structure |
| 21 | Yes/no questions and answers | ...ไหม? (mǎi?) — yes/no question marker; ใช่/ไม่ใช่ (yes/no); affirmative/negative responses |
| 22 | Wh-questions | อะไร, ใคร, ที่ไหน, เมื่อไหร่, ทำไม, อย่างไร/ยังไง, เท่าไหร่/กี่; in their natural position |
| 23 | Negation with ไม่ | ไม่ + verb for "not"; ไม่ใช่ for "not be"; basic negation patterns |
| 24 | Modal verbs intro | สามารถ/ได้ (can), ต้อง (must), ควร (should), อยาก (want to) |
| 25 | **A1 Review and consolidation** | Mock A1; ~800 vocab; all 5 tones reasonable; Thai script readable (limited speed); basic conversations possible with polite particles |

## 4.2 Level A2 — Elementary (Weeks 26–50)

| W | Title | Core focus |
|---|---|---|
| 26 | Tense particles deeper | เคย (ever, experiential), ยัง (still), กำลังจะ (about to), เพิ่ง (just) |
| 27 | Complex modals | The versatile ได้; ต้องการ; conditional senses; idiomatic uses |
| 28 | Imperative and requests | Forming imperatives; ขอ (request: "may I"); กรุณา (please, formal); ช่วย (help me to...) |
| 29 | Conjunctions | และ (and), หรือ (or), แต่ (but), เพราะ (because), ถ้า (if), เพื่อ (in order to); sentence connection |
| 30 | Subordinate clauses | เมื่อ (when), ก่อน (before), หลังจาก (after); time/order clauses |
| 31 | Relative clauses with ที่ | คนที่ฉันรู้จัก (person whom I know); relative constructions |
| 32 | Comparative and superlative | กว่า (more than), ที่สุด (most), เท่ากับ (equal to); degree expressions |
| 33 | Reduplication patterns | ๆ symbol; plural/emphasis/intensity reduplication; common patterns |
| 34 | Adverbs of frequency and time | บ่อย, นาน ๆ ครั้ง, ไม่เคย, เสมอ; วันนี้, พรุ่งนี้, เมื่อวาน, สัปดาห์หน้า |
| 35 | Spatial vocabulary | ใน (inside), บน (on/above), ใต้ (under), หน้า (in front of), หลัง (behind), ข้าง (beside) |
| 36 | Workplace and professions | Job titles; workplace courtesy; the pi/nong system in workplaces; Thai business culture intro |
| 37 | Daily routine and household | Domestic vocabulary; Thai family structure terms; multigenerational households |
| 38 | Travel and transportation | Bangkok BTS/MRT; taxis; tuk-tuks; motorbike taxis (วินมอเตอร์ไซค์); regional travel |
| 39 | **Thai cuisine — comprehensive** | Pad thai, tom yum, green curry, mango sticky rice; regional cuisines (Central, Northern, Isan, Southern); ordering; spice levels; vegetarian options; food etiquette |
| 40 | Songkran and major holidays | Thai New Year (April); cultural significance; water festival; family return; preparation traditions |
| 41 | Health and body | Body parts; traditional medicine; doctor visits; Thai massage; pharmacy |
| 42 | Shopping and money | Markets (ตลาด); shopping vocabulary; bargaining culture; Thai baht; modern shopping |
| 43 | Communication and technology | Modern Thai internet vocabulary; LINE messaging app (dominant in Thailand); Thai social media |
| 44 | **Theravada Buddhism in daily life** | Wat (temple) culture; making merit (ทำบุญ); monks and ordination; basic Buddhist vocabulary; respect protocols at temples |
| 45 | Thai geography and identity | Four regions (Central, Northern, Northeastern/Isan, Southern); major cities; geographic diversity |
| 46 | Diaspora context | Thai communities abroad (US, Australia, Europe); diaspora cultural maintenance; international Thai restaurants |
| 47 | Regional variety awareness | Bangkok vs. Chiang Mai vs. Isan vs. Southern; vocabulary differences; cultural distinctiveness |
| 48 | Indirect communication style | Thai communication patterns; saving face; greng jai; mai pen rai; reading context |
| 49 | "Sanuk" and Thai social values | Fun as cultural value; relationships and harmony; hierarchical respect |
| 50 | **A2 Review and consolidation** | Mock A2; ~1,800 vocab |

## 4.3 Level B1 — Intermediate (Weeks 51–90)

| W | Title | Core focus |
|---|---|---|
| 51–55 | Tone mastery in connected speech | Maintaining tone consistency at natural pace; tonal interaction patterns |
| 56–60 | Script fluency consolidation | Reading speed; word segmentation (no spaces between words); recognizing patterns |
| 61–65 | **Royal Thai (Rachasap) introduction** | Receptive understanding of royal vocabulary; when it's used; cultural significance; **lèse-majesté awareness** for learners |
| 66–70 | Buddhist monk register | Vocabulary for talking to/about monks; making merit vocabulary; temple etiquette deeper |
| 71–75 | Thai cultural concepts | Greng jai, mai pen rai, sanuk, jaidii in depth; how these affect communication |
| 76–80 | Thai history overview | Pre-Sukhothai era; Sukhothai (Ramkhamhaeng, ~1240-1438); Ayutthaya (1351-1767); Thonburi-Rattanakosin period (1767-present); Cold War era; constitutional monarchy; military governments; contemporary political tensions |
| 81–85 | Thai literature introduction | Sunthorn Phu (national poet); the Ramakien (Thai version of Ramayana); modern Thai novels; contemporary writers (Chart Korbjitti, Pira Sudham) |
| 86–90 | **B1 Review and consolidation** | Mock B1; ~3,500 vocab |

## 4.4 Level B2 — Upper-Intermediate (Weeks 91–125)

| Weeks | Focus | Notes |
|---|---|---|
| 91–100 | Advanced grammar refinements | Complex sentence types; classifier nuance; particle subtleties; formal register |
| 101–110 | Thai literature sustained | Khun Chang Khun Phaen (national epic); contemporary literature; Thai poetry traditions |
| 111–115 | News and journalism | Thai PBS; major newspapers; political vocabulary (carefully neutral); economic vocabulary |
| 116–120 | Thai cinema | Apichatpong Weerasethakul (Palme d'Or winner); Pen-ek Ratanaruang; contemporary Thai cinema; classic Thai films |
| 121–124 | Business and professional Thai | Thai business culture; formal correspondence; meetings; hierarchical workplace navigation |
| 125 | **B2 Review and consolidation** | Mock B2; ~5,500 vocab |

## 4.5 Level C1 — Advanced (Weeks 126–155)

| Weeks | Focus | Notes |
|---|---|---|
| 126–135 | Thai literature classical and modern | Sunthorn Phu's Phra Aphai Mani; Ramakien excerpts; modern novels; Thai poetry rhythms |
| 136–140 | Buddhist philosophy in Thai | Buddhist suttas in Thai; meditation terminology; Theravada doctrine; cultural-religious literacy |
| 141–145 | Royal Thai mastery | Active competence in Rachasap; understanding when and how to use; reading royal-context texts |
| 146–150 | Specialized professional Thai | Domain-specific advanced vocabulary; conference Thai |
| 151–154 | Regional varieties receptive | Northern (Kham Muang), Northeastern (Isan), Southern Thai recognition |
| 155 | **C1 Review and consolidation** | Mock C1; ~7,500 vocab |

## 4.6 Level C2 — Mastery (Weeks 156–180)

| Weeks | Focus | Notes |
|---|---|---|
| 156–160 | Classical scripts awareness | Khom Thai (Cambodian-derived sacred script); Lanna script (Northern Thai); cultural-historical context |
| 161–165 | Sukhothai-era classical Thai | Ramkhamhaeng inscription; classical Thai poetry forms |
| 166–170 | Thai poetry mastery | Klong, kap, glon — Thai poetry forms; major poets through history; rhythm and meter |
| 171–175 | Creative writing in Thai | Short fiction; poetry attempts; essay writing; formal correspondence |
| 176–178 | Comprehensive review | All-skills mastery; identify final gaps |
| 179–180 | **Capstone project** | Choose: (a) 5,000-word essay in Thai, (b) translate a Thai literary passage, (c) 30-minute podcast in Thai, (d) attend a Buddhist meditation retreat conducted in Thai and produce reflection, (e) CU-TFL assessment |

---

# PART 5 — CULTURAL ROTATION STRATEGY

Thailand has four main regions plus significant Thai diaspora. Cultural notes rotate across:

- **Central Thailand (ภาคกลาง)** — Bangkok (largest city, capital, cultural-political center), Ayutthaya (UNESCO former capital), Kanchanaburi (Death Railway WWII history), Sukhothai (UNESCO ancient capital), Lopburi
- **Northern Thailand (ภาคเหนือ) — Lanna culture** — Chiang Mai (cultural capital of the north, Lanna heritage), Chiang Rai (Golden Triangle area), Pai (mountain town), Mae Hong Son (hill tribe area)
- **Northeastern Thailand (ภาคอีสาน) — Isan, Lao-related culture** — Khon Kaen, Udon Thani, Nakhon Ratchasima (Korat), Nong Khai (Lao border), the spicy food region, sticky rice culture, distinctive music (mor lam, luk thung)
- **Southern Thailand (ภาคใต้)** — Hat Yai (commercial center), Phuket (international tourism), Krabi (limestone islands), Songkhla, the Malay-Muslim provinces (Yala, Pattani, Narathiwat)
- **Thai diaspora communities** — United States (Los Angeles "Thai Town," New York), Australia (Sydney, Melbourne), Germany, UK, Sweden; ethnic Thai communities in neighboring countries
- **Religious traditions** — Theravada Buddhism (~93% — the foundational cultural-religious matrix); Islam (~5-6%, concentrated in southern provinces, Malay-Muslim communities); Christianity (~1%, both Catholic and Protestant); Hinduism (small but historically influential); Chinese folk religion (among Sino-Thai); animism cross-cutting all (spirit houses, etc.)
- **Historical periods** — Pre-Sukhothai (Tai migrations from southern China; Mon and Khmer civilizations); Sukhothai Kingdom (1238-1438 — King Ramkhamhaeng, traditional founding of Thai script); Ayutthaya Kingdom (1351-1767 — height of premodern Thai power; sacked by Burmese 1767); Thonburi period (1767-1782); Rattanakosin / Bangkok era (1782-present; Chakri Dynasty); modernization under Mongkut/Rama IV (1851-1868) and Chulalongkorn/Rama V (1868-1910 — never colonized but reformed extensively); Constitutional Monarchy from 1932; Cold War era and Vietnam War (US military presence); rapid economic development 1980s-90s; 1997 Asian Financial Crisis; political polarization 2000s-present; military coups 2006, 2014; pro-democracy movements 2020-present
- **Cultural domains** — Thai literature (Khun Chang Khun Phaen national epic, Ramakien adaptation of Ramayana, Sunthorn Phu's poetry); Thai cinema (Apichatpong Weerasethakul, Pen-ek Ratanaruang); T-pop and Thai music (luk thung folk, mor lam Isan music, modern T-pop); Thai dance (khon classical masked dance, traditional regional dances); Muay Thai martial arts; classical music (piphat ensembles, ranat percussion)
- **Cuisine** — **regional cuisines distinctly different**; *pad thai* (national dish), *tom yum* (sour soup), *gaeng khiao wan* (green curry), *gaeng massaman* (massaman curry, Southern), *som tam* (papaya salad, Isan), *khao soi* (Northern curry noodle), *larb* (Isan minced meat salad), *gai yang* (grilled chicken), *mango sticky rice*, *roti* (Southern), Thai-Chinese cuisine (*khao man gai*, *kuay teow*); rice (jasmine, sticky), fish sauce, chilies, herbs (basil, lemongrass, kaffir lime) fundamental
- **Modern dynamism** — Thailand 4.0 economic strategy; tech and startups (Pruksa, Ascend Money); manufacturing hub (automotive, electronics); tourism economy (Bangkok, Phuket, Chiang Mai); contemporary arts and cinema; growing tech sector; aging society challenges; political tensions and pro-democracy movements; complex relationship with China and Southeast Asian neighbors
- **Sensitive topics** — **Monarchy and lèse-majesté law (Section 112) — illegal to defame the King, Queen, heir, or regent; up to 15 years per count; this affects what learners produce in Thai about the royal family**; southern insurgency (Yala, Pattani, Narathiwat, Malay-Muslim provinces, ongoing since 2004); political polarization (red-yellow shirts, military coups, pro-democracy movements); LGBT+ rights (relatively accepted culturally, legally slower); sex industry context (Bangkok, Pattaya); ethnic minority issues (hill tribes, stateless persons); modern slavery and migration issues; environmental concerns — handled honestly and neutrally; **lèse-majesté requires real caution in productive output**

**Lesson-generator instruction:** Cultural notes should be specific (named places, people, eras, dishes, festivals, films, music). **Rotate across the four regions (Central, Northern, Northeastern/Isan, Southern) and Thai diaspora**. Address Buddhist context centrally and respectfully. Address modern Thai dynamism alongside historical context. Religious diversity (Theravada Buddhist majority, Muslim minority in south, smaller communities) represented. **Lèse-majesté sensitivity: do not generate content that disparages, criticizes, or could be interpreted as insulting the Thai monarchy** — this is a legal issue, not just cultural preference. Sensitive topics handled neutrally and factually. Avoid both orientalist exotic-Thailand framing AND sex-tourism stereotypes.

---

# PART 6 — RESOURCES FOR THAI

## 6.1 Comprehensible Input

- **Learn Thai with Mod** (YouTube) — excellent, friendly content
- **ThaiPod101** (YouTube free + paid platform) — comprehensive
- **Pailin's Kitchen** (YouTube) — Thai cooking + clear Thai narration
- **Stu Jay Raj** (YouTube) — linguistic depth, advanced learners
- **Mike Pinpinto** (YouTube) — natural Thai conversations
- **Easy Thai** (YouTube) — street interviews
- **Thai PBS** — educational Thai TV content; slower, clearer Thai

## 6.2 Structured Courses

- **Textbooks:**
  - **Thai for Beginners** (Becker, Paiboon Publishing) — popular starter; available with audio
  - **Foundations of Thai** (Marvin Brown, AUA Language Center) — classic natural-method materials
  - **Linguaphone Thai** — audio-based
  - **Thai: An Essential Grammar** (Smyth, Routledge) — solid reference grammar
  - **Thai Reference Grammar** (Smyth) — comprehensive academic grammar
  - **Teach Yourself Thai** (Smyth) — TY series standard
  - **Reading Thai** (Iyer) — focused script-reading practice
- **Free online:**
  - **DLI Thai materials** — comprehensive government-developed; freely available
  - **Royal Thai Embassy materials** (various countries)
  - **AUA Language Center materials** (some available online)

## 6.3 Tutoring

- **iTalki** — abundant Thai tutors (Thailand-based, very affordable, $5-15/hr); strong recommendation
- **Preply** — similar
- **HelloTalk, Tandem** — many Thai speakers practicing English
- **In-country options:**
  - **AUA Language Center** (Bangkok, Chiang Mai) — famous for natural-method intensive Thai
  - **Chulalongkorn University Thai Program** — premier academic Thai
  - **Walen Thai School** — popular for expats
  - **Pro Language** (Bangkok)
  - **UNITY Thai School** (Chiang Mai)
  - **Many private schools** throughout Thailand for intensive immersion

## 6.4 Reading Practice by Level

- **A1-A2:** Children's books in Thai; simple readers; Becker textbook practice texts; ThaiPod101 reading materials
- **B1:** Newspaper articles (Thai Rath, Matichon); Thai fairy tales; short stories; LINE TODAY (news app)
- **B2:** Modern Thai fiction; contemporary novels; Thai PBS articles; Bangkok Post Thai-language sections
- **C1+:** Native literature — Khun Chang Khun Phaen (national epic); Chart Korbjitti novels; Sunthorn Phu poetry; contemporary literary fiction
- **C2:** Classical Thai — Ramakien (Thai Ramayana); Sukhothai inscriptions; Buddhist suttas in Thai

## 6.5 News and Media

- **Thai PBS** — educational broadcaster (clear Thai)
- **Channel 3, 7, 9, MCOT** — major Thai broadcasters
- **Thai Rath** — major newspaper
- **Matichon** — major newspaper
- **Bangkok Post (English) and Thai-language sections**
- **The Nation (English)**
- **MGR Online / Manager Online** — news
- **LINE TODAY** — major Thai news app
- **VOA Thai / BBC Thai** — international perspective in Thai

## 6.6 Film and TV by Level

- **A2:** Thai children's animation; clear TV content; Thai PBS educational
- **B1:** Thai *lakorn* (telenovelas — slower-paced, dramatic); cooking shows; travel programs
- **B2:** Mainstream Thai cinema; contemporary Thai films; classic Thai cinema (Pen-ek Ratanaruang)
- **C1:** Apichatpong Weerasethakul films (*Uncle Boonmee Who Can Recall His Past Lives* — Palme d'Or 2010); Thai auteur cinema; classic horror (*Nang Nak*); contemporary indie
- **C2:** Full native content; classical Thai dance and performance; documentaries

## 6.7 Music for Listening Practice

- **T-Pop** — BLACKPINK's Lisa (Lalisa Manobal) is Thai; 4EVE; PiXXiE; Tilly Birds; Three Man Down; F.HERO; growing T-pop scene
- **Modern Thai pop** — Cocktail, Bodyslam (legendary rock), Bird Thongchai (60s-present icon)
- **Luk Thung (ลูกทุ่ง)** — country/folk Thai music; rural themes; Sayan Sanya, Pongsri Woranut historical
- **Mor Lam (หมอลำ)** — Isan/Northeastern Thai folk music; rapid singing; sometimes called Thai rap by analogy
- **Classical Thai music** — *piphat* ensembles, *ranat ek* (xylophone), *khong wong* (gong circle); traditional and ceremonial
- **Buddhist chanting (สวดมนต์)** — Pali chanting in Thai temples; cultural-religious soundscape

## 6.8 Pronunciation Tools

- **Forvo** — native pronunciations
- **ThaiPod101 pronunciation series** — extensive
- **YouTube tone-training videos** — many available
- **Shadowing** — any Thai podcast or news; repeat each sentence aloud with tone consistency
- **Reading aloud** — Thai is highly phonemic once script is mastered; reading aloud daily essential

## 6.9 Apps and Tools

- **Anki** — essential for SRS; shared Thai decks available
- **Duolingo** — has Thai (decent quality)
- **Ling** — well-developed Thai course
- **Lingodeer** — Thai course
- **Memrise** — Thai courses
- **Drops** — Thai vocabulary, good script emphasis
- **Pimsleur** — Thai audio course (Pimsleur Premium has Thai)
- **Mango Languages** — Thai course
- **ThaiCloud.com / Thai2English.com** — Thai-English dictionaries with tone marks
- **Thai Dict** (multiple apps)

---

# PART 7 — DAILY PRACTICE FRAMEWORK (THAI-FLAVORED)

| Activity | Time | Frequency | Thai-specific notes |
|---|---|---|---|
| Vocab SRS (Anki) | 15–20 min | Daily | Cards from each lesson; **include tone marks in Thai script (not just transliteration)** |
| **Tone production drills** | 5–10 min | Daily through B1 | Five tones in connected speech; consistency in fast speech |
| **Script reading practice** | 10–15 min | Daily through A2 | Reading Thai text without transliteration; develop word-segmentation skill |
| Comprehensible input | 20–25 min | Daily | Learn Thai with Mod early; news at intermediate; films from B1 |
| Active output (journaling) | 10 min | Daily | Write 3–5 sentences daily in Thai script |
| Conversation with native | 30 min | 1–2× per week from Week 5 | iTalki Thai tutor; **practice polite particles** religiously (gendered) |
| Reading at level | 15 min | 4× per week | Children's books early; news at B1; literature at C1 |
| Listening practice | Anytime | Daily | T-pop and luk thung; news; podcasts |
| Pronunciation drill | 5 min | Daily | Reading aloud Thai script with tone consistency |

**Thai-specific habit recommendations:**

- Switch phone language to Thai around Week 15 (well-supported)
- **Use polite particles ALWAYS in Thai conversation** — non-negotiable for politeness
- Listen to Thai pop and luk thung daily — melodic, often clear enunciation
- Watch one Thai *lakorn* (telenovela) episode per week from Week 30 — extended exposure
- Visit a Thai temple if accessible; practice respectful behavior
- **Read Thai script daily** — even 5 minutes of script reading prevents regression
- Follow Thai Twitter/X or Instagram accounts in Thai from B1+
- **Avoid producing content about the Thai monarchy** until you're confident with Royal Thai vocabulary; receive content cautiously
- If considering travel: AUA Language Center in Bangkok or Chiang Mai is exceptionally good for intensive immersion

**Total daily commitment: 45–60 minutes minimum.** Similar to Korean/Japanese (FSI Cat IV). Reaching B2 typically takes 3-4 years of consistent effort — significantly longer than Spanish; comparable to Mandarin without the character load.

---

# PART 8 — ASSESSMENT MILESTONES

Thailand has a clear primary proficiency exam:

## 8.1 CU-TFL (Chulalongkorn University Test of Thai as a Foreign Language)

The dominant Thai-as-foreign-language proficiency exam, administered by Chulalongkorn University. Multi-level system. Recognized internationally for Thai proficiency.

## 8.2 Other Thai Assessments

- **University institutional assessments** — Chulalongkorn, Thammasat, Mahidol; various international programs
- **ACTFL OPI** — Oral Proficiency Interview available for Thai; widely recognized in US institutions
- **DLI Thai proficiency tests** — Defense Language Institute internal assessments
- **ILR levels** — US government scale (0-5)

| Level | Curriculum week | Format |
|---|---|---|
| CEFR A1 | End of Week 25 | Self-assessment; CU-TFL Beginner if available |
| CEFR A2 | End of Week 50 | CU-TFL Elementary; ACTFL Novice |
| CEFR B1 | End of Week 90 | CU-TFL Intermediate; ACTFL Intermediate |
| CEFR B2 | End of Week 125 | CU-TFL Advanced; ACTFL Advanced |
| CEFR C1 | End of Week 155 | CU-TFL Superior; ACTFL Superior |
| CEFR C2 | End of Week 180 | ACTFL Distinguished; specialized university certification |

## 8.3 ACTFL OPI

Particularly useful for Thai given the available infrastructure. DLI has a robust Thai program with well-developed assessment.

## 8.4 University Programs

- **Chulalongkorn University Thai Program** — premier Thai-for-foreigners program in Thailand
- **Thammasat University** — competitive academic Thai
- **Mahidol University** — international academic Thai
- **US universities offering Thai** — Cornell, Northern Illinois, Hawaii, Washington (Seattle), UCLA, Wisconsin-Madison
- **DLI (Defense Language Institute)** — Monterey, CA; rigorous Thai program

## 8.5 Self-Assessment

The lesson template's self-assessment checklist applies. For Thai, additionally rate weekly:

- **Tone fluency** — can you produce all 5 tones consistently in connected speech?
- **Tone determination from script** — can you read a Thai word and determine its tone correctly?
- **Polite particles** — do you use ครับ/ค่ะ/คะ automatically and correctly?
- **Classifier accuracy** — what percentage of nouns produced with correct classifier?
- **Script reading speed** — how quickly can you read Thai text?
- **Listening at native speed** — what percentage of a Thai PBS broadcast can you follow?

---

# PART 9 — COMMON CHALLENGES FOR ENGLISH SPEAKERS

## 9.1 The Thai Script

44 consonants in 3 classes, 15 vowels in various positions, 4 tone marks — a substantial upfront learning load. Curriculum response: systematic introduction Weeks 1-15; daily reading practice; transliteration weaned by Week 12.

## 9.2 The Consonant Class System

Determining tone requires knowing which class each consonant belongs to. Curriculum response: Weeks 6-10 introduce classes progressively; sustained practice.

## 9.3 Tone Production

Five phonemic tones — same conceptual challenge as Vietnamese/Mandarin. Curriculum response: Weeks 2-4 intensive; sustained drilling through B1.

## 9.4 Aspirated vs. Unaspirated Stops

English speakers don't distinguish phonemically; Thai does. Curriculum response: Week 1 with minimal pairs; sustained practice.

## 9.5 Vowel Length

Phonemic in Thai; allophonic in English. Curriculum response: Week 1; minimal pairs; sustained attention.

## 9.6 The ɯ Vowel (อึ/อือ)

High central unrounded — novel for English speakers. Curriculum response: Week 1; deliberate practice (same as Vietnamese ư).

## 9.7 Word Segmentation in Continuous Text

No spaces between words in Thai sentences. Curriculum response: introduced Week 9; sustained reading practice develops the skill.

## 9.8 Modifier-After-Noun Word Order

Like Vietnamese, French, Spanish; opposite of English. Curriculum response: explicit teaching Week 18.

## 9.9 Classifier System

Required with numbers and demonstratives. Curriculum response: introduced Week 16; sustained practice.

## 9.10 Polite Particles (ครับ/ค่ะ/คะ)

Mandatory in polite contexts; gendered. Curriculum response: Week 2; reinforced throughout.

## 9.11 Royal Thai (Rachasap)

A separate elevated vocabulary system. Curriculum response: introduced descriptively at B1 (Week 61-65); active use only when needed; cultural-legal context (lèse-majesté).

## 9.12 Pronoun System

Less elaborate than Vietnamese but still requires social-context awareness. Curriculum response: Weeks 5-6 introduction; ongoing calibration.

## 9.13 Indirect Communication Style

Greng jai, mai pen rai, face-saving culture. Curriculum response: cultural notes throughout; explicit teaching at B1.

## 9.14 The Plateau at B1→B2

Standard plateau; Thai has the additional challenge of mastering Royal Thai receptive understanding. Curriculum response: B1 gets 40 weeks; sustained practice.

## 9.15 Sino-Thai vs. Pali-Sanskrit Vocabulary Layers

Like Vietnamese has Sino-Vietnamese, Thai has both Chinese-derived (Sino-Thai) and Indic-derived (Pali-Sanskrit) vocabulary layers for different registers. Curriculum response: explicit at B1.

## 9.16 Lèse-Majesté Awareness

A legal-cultural reality affecting what learners should produce. Curriculum response: explicit treatment at B1; clear practical guidance.

---

# PART 10 — THAI-SPECIFIC NOTES FOR LESSON GENERATION

Notes for the AI generating each weekly Thai lesson, in addition to the universal pedagogical principles.

## 10.1 Lesson Template Adjustments for Thai

The universal 12-section template applies with these adjustments:

- **Add Section 13: Script Focus** (Weeks 1–20) — explicit script reading practice; consonant class drilling; tone-determination practice. Reduce after Week 20 as script becomes integrated.
- **Add Section 14: Tone Focus** (Weeks 2–40) — explicit tone production drilling; minimal pairs; connected speech consistency.
- **Section 2 (Key Vocabulary)** — **always show Thai script alongside transliteration in early weeks; transition to Thai script only by Week 12-15**; for nouns, **show the most common classifier**; mark Sino-Thai or Pali-Sanskrit etymology when relevant.
- **Section 3 (Grammar Focus)** — pattern + example format. Include Thai grammatical terminology where useful (*คำกริยา* verb, *คำนาม* noun, *วรรณยุกต์* tone).
- **Section 5 (Listening Exercise)** — A1: Learn Thai with Mod beginner content; A2: ThaiPod101 intermediate; B1+: Thai PBS, podcasts; B2+: films and native content.
- **Section 8 (Speaking Exercise)** — include tone production drills in A1 (every lesson!); throughout, include polite particle practice; reading Thai script aloud essential.

## 10.2 Vocabulary Selection

- Frequency-weighted Thai vocabulary (from Thai corpora)
- **Always show in Thai script with tone marks** by mid-A1
- **Always show classifiers with nouns** where applicable
- Mark Sino-Thai vs. Pali-Sanskrit etymology when relevant for register
- Include both formal Thai AND modern urban Thai code-switching where appropriate to level

## 10.3 Example Sentence Composition

- Write natural Thai that a native would produce
- Use SVO word order consistently
- Apply modifier-after-noun pattern correctly
- Use appropriate polite particles for context (gendered!)
- Use appropriate pronouns
- Reflect register appropriate to the level
- Reference Thai cultural contexts (cities, festivals, foods, music) — rotate across all four regions and diaspora
- Buddhist cultural references presented respectfully and descriptively
- **AVOID generating content critical of, mocking, or potentially insulting the Thai monarchy** — this is a legal sensitivity, not just preference; Rachasap should be presented descriptively when introduced

## 10.4 Cultural Notes

- High density throughout
- Specific places, eras, people, dishes, festivals, films, music, cultural figures
- **Rotate across the four regions (Central, Northern, Northeastern/Isan, Southern) and Thai diaspora**
- Address Buddhist context centrally and respectfully
- Modern Thai dynamism (tech, T-pop, contemporary arts, tourism) alongside traditional context
- Religious diversity (Theravada Buddhist majority, Muslim minority south, smaller communities) presented descriptively
- **Lèse-majesté sensitivity** — do not generate disparaging royal content
- Sensitive topics (southern insurgency, political polarization, military coups, LGBT+ status, sex industry) handled neutrally and factually when they appear
- Avoid orientalist exotic-Thailand framing OR sex-tourism stereotypes
- Represent modern urban Thai life alongside traditional contexts

## 10.5 Listening Recommendations

- A1: Learn Thai with Mod beginner; Pailin's Kitchen with clear narration
- A2: ThaiPod101 intermediate; slow Thai PBS; simple T-pop
- B1: T-pop full speed; Thai PBS news; podcasts
- B2: Full TV programming; Thai *lakorn*; films with subtitles
- C1+: Native podcasts unrestricted; Buddhist dharma talks; literary readings; political discourse

## 10.6 Reading Passages by Level

Calibrated to level (in Thai script from Week 12 onward):

- **A1:** ~50–100 Thai-script words; present tense particles; high-frequency vocab; clear tone marks visible
- **A2:** ~150–250 words; past and future particles; varied registers; classifiers used
- **B1:** ~300–500 words; complex sentences; idioms; Sino-Thai/Pali-Sanskrit vocabulary appearing
- **B2:** ~600–800 words; literary or journalistic register; advanced grammar
- **C1:** ~1,000–1,500 words; sophisticated register; literary Thai
- **C2:** ~2,000+ words; native-quality including classical and contemporary; Royal Thai contexts when applicable

## 10.7 Grammar Explanations

- In English through B1; transitioning to Thai for grammar terms at B2+
- Include Thai grammatical terminology where appropriate
- Pattern + example + translation + explanation + common pitfall format
- Contrast with English where helpful — many illuminating contrasts due to analytic grammar, script system, and tone system

## 10.8 Pronunciation Section

Every lesson, especially A1-A2:

- **A1:** Specific tone focus + aspiration + vowel length; minimal pairs; reading aloud
- **A2:** Connected speech tones; rhythm and stress patterns
- **B1+:** Regional accent recognition; natural-speed tone production
- **B2+:** Classical text pronunciation; Buddhist chanting awareness

## 10.9 Drill Variety

- Mix at least three of: tone identification, tone production, classifier selection, polite particle calibration, script reading, sentence transformation, translation (both directions)
- Avoid pure multiple-choice except for nuance items
- Include tone-determination-from-script drilling explicitly through A1-A2

## 10.10 The Weekly Challenge

Examples calibrated to level:

- A1: Have a 1-minute self-introduction conversation in Thai with a tutor (with correct polite particles and pronouns)
- A2: Order Thai food in Thai at a Thai restaurant or roleplay; navigate spice levels
- B1: Watch one Thai *lakorn* episode and summarize the plot in Thai
- B2: Watch an Apichatpong Weerasethakul film and discuss themes in Thai
- C1: Read a Sunthorn Phu poetry excerpt and write a brief analysis
- C2: Engage in unscripted debate in Thai; attempt classical Thai poetry recitation; or write a literary essay

## 10.11 Religious, Political, and Legal Sensitivity

For lesson generators (AI or human):

- The curriculum is for learners interested in Thai-speaking communities — Bangkok, regional Thailand, Thai diaspora
- Religious diversity (Theravada Buddhist majority, Muslim minority south, Christian minority, smaller communities) presented descriptively
- Buddhist practices and concepts taught respectfully and with cultural accuracy
- For political topics (military governments, political polarization, pro-democracy movements, southern conflict, LGBT+ status): present factually and neutrally
- **Lèse-majesté (Section 112)** is a serious legal matter:
  - DO NOT generate Thai content that defames, mocks, criticizes, or could be interpreted as insulting the Thai monarchy (King, Queen, heir, regent)
  - Present Rachasap (Royal Thai) descriptively when introduced
  - Note lèse-majesté legal context explicitly when relevant
  - This is for the learner's legal protection, not editorial position
- Avoid orientalist "exotic Thailand" framing
- Avoid sex-tourism stereotypes; sex industry context exists but isn't the curriculum's focus
- Modern Thai dynamism (tech, T-pop, contemporary arts, tourism, manufacturing) featured alongside traditional culture
- Hill tribe and ethnic minority issues presented respectfully when they appear
- Note where Thai perspectives may differ from Western media narratives without endorsing either

---

*End of document. This is the Thai-specific reference for the language learning project. The next deliverable (when ready for the build phase) would be the structured curriculum data (\`lib/curricula/thai.ts\`) with all 180 weeks as TypeScript objects matching the schema used for other languages.*
`;
