// lib/curricula/index.ts
// Auto-generated by scripts/extract-curricula.ts
// Imports all 31 language curricula and provides lookup helpers.

import type { Curriculum } from '../types';
import { spanishCurriculum } from './spanish';
import { frenchCurriculum } from './french';
import { italianCurriculum } from './italian';
import { portugueseCurriculum } from './portuguese';
import { dutchCurriculum } from './dutch';
import { danishCurriculum } from './danish';
import { swedishCurriculum } from './swedish';
import { norwegianCurriculum } from './norwegian';
import { germanCurriculum } from './german';
import { swahiliCurriculum } from './swahili';
import { indonesianCurriculum } from './indonesian';
import { greekCurriculum } from './greek';
import { englishCurriculum } from './english';
import { russianCurriculum } from './russian';
import { polishCurriculum } from './polish';
import { ukrainianCurriculum } from './ukrainian';
import { hindiCurriculum } from './hindi';
import { bengaliCurriculum } from './bengali';
import { urduCurriculum } from './urdu';
import { persianCurriculum } from './persian';
import { filipinoCurriculum } from './filipino';
import { cebuanoCurriculum } from './cebuano';
import { vietnameseCurriculum } from './vietnamese';
import { turkishCurriculum } from './turkish';
import { hebrewCurriculum } from './hebrew';
import { irishCurriculum } from './irish';
import { mandarinCurriculum } from './mandarin';
import { japaneseCurriculum } from './japanese';
import { koreanCurriculum } from './korean';
import { arabicCurriculum } from './arabic';
import { thaiCurriculum } from './thai';

export const CURRICULA: Record<string, Curriculum> = {
  es: spanishCurriculum,
  fr: frenchCurriculum,
  it: italianCurriculum,
  pt: portugueseCurriculum,
  nl: dutchCurriculum,
  da: danishCurriculum,
  sv: swedishCurriculum,
  no: norwegianCurriculum,
  de: germanCurriculum,
  sw: swahiliCurriculum,
  id: indonesianCurriculum,
  el: greekCurriculum,
  en: englishCurriculum,
  ru: russianCurriculum,
  pl: polishCurriculum,
  uk: ukrainianCurriculum,
  hi: hindiCurriculum,
  bn: bengaliCurriculum,
  ur: urduCurriculum,
  fa: persianCurriculum,
  tl: filipinoCurriculum,
  ceb: cebuanoCurriculum,
  vi: vietnameseCurriculum,
  tr: turkishCurriculum,
  he: hebrewCurriculum,
  ga: irishCurriculum,
  zh: mandarinCurriculum,
  ja: japaneseCurriculum,
  ko: koreanCurriculum,
  ar: arabicCurriculum,
  th: thaiCurriculum,
};

export function getCurriculum(langCode: string): Curriculum | undefined {
  return CURRICULA[langCode];
}

export function getAllCurricula(): Curriculum[] {
  return Object.values(CURRICULA);
}
